#!/bin/bash

# fiddle_run executes the build fiddle (from the local
# skia tree's out/Release_Developer directory) and places the output
# png into the inout directory so it can be seen
# outside the chroot jail and served back to the user. 

[ -z $SKIA_ROOT ] && SKIA_ROOT="/skia_build/skia"
[ -z $WEBTRY_INOUT ] && WEBTRY_INOUT="/skia_build/inout"

if [ "$(uname)" == "Linux" ]; then
	EXECUTABLE="$SKIA_ROOT/out/Release_Developer/fiddle_secwrap $SKIA_ROOT/out/Release_Developer/$1"
else
	EXECUTABLE="$SKIA_ROOT/out/Release_Developer/$1"
fi

echo "-=-=-=-=-=-=-"
$EXECUTABLE "${@:2}"
