// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	types "go.skia.org/infra/task_scheduler/go/types"
)

// TaskExecutor is an autogenerated mock type for the TaskExecutor type
type TaskExecutor struct {
	mock.Mock
}

// GetFreeMachines provides a mock function with given fields: ctx, pool
func (_m *TaskExecutor) GetFreeMachines(ctx context.Context, pool string) ([]*types.Machine, error) {
	ret := _m.Called(ctx, pool)

	if len(ret) == 0 {
		panic("no return value specified for GetFreeMachines")
	}

	var r0 []*types.Machine
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*types.Machine, error)); ok {
		return rf(ctx, pool)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*types.Machine); ok {
		r0 = rf(ctx, pool)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*types.Machine)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, pool)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPendingTasks provides a mock function with given fields: ctx, pool
func (_m *TaskExecutor) GetPendingTasks(ctx context.Context, pool string) ([]*types.TaskResult, error) {
	ret := _m.Called(ctx, pool)

	if len(ret) == 0 {
		panic("no return value specified for GetPendingTasks")
	}

	var r0 []*types.TaskResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*types.TaskResult, error)); ok {
		return rf(ctx, pool)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*types.TaskResult); ok {
		r0 = rf(ctx, pool)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*types.TaskResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, pool)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTaskCompletionStatuses provides a mock function with given fields: ctx, taskIDs
func (_m *TaskExecutor) GetTaskCompletionStatuses(ctx context.Context, taskIDs []string) ([]bool, error) {
	ret := _m.Called(ctx, taskIDs)

	if len(ret) == 0 {
		panic("no return value specified for GetTaskCompletionStatuses")
	}

	var r0 []bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) ([]bool, error)); ok {
		return rf(ctx, taskIDs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string) []bool); ok {
		r0 = rf(ctx, taskIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]bool)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = rf(ctx, taskIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTaskResult provides a mock function with given fields: ctx, taskID, includeStats
func (_m *TaskExecutor) GetTaskResult(ctx context.Context, taskID string, includeStats bool) (*types.TaskResult, error) {
	ret := _m.Called(ctx, taskID, includeStats)

	if len(ret) == 0 {
		panic("no return value specified for GetTaskResult")
	}

	var r0 *types.TaskResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, bool) (*types.TaskResult, error)); ok {
		return rf(ctx, taskID, includeStats)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, bool) *types.TaskResult); ok {
		r0 = rf(ctx, taskID, includeStats)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.TaskResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, bool) error); ok {
		r1 = rf(ctx, taskID, includeStats)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Name provides a mock function with no fields
func (_m *TaskExecutor) Name() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Pools provides a mock function with no fields
func (_m *TaskExecutor) Pools() []string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Pools")
	}

	var r0 []string
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// TriggerTask provides a mock function with given fields: ctx, req
func (_m *TaskExecutor) TriggerTask(ctx context.Context, req *types.TaskRequest) (*types.TaskResult, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for TriggerTask")
	}

	var r0 *types.TaskResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *types.TaskRequest) (*types.TaskResult, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *types.TaskRequest) *types.TaskResult); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.TaskResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *types.TaskRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTaskExecutor creates a new instance of TaskExecutor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTaskExecutor(t interface {
	mock.TestingT
	Cleanup(func())
}) *TaskExecutor {
	mock := &TaskExecutor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
