[jumphosts]
rack1
rack2
rack3
rack4
rack5

[rack4_all]
skia-rpi2-rack4-shelf1-[001:020]
skia-rpi2-rack4-shelf1-[025:040]

[rack4_rpis:children]
rack4_shelf1
rack4_shelf2

[rack4_shelf1]
skia-rpi2-rack4-shelf1-[001:020]
skia-rpi2-rack4-shelf1-[025:040]

[rack4_shelf2]
skia-rpi2-rack4-shelf2-[001:024]