[jumphosts]
internal1
rack1
rack2
rack3
rack4

[rack4_trial_run]
skia-rpi2-rack4-shelf1-[001:004]


[rack4_rpis:children]
rack4_shelf1
rack4_shelf2

[rack4_shelf1]
skia-rpi2-rack4-shelf1-[001:040]

[rack4_shelf2]
skia-rpi2-rack4-shelf2-[001:024]