load("@rules_go//go:def.bzl", "go_library")
load("//bazel/go:go_test.bzl", "go_test")

go_library(
    name = "utils",
    srcs = ["utils.go"],
    importpath = "go.skia.org/infra/autogardener/go/utils",
    visibility = ["//visibility:public"],
    deps = [
        "//go/metrics2",
        "//go/skerr",
        "//go/sklog",
        "@com_github_cenkalti_backoff//:backoff",
        "@org_golang_google_genai//:genai",
        "@org_golang_x_time//rate",
    ],
)

go_test(
    name = "utils_test",
    srcs = ["utils_test.go"],
    embed = [":utils"],
    deps = ["@com_github_stretchr_testify//assert"],
)
