#!/bin/bash
# Builds and uploads a debian package for grandcentral.
APPNAME=grandcentral
SYSTEMD=${APPNAME}.service
DESCRIPTION="Central message passing app for Skia Infra"

# Copy files into the right locations in ${ROOT}.
copy_release_files()
{
INSTALL="sudo install -D --verbose --backup=none --group=root --owner=root"
INSTALL_DIR="sudo install -d --verbose --backup=none --group=root --owner=root"
${INSTALL} --mode=644 -T ./sys/${APPNAME}.service   ${ROOT}/etc/systemd/system/${APPNAME}.service
${INSTALL} --mode=755 -T ${GOPATH}/bin/grandcentral ${ROOT}/usr/local/bin/grandcentral
}

source ../bash/release.sh
