apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: alertmanager
spec:
  template:
    metadata:
      labels:
        app: alertmanager
    spec:
      containers:
      - name: alertmanager
        image: prom/alertmanager:v0.14.0
        ports:
          - name: http
            containerPort: 8080
        args:
          - "--web.listen-address=:8080"
          - "--config.file=/etc/alertmanager/alertmanager-config.yml"
          - "--storage.path=/alertmanager"
        volumeMounts:
        - name: alertmanager-volume
          mountPath: /etc/alertmanager
        - name: alertmanager
          mountPath: /alertmanager
      volumes:
        - name: alertmanager-volume
          configMap:
            name: alertmanager-conf
        - name: alertmanager
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: alertmanager
  name: alertmanager
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
  selector:
    app: alertmanager
  type: NodePort

