// Enable lit-plugin support.

import { BugTooltipSk } from './perf/modules/bug-tooltip-sk/bug-tooltip-sk';
import { AlertConfigSk } from './perf/modules/alert-config-sk/alert-config-sk';
import { AlertManagerSk } from './am/modules/alert-manager-sk/alert-manager-sk';
import { AlgoSelectSk } from './perf/modules/algo-select-sk/algo-select-sk';
import { AloginSk } from './infra-sk/modules/alogin-sk/alogin-sk';
import { AndroidLayersSk } from './debugger-app/modules/android-layers-sk/android-layers-sk';
import { AnomaliesTableSk } from './perf/modules/anomalies-table-sk/anomalies-table-sk';
import { AppSk } from './infra-sk/modules/app-sk/app-sk';
import { ARBConfigSk } from './autoroll/modules/arb-config-sk/arb-config-sk';
import { ARBModeHistorySk } from './autoroll/modules/arb-mode-history-sk/arb-mode-history-sk';
import { ARBRollHistorySk } from './autoroll/modules/arb-roll-history-sk/arb-roll-history-sk';
import { ARBScaffoldSk } from './autoroll/modules/arb-scaffold-sk/arb-scaffold-sk';
import { ARBStatusSk } from './autoroll/modules/arb-status-sk/arb-status-sk';
import { ARBStrategyHistorySk } from './autoroll/modules/arb-strategy-history-sk/arb-strategy-history-sk';
import { ARBTableSk } from './autoroll/modules/arb-table-sk/arb-table-sk';
import { AutoAssignSk } from './am/modules/auto-assign-sk/auto-assign-sk';
import { AutogrowTextareaSk } from './infra-sk/modules/autogrow-textarea-sk/autogrow-textarea-sk';
import { AutoRefreshSk } from './machine/modules/auto-refresh-sk/auto-refresh-sk';
import { AutorollerStatusSk } from './status/modules/autoroller-status-sk/autoroller-status-sk';
import { BinaryDiffPageSk } from './codesize/modules/binary-diff-page-sk/binary-diff-page-sk';
import { BinaryPageSk } from './codesize/modules/binary-page-sk/binary-page-sk';
import { BisectDialogSk } from './perf/modules/bisect-dialog-sk/bisect-dialog-sk';
import { BlamelistPanelSk } from './golden/modules/blamelist-panel-sk/blamelist-panel-sk';
import { BotChooserSk } from './am/modules/bot-chooser-sk/bot-chooser-sk';
import { BranchesSk } from './status/modules/branches-sk/branches-sk';
import { BugsCentralScaffoldSk } from './bugs-central/modules/bugs-central-scaffold-sk/bugs-central-scaffold-sk';
import { BugsCentralSk } from './bugs-central/modules/bugs-central-sk/bugs-central-sk';
import { BugsChartSk } from './bugs-central/modules/bugs-chart-sk/bugs-chart-sk';
import { BugsSLOPopupSk } from './bugs-central/modules/bugs-slo-popup-sk/bugs-slo-popup-sk';
import { BugsStatusSk } from './status/modules/bugs-status-sk/bugs-status-sk';
import { BulkTriageSk } from './golden/modules/bulk-triage-sk/bulk-triage-sk';
import { ByBlameEntrySk } from './golden/modules/byblameentry-sk/byblameentry-sk';
import { ByBlamePageSk } from './golden/modules/byblame-page-sk/byblame-page-sk';
import { CalendarInputSk } from './perf/modules/calendar-input-sk/calendar-input-sk';
import { CalendarSk } from './perf/modules/calendar-sk/calendar-sk';
import { CapacitySk } from './status/modules/capacity-sk/capacity-sk';
import { ChangelistControlsSk } from './golden/modules/changelist-controls-sk/changelist-controls-sk';
import { ChangelistsPageSk } from './golden/modules/changelists-page-sk/changelists-page-sk';
import { ChartTooltipSk } from './perf/modules/chart-tooltip-sk/chart-tooltip-sk';
import { CheckOrRadio } from './elements-sk/modules/checkbox-sk/checkbox-sk';
import { ClipboardSk } from './infra-sk/modules/clipboard-sk/clipboard-sk';
import { ClusterDigestsSk } from './golden/modules/cluster-digests-sk/cluster-digests-sk';
import { ClusterLastNPageSk } from './perf/modules/cluster-lastn-page-sk/cluster-lastn-page-sk';
import { ClusterPageSk } from './perf/modules/cluster-page-sk/cluster-page-sk';
import { ClusterSummary2Sk } from './perf/modules/cluster-summary2-sk/cluster-summary2-sk';
import { CodesizeScaffoldSk } from './codesize/modules/codesize-scaffold-sk/codesize-scaffold-sk';
import { CollapseSk } from './elements-sk/modules/collapse-sk/collapse-sk';
import { CommandsSk } from './debugger-app/modules/commands-sk/commands-sk';
import { CommentsSk } from './status/modules/comments-sk/comments-sk';
import { CommitDetailPanelSk } from './perf/modules/commit-detail-panel-sk/commit-detail-panel-sk';
import { CommitDetailPickerSk } from './perf/modules/commit-detail-picker-sk/commit-detail-picker-sk';
import { CommitDetailSk } from './perf/modules/commit-detail-sk/commit-detail-sk';
import { CommitRangeSk } from './perf/modules/commit-range-sk/commit-range-sk';
import { CommitsTableSk } from './status/modules/commits-table-sk/commits-table-sk';
import { ConfirmDialogSk } from './infra-sk/modules/confirm-dialog-sk/confirm-dialog-sk';
import { CorpusSelectorSk } from './golden/modules/corpus-selector-sk/corpus-selector-sk';
import { CyclerButtonSk } from './debugger-app/modules/cycler-button-sk/cycler-button-sk';
import { DayRangeSk } from './perf/modules/day-range-sk/day-range-sk';
import { DebuggerAppSk } from './shaders/modules/debugger-app-sk/debugger-app-sk';
import { DebuggerPageSk } from './debugger-app/modules/debugger-page-sk/debugger-page-sk';
import { DebugViewSk } from './debugger-app/modules/debug-view-sk/debug-view-sk';
import { DemoListSk } from './demos/modules/demo-list-sk/demo-list-sk';
import { DetailsDialogSk } from './status/modules/details-dialog-sk/details-dialog-sk';
import { DetailsPageSk } from './golden/modules/details-page-sk/details-page-sk';
import { DeviceEditorSk } from './machine/modules/device-editor-sk/device-editor-sk';
import { DiffPageSk } from './golden/modules/diff-page-sk/diff-page-sk';
import { DigestDetailsSk } from './golden/modules/digest-details-sk/digest-details-sk';
import { DisplayTreeStatusSk } from './tree_status/modules/display-tree-status-sk/display-tree-status-sk';
import { DomainPickerSk } from './perf/modules/domain-picker-sk/domain-picker-sk';
import { DotsLegendSk } from './golden/modules/dots-legend-sk/dots-legend-sk';
import { DotsSk } from './golden/modules/dots-sk/dots-sk';
import { EditChildShaderSk } from './shaders/modules/edit-child-shader-sk/edit-child-shader-sk';
import { EditIgnoreRuleSk } from './golden/modules/edit-ignore-rule-sk/edit-ignore-rule-sk';
import { EmailChooserSk } from './am/modules/email-chooser-sk/email-chooser-sk';
import { EnterTreeStatus } from './tree_status/modules/enter-tree-status-sk/enter-tree-status-sk';
import { ErrorToastSk } from './elements-sk/modules/error-toast-sk/error-toast-sk';
import { ExampleControlSk } from './new_element/modules/example-control-sk/example-control-sk';
import { ExistingBugDialogSk } from './perf/modules/existing-bug-dialog-sk/existing-bug-dialog-sk';
import { ExpandableTextareaSk } from './infra-sk/modules/expandable-textarea-sk/expandable-textarea-sk';
import { ExploreMultiSk } from './perf/modules/explore-multi-sk/explore-multi-sk';
import { ExploreSimpleSk } from './perf/modules/explore-simple-sk/explore-simple-sk';
import { ExploreSk } from './perf/modules/explore-sk/explore-sk';
import { FavoritesDialogSk } from './perf/modules/favorites-dialog-sk/favorites-dialog-sk';
import { FavoritesSk } from './perf/modules/favorites-sk/favorites-sk';
import { FiddleEmbed } from './fiddlek/modules/fiddle-embed-sk/fiddle-embed-sk';
import { FiddleSk } from './fiddlek/modules/fiddle-sk/fiddle-sk';
import { FilterDialogSk } from './golden/modules/filter-dialog-sk/filter-dialog-sk';
import { GoldScaffoldSk } from './golden/modules/gold-scaffold-sk/gold-scaffold-sk';
import { GoldStatusSk } from './status/modules/gold-status-sk/gold-status-sk';
import { GraphTitleSk } from './perf/modules/graph-title-sk/graph-title-sk';
import { HistogramSk } from './debugger-app/modules/histogram-sk/histogram-sk';
import { HumanDateSk } from './infra-sk/modules/human-date-sk/human-date-sk';
import { IgnoresPageSk } from './golden/modules/ignores-page-sk/ignores-page-sk';
import { ImageCompareSk } from './golden/modules/image-compare-sk/image-compare-sk';
import { IncidentSk } from './am/modules/incident-sk/incident-sk';
import { IndexPageSk } from './codesize/modules/index-page-sk/index-page-sk';
import { JobSearchSk } from './task_scheduler/modules/job-search-sk/job-search-sk';
import { JobSk } from './task_scheduler/modules/job-sk/job-sk';
import { JobTimelineSk } from './task_scheduler/modules/job-timeline-sk/job-timeline-sk';
import { JobTriggerSk } from './task_scheduler/modules/job-trigger-sk/job-trigger-sk';
import { JSONSourceSk } from './perf/modules/json-source-sk/json-source-sk';
import { LastCommitSk } from './golden/modules/last-commit-sk/last-commit-sk';
import { LeasingListSk } from './leasing/modules/leasing-list-sk/leasing-list-sk';
import { LeasingScaffoldSk } from './leasing/modules/leasing-scaffold-sk/leasing-scaffold-sk';
import { LeasingSelectionsSk } from './leasing/modules/leasing-selections-sk/leasing-selections-sk';
import { LeasingTaskSk } from './leasing/modules/leasing-task-sk/leasing-task-sk';
import { ListAutorollersSk } from './tree_status/modules/list-autorollers-sk/list-autorollers-sk';
import { ListPageSk } from './golden/modules/list-page-sk/list-page-sk';
import { MachineAppSk } from './machine/modules/machine-app-sk';
import { MachinesTableSk } from './machine/modules/machines-table-sk';
import { MachineTableColumnsDialogSk } from './machine/modules/machine-table-columns-dialog-sk/machine-table-columns-dialog-sk';
import { MultiInputSk } from './infra-sk/modules/multi-input-sk/multi-input-sk';
import { MultiSelectSk } from './elements-sk/modules/multi-select-sk/multi-select-sk';
import { MultiZoomSk } from './golden/modules/multi-zoom-sk/multi-zoom-sk';
import { NavButtonSk } from './elements-sk/modules/nav-button-sk/nav-button-sk';
import { NavigationSk } from './status/modules/navigation-sk/navigation-sk';
import { NavLinksSk } from './elements-sk/modules/nav-links-sk/nav-links-sk';
import { NewBugDialogSk } from './perf/modules/new-bug-dialog-sk/new-bug-dialog-sk';
import { NoteEditorSk } from './machine/modules/note-editor-sk/note-editor-sk';
import { ParamSetSk } from './infra-sk/modules/paramset-sk/paramset-sk';
import { PerfScaffoldSk } from './perf/modules/perf-scaffold-sk/perf-scaffold-sk';
import { PerfStatusSk } from './status/modules/perf-status-sk/perf-status-sk';
import { PickerFieldSk } from './perf/modules/picker-field-sk/picker-field-sk';
import { PinpointTryJobDialogSk } from './perf/modules/pinpoint-try-job-dialog-sk/pinpoint-try-job-dialog-sk';
import { PivotQuerySk } from './perf/modules/pivot-query-sk/pivot-query-sk';
import { PivotTableSk } from './perf/modules/pivot-table-sk/pivot-table-sk';
import { PlaySk } from './debugger-app/modules/play-sk/play-sk';
import { PlotGoogleChartSk } from './perf/modules/plot-google-chart-sk/plot-google-chart-sk';
import { PlotSimpleSk } from './perf/modules/plot-simple-sk/plot-simple-sk';
import { PlotSummarySk } from './perf/modules/plot-summary-sk/plot-summary-sk';
import { PointLinksSk } from './perf/modules/point-links-sk/point-links-sk';
import { ProcessingTableSk } from './skcq/modules/processing-table-sk/processing-table-sk';
import { QueryChooserSk } from './perf/modules/query-chooser-sk/query-chooser-sk';
import { QueryCountSk } from './perf/modules/query-count-sk/query-count-sk';
import { QueryDialogSk } from './golden/modules/query-dialog-sk/query-dialog-sk';
import { QuerySk } from './infra-sk/modules/query-sk/query-sk';
import { QueryValuesSk } from './infra-sk/modules/query-values-sk/query-values-sk';
import { RadioElement } from './elements-sk/modules/radio-sk/radio-sk';
import { RegressionsPageSk } from './perf/modules/regressions-page-sk/regressions-page-sk';
import { ReportPageSk } from './perf/modules/report-page-sk/report-page-sk';
import { ResourcesSk } from './debugger-app/modules/resources-sk/resources-sk';
import { RevisionInfoSk } from './perf/modules/revision-info-sk/revision-info-sk';
import { RotationsSk } from './status/modules/rotations-sk/rotations-sk';
import { ScrapExchangeSk } from './scrap/modules/scrap-exchange-sk/scrap-exchange-sk';
import { ScreenshotsViewerSk } from './puppeteer-tests/modules/screenshots-viewer-sk/screenshots-viewer-sk';
import { SearchControlsSk } from './golden/modules/search-controls-sk/search-controls-sk';
import { SearchPageSk } from './golden/modules/search-page-sk/search-page-sk';
import { SelectSk } from './elements-sk/modules/select-sk/select-sk';
import { ShaderEditorSk } from './skottie/modules/skottie-shader-editor-sk/skottie-shader-editor-sk';
import { ShadersAppSk } from './shaders/modules/shaders-app-sk/shaders-app-sk';
import { SilenceSk } from './am/modules/silence-sk/silence-sk';
import { SkCQ } from './skcq/modules/skcq-sk/skcq-sk';
import { SkCQScaffold } from './skcq/modules/skcq-scaffold-sk/skcq-scaffold-sk';
import { SkipTasksSk } from './task_scheduler/modules/skip-tasks-sk/skip-tasks-sk';
import { SkottieAudioSk } from './skottie/modules/skottie-audio-sk/skottie-audio-sk';
import { SkottieBackgroundSettingsSk } from './skottie/modules/skottie-background-settings-sk/skottie-background-settings-sk';
import { SkottieButtonSk } from './skottie/modules/skottie-button-sk/skottie-button-sk';
import { SkottieColorInputSk } from './skottie/modules/skottie-color-input-sk/skottie-color-input-sk';
import { SkottieColorManagerSk } from './skottie/modules/skottie-color-manager-sk/skottie-color-manager-sk';
import { SkottieCompatibilitySk } from './skottie/modules/skottie-compatibility-sk/skottie-compatibility-sk';
import { SkottieConfigSk } from './skottie/modules/skottie-config-sk/skottie-config-sk';
import { SkottieDriveSk } from './skottie/modules/skottie-drive-sk/skottie-drive-sk';
import { SkottieDropdownSk } from './skottie/modules/skottie-dropdown-sk/skottie-dropdown-sk';
import { SkottieEmbedSk } from './skottie/modules/skottie-embed-sk/skottie-embed-sk';
import { SkottieExporterBaseSk } from './skottie/modules/skottie-exporter-sk/skottie-exporter-base-sk/skottie-exporter-base-sk';
import { SkottieExporterGifSk } from './skottie/modules/skottie-exporter-sk/skottie-exporter-gif-sk/skottie-exporter-gif-sk';
import { SkottieExporterPNGSk } from './skottie/modules/skottie-exporter-sk/skottie-exporter-png-sk/skottie-exporter-png-sk';
import { SkottieExporterSk } from './skottie/modules/skottie-exporter-sk/skottie-exporter-sk';
import { SkottieExporterWebMSk } from './skottie/modules/skottie-exporter-sk/skottie-exporter-webm-sk/skottie-exporter-webm-sk';
import { SkottieFileFormSk } from './skottie/modules/skottie-file-form-sk/skottie-file-form-sk';
import { SkottieFileSettingsSk } from './skottie/modules/skottie-file-settings-sk/skottie-file-settings-sk';
import { SkottieFontSelectorSk } from './skottie/modules/skottie-font-selector-sk/skottie-font-selector-sk';
import { SkottieGifExporterSk } from './skottie/modules/skottie-gif-exporter-sk/skottie-gif-exporter-sk';
import { SkottieInlineSk } from './skottie/modules/skottie-inline-sk/skottie-inline-sk';
import { SkottieLibrarySk } from './skottie/modules/skottie-library-sk/skottie-library-sk';
import { SkottiePerformanceSk } from './skottie/modules/skottie-performance-sk/skottie-performance-sk';
import { SkottiePlayerSk } from './skottie/modules/skottie-player-sk/skottie-player-sk';
import { SkottieSk } from './skottie/modules/skottie-sk/skottie-sk';
import { SkottieSlotManagerSk } from './skottie/modules/skottie-slot-manager-sk/skottie-slot-manager-sk';
import { SkottieTextEditorBoxSk } from './skottie/modules/skottie-text-editor-sk/text-box-sk/text-box-sk';
import { SkottieTextEditorSk } from './skottie/modules/skottie-text-editor-sk/skottie-text-editor-sk';
import { SkottieTextSamplerSk } from './skottie/modules/skottie-text-sampler-sk/skottie-text-sampler-sk';
import { SkottieVec2InputSk } from './skottie/modules/skottie-slot-manager-sk/skottie-vec2-input-sk';
import { SortSk } from './infra-sk/modules/sort-sk/sort-sk';
import { SortToggleSk } from './golden/modules/sort-toggle-sk/sort-toggle-sk';
import { SpinnerSk } from './elements-sk/modules/spinner-sk/spinner-sk';
import { SplitChartMenuSk } from './perf/modules/split-chart-menu-sk/split-chart-menu-sk';
import { StatusSk } from './status/modules/status-sk/status-sk';
import { SubscriptionTableSk } from './perf/modules/subscription-table-sk/subscription-table-sk';
import { TabsPanelSk } from './elements-sk/modules/tabs-panel-sk/tabs-panel-sk';
import { TabsSk } from './elements-sk/modules/tabs-sk/tabs-sk';
import { TaskDriverSk } from './infra-sk/modules/task-driver-sk/task-driver-sk';
import { TaskGraphSk } from './task_scheduler/modules/task-graph-sk/task-graph-sk';
import { TaskSchedulerScaffoldSk } from './task_scheduler/modules/task-scheduler-scaffold-sk/task-scheduler-scaffold-sk';
import { TaskSk } from './task_scheduler/modules/task-sk/task-sk';
import { TestPickerSk } from './perf/modules/test-picker-sk/test-picker-sk';
import { TestSrcSk } from './fiddlek/modules/test-src-sk/test-src-sk';
import { TextareaNumbersSk } from './fiddlek/modules/textarea-numbers-sk/textarea-numbers-sk';
import { ThemeChooserSk } from './infra-sk/modules/theme-chooser-sk/theme-chooser-sk';
import { TimelineSk } from './debugger-app/modules/timeline-sk/timeline-sk';
import { ToastSk } from './elements-sk/modules/toast-sk/toast-sk';
import { ToolsSk } from './tool/modules/tools-sk/tools-sk';
import { TooltipSk } from './infra-sk/modules/tooltip-sk/tooltip-sk';
import { TraceFilterSk } from './golden/modules/trace-filter-sk/trace-filter-sk';
import { TreeScaffoldSk } from './tree_status/modules/tree-scaffold-sk/tree-scaffold-sk';
import { TreeStatusSk } from './status/modules/tree-status-sk/tree-status-sk';
import { TriagelogPageSk } from './golden/modules/triagelog-page-sk/triagelog-page-sk';
import { TriageMenuSk } from './perf/modules/triage-menu-sk/triage-menu-sk';
import { TriagePageSk } from './perf/modules/triage-page-sk/triage-page-sk';
import { TriageSk } from './perf/modules/triage2-sk/triage2-sk';
import { TriageStatusSk } from './perf/modules/triage-status-sk/triage-status-sk';
import { TriconSk } from './perf/modules/tricon2-sk/tricon2-sk';
import { UniformColorSk } from './infra-sk/modules/uniform-color-sk/uniform-color-sk';
import { UniformDimensionsSk } from './infra-sk/modules/uniform-dimensions-sk/uniform-dimensions-sk';
import { UniformFpsSk } from './infra-sk/modules/uniform-fps-sk/uniform-fps-sk';
import { UniformGenericSk } from './infra-sk/modules/uniform-generic-sk/uniform-generic-sk';
import { UniformImageresolutionSk } from './infra-sk/modules/uniform-imageresolution-sk/uniform-imageresolution-sk';
import { UniformMouseSk } from './infra-sk/modules/uniform-mouse-sk/uniform-mouse-sk';
import { UniformSliderSk } from './infra-sk/modules/uniform-slider-sk/uniform-slider-sk';
import { UniformTimeSk } from './infra-sk/modules/uniform-time-sk/uniform-time-sk';
import { UserIssueSk } from './perf/modules/user-issue-sk/user-issue-sk';
import { VerifiersDetailSk } from './skcq/modules/verifiers-detail-sk/verifiers-detail-sk';
import { VersionPageSk } from './debugger-app/modules/version-page-sk/version-page-sk';
import { WordCloudSk } from './perf/modules/word-cloud-sk/word-cloud-sk';
import { ZoomSk } from './debugger-app/modules/zoom-sk/zoom-sk';

declare global {
  interface HTMLElementTagNameMap {
    // auto-generated icons are defined as a unnamed class.
    'access-alarm-icon-sk': HTMLElement;
    'access-alarms-icon-sk': HTMLElement;
    'accessibility-icon-sk': HTMLElement;
    'accessible-icon-sk': HTMLElement;
    'access-time-icon-sk': HTMLElement;
    'account-balance-icon-sk': HTMLElement;
    'account-balance-wallet-icon-sk': HTMLElement;
    'account-box-icon-sk': HTMLElement;
    'account-circle-icon-sk': HTMLElement;
    'ac-unit-icon-sk': HTMLElement;
    'adb-icon-sk': HTMLElement;
    'add-alarm-icon-sk': HTMLElement;
    'add-alert-icon-sk': HTMLElement;
    'add-a-photo-icon-sk': HTMLElement;
    'add-box-icon-sk': HTMLElement;
    'add-circle-icon-sk': HTMLElement;
    'add-circle-outline-icon-sk': HTMLElement;
    'add-icon-sk': HTMLElement;
    'add-location-icon-sk': HTMLElement;
    'add-shopping-cart-icon-sk': HTMLElement;
    'add-to-photos-icon-sk': HTMLElement;
    'add-to-queue-icon-sk': HTMLElement;
    'adjust-icon-sk': HTMLElement;
    'airline-seat-flat-angled-icon-sk': HTMLElement;
    'airline-seat-flat-icon-sk': HTMLElement;
    'airline-seat-individual-suite-icon-sk': HTMLElement;
    'airline-seat-legroom-extra-icon-sk': HTMLElement;
    'airline-seat-legroom-normal-icon-sk': HTMLElement;
    'airline-seat-legroom-reduced-icon-sk': HTMLElement;
    'airline-seat-recline-extra-icon-sk': HTMLElement;
    'airline-seat-recline-normal-icon-sk': HTMLElement;
    'airplanemode-active-icon-sk': HTMLElement;
    'airplanemode-inactive-icon-sk': HTMLElement;
    'airplay-icon-sk': HTMLElement;
    'airport-shuttle-icon-sk': HTMLElement;
    'alarm-add-icon-sk': HTMLElement;
    'alarm-icon-sk': HTMLElement;
    'alarm-off-icon-sk': HTMLElement;
    'alarm-on-icon-sk': HTMLElement;
    'album-icon-sk': HTMLElement;
    'all-inclusive-icon-sk': HTMLElement;
    'all-out-icon-sk': HTMLElement;
    'android-icon-sk': HTMLElement;
    'announcement-icon-sk': HTMLElement;
    'apps-icon-sk': HTMLElement;
    'archive-icon-sk': HTMLElement;
    'arrow-back-icon-sk': HTMLElement;
    'arrow-downward-icon-sk': HTMLElement;
    'arrow-drop-down-circle-icon-sk': HTMLElement;
    'arrow-drop-down-icon-sk': HTMLElement;
    'arrow-drop-up-icon-sk': HTMLElement;
    'arrow-forward-icon-sk': HTMLElement;
    'arrow-upward-icon-sk': HTMLElement;
    'art-track-icon-sk': HTMLElement;
    'aspect-ratio-icon-sk': HTMLElement;
    'assessment-icon-sk': HTMLElement;
    'assignment-icon-sk': HTMLElement;
    'assignment-ind-icon-sk': HTMLElement;
    'assignment-late-icon-sk': HTMLElement;
    'assignment-returned-icon-sk': HTMLElement;
    'assignment-return-icon-sk': HTMLElement;
    'assignment-turned-in-icon-sk': HTMLElement;
    'assistant-icon-sk': HTMLElement;
    'assistant-photo-icon-sk': HTMLElement;
    'attach-file-icon-sk': HTMLElement;
    'attachment-icon-sk': HTMLElement;
    'attach-money-icon-sk': HTMLElement;
    'audiotrack-icon-sk': HTMLElement;
    'autorenew-icon-sk': HTMLElement;
    'av-timer-icon-sk': HTMLElement;
    'backspace-icon-sk': HTMLElement;
    'backup-icon-sk': HTMLElement;
    'battery-20-icon-sk': HTMLElement;
    'battery-30-icon-sk': HTMLElement;
    'battery-50-icon-sk': HTMLElement;
    'battery-60-icon-sk': HTMLElement;
    'battery-80-icon-sk': HTMLElement;
    'battery-90-icon-sk': HTMLElement;
    'battery-alert-icon-sk': HTMLElement;
    'battery-charging-20-icon-sk': HTMLElement;
    'battery-charging-30-icon-sk': HTMLElement;
    'battery-charging-50-icon-sk': HTMLElement;
    'battery-charging-60-icon-sk': HTMLElement;
    'battery-charging-80-icon-sk': HTMLElement;
    'battery-charging-90-icon-sk': HTMLElement;
    'battery-charging-full-icon-sk': HTMLElement;
    'battery-full-icon-sk': HTMLElement;
    'battery-std-icon-sk': HTMLElement;
    'battery-unknown-icon-sk': HTMLElement;
    'beach-access-icon-sk': HTMLElement;
    'beenhere-icon-sk': HTMLElement;
    'block-icon-sk': HTMLElement;
    'bluetooth-audio-icon-sk': HTMLElement;
    'bluetooth-connected-icon-sk': HTMLElement;
    'bluetooth-disabled-icon-sk': HTMLElement;
    'bluetooth-icon-sk': HTMLElement;
    'bluetooth-searching-icon-sk': HTMLElement;
    'blur-circular-icon-sk': HTMLElement;
    'blur-linear-icon-sk': HTMLElement;
    'blur-off-icon-sk': HTMLElement;
    'blur-on-icon-sk': HTMLElement;
    'book-icon-sk': HTMLElement;
    'bookmark-border-icon-sk': HTMLElement;
    'bookmark-icon-sk': HTMLElement;
    'border-all-icon-sk': HTMLElement;
    'border-bottom-icon-sk': HTMLElement;
    'border-clear-icon-sk': HTMLElement;
    'border-color-icon-sk': HTMLElement;
    'border-horizontal-icon-sk': HTMLElement;
    'border-inner-icon-sk': HTMLElement;
    'border-left-icon-sk': HTMLElement;
    'border-outer-icon-sk': HTMLElement;
    'border-right-icon-sk': HTMLElement;
    'border-style-icon-sk': HTMLElement;
    'border-top-icon-sk': HTMLElement;
    'border-vertical-icon-sk': HTMLElement;
    'branding-watermark-icon-sk': HTMLElement;
    'brightness-1-icon-sk': HTMLElement;
    'brightness-2-icon-sk': HTMLElement;
    'brightness-3-icon-sk': HTMLElement;
    'brightness-4-icon-sk': HTMLElement;
    'brightness-5-icon-sk': HTMLElement;
    'brightness-6-icon-sk': HTMLElement;
    'brightness-7-icon-sk': HTMLElement;
    'brightness-auto-icon-sk': HTMLElement;
    'brightness-high-icon-sk': HTMLElement;
    'brightness-low-icon-sk': HTMLElement;
    'brightness-medium-icon-sk': HTMLElement;
    'broken-image-icon-sk': HTMLElement;
    'brush-icon-sk': HTMLElement;
    'bubble-chart-icon-sk': HTMLElement;
    'bug-report-icon-sk': HTMLElement;
    'build-icon-sk': HTMLElement;
    'burst-mode-icon-sk': HTMLElement;
    'business-center-icon-sk': HTMLElement;
    'business-icon-sk': HTMLElement;
    'cached-icon-sk': HTMLElement;
    'cake-icon-sk': HTMLElement;
    'call-end-icon-sk': HTMLElement;
    'call-icon-sk': HTMLElement;
    'call-made-icon-sk': HTMLElement;
    'call-merge-icon-sk': HTMLElement;
    'call-missed-icon-sk': HTMLElement;
    'call-missed-outgoing-icon-sk': HTMLElement;
    'call-received-icon-sk': HTMLElement;
    'call-split-icon-sk': HTMLElement;
    'call-to-action-icon-sk': HTMLElement;
    'camera-alt-icon-sk': HTMLElement;
    'camera-enhance-icon-sk': HTMLElement;
    'camera-front-icon-sk': HTMLElement;
    'camera-icon-sk': HTMLElement;
    'camera-rear-icon-sk': HTMLElement;
    'camera-roll-icon-sk': HTMLElement;
    'cancel-icon-sk': HTMLElement;
    'card-giftcard-icon-sk': HTMLElement;
    'card-membership-icon-sk': HTMLElement;
    'card-travel-icon-sk': HTMLElement;
    'casino-icon-sk': HTMLElement;
    'cast-connected-icon-sk': HTMLElement;
    'cast-icon-sk': HTMLElement;
    'center-focus-strong-icon-sk': HTMLElement;
    'center-focus-weak-icon-sk': HTMLElement;
    'change-history-icon-sk': HTMLElement;
    'chat-bubble-icon-sk': HTMLElement;
    'chat-bubble-outline-icon-sk': HTMLElement;
    'chat-icon-sk': HTMLElement;
    'check-box-icon-sk': HTMLElement;
    'check-box-outline-blank-icon-sk': HTMLElement;
    'check-circle-icon-sk': HTMLElement;
    'check-icon-sk': HTMLElement;
    'chevron-left-icon-sk': HTMLElement;
    'chevron-right-icon-sk': HTMLElement;
    'child-care-icon-sk': HTMLElement;
    'child-friendly-icon-sk': HTMLElement;
    'chrome-reader-mode-icon-sk': HTMLElement;
    'class-icon-sk': HTMLElement;
    'clear-all-icon-sk': HTMLElement;
    'clear-icon-sk': HTMLElement;
    'closed-caption-icon-sk': HTMLElement;
    'close-icon-sk': HTMLElement;
    'cloud-circle-icon-sk': HTMLElement;
    'cloud-done-icon-sk': HTMLElement;
    'cloud-download-icon-sk': HTMLElement;
    'cloud-icon-sk': HTMLElement;
    'cloud-off-icon-sk': HTMLElement;
    'cloud-queue-icon-sk': HTMLElement;
    'cloud-upload-icon-sk': HTMLElement;
    'code-icon-sk': HTMLElement;
    'collections-bookmark-icon-sk': HTMLElement;
    'collections-icon-sk': HTMLElement;
    'colorize-icon-sk': HTMLElement;
    'color-lens-icon-sk': HTMLElement;
    'comment-icon-sk': HTMLElement;
    'compare-arrows-icon-sk': HTMLElement;
    'compare-icon-sk': HTMLElement;
    'computer-icon-sk': HTMLElement;
    'confirmation-number-icon-sk': HTMLElement;
    'contact-mail-icon-sk': HTMLElement;
    'contact-phone-icon-sk': HTMLElement;
    'contacts-icon-sk': HTMLElement;
    'content-copy-icon-sk': HTMLElement;
    'content-cut-icon-sk': HTMLElement;
    'content-paste-icon-sk': HTMLElement;
    'control-point-duplicate-icon-sk': HTMLElement;
    'control-point-icon-sk': HTMLElement;
    'copyright-icon-sk': HTMLElement;
    'create-icon-sk': HTMLElement;
    'create-new-folder-icon-sk': HTMLElement;
    'credit-card-icon-sk': HTMLElement;
    'crop-16-9-icon-sk': HTMLElement;
    'crop-3-2-icon-sk': HTMLElement;
    'crop-5-4-icon-sk': HTMLElement;
    'crop-7-5-icon-sk': HTMLElement;
    'crop-din-icon-sk': HTMLElement;
    'crop-free-icon-sk': HTMLElement;
    'crop-icon-sk': HTMLElement;
    'crop-landscape-icon-sk': HTMLElement;
    'crop-original-icon-sk': HTMLElement;
    'crop-portrait-icon-sk': HTMLElement;
    'crop-rotate-icon-sk': HTMLElement;
    'crop-square-icon-sk': HTMLElement;
    'dashboard-icon-sk': HTMLElement;
    'data-usage-icon-sk': HTMLElement;
    'date-range-icon-sk': HTMLElement;
    'dehaze-icon-sk': HTMLElement;
    'delete-forever-icon-sk': HTMLElement;
    'delete-icon-sk': HTMLElement;
    'delete-sweep-icon-sk': HTMLElement;
    'description-icon-sk': HTMLElement;
    'desktop-mac-icon-sk': HTMLElement;
    'desktop-windows-icon-sk': HTMLElement;
    'details-icon-sk': HTMLElement;
    'developer-board-icon-sk': HTMLElement;
    'developer-mode-icon-sk': HTMLElement;
    'device-hub-icon-sk': HTMLElement;
    'devices-icon-sk': HTMLElement;
    'devices-other-icon-sk': HTMLElement;
    'dialer-sip-icon-sk': HTMLElement;
    'dialpad-icon-sk': HTMLElement;
    'directions-bike-icon-sk': HTMLElement;
    'directions-boat-icon-sk': HTMLElement;
    'directions-bus-icon-sk': HTMLElement;
    'directions-car-icon-sk': HTMLElement;
    'directions-icon-sk': HTMLElement;
    'directions-railway-icon-sk': HTMLElement;
    'directions-run-icon-sk': HTMLElement;
    'directions-subway-icon-sk': HTMLElement;
    'directions-transit-icon-sk': HTMLElement;
    'directions-walk-icon-sk': HTMLElement;
    'disc-full-icon-sk': HTMLElement;
    'dns-icon-sk': HTMLElement;
    'dock-icon-sk': HTMLElement;
    'domain-icon-sk': HTMLElement;
    'done-all-icon-sk': HTMLElement;
    'done-icon-sk': HTMLElement;
    'do-not-disturb-alt-icon-sk': HTMLElement;
    'do-not-disturb-icon-sk': HTMLElement;
    'do-not-disturb-off-icon-sk': HTMLElement;
    'do-not-disturb-on-icon-sk': HTMLElement;
    'donut-large-icon-sk': HTMLElement;
    'donut-small-icon-sk': HTMLElement;
    'drafts-icon-sk': HTMLElement;
    'drag-handle-icon-sk': HTMLElement;
    'drive-eta-icon-sk': HTMLElement;
    'dvr-icon-sk': HTMLElement;
    'edit-icon-sk': HTMLElement;
    'edit-location-icon-sk': HTMLElement;
    'eject-icon-sk': HTMLElement;
    'email-icon-sk': HTMLElement;
    'enhanced-encryption-icon-sk': HTMLElement;
    'equalizer-icon-sk': HTMLElement;
    'error-icon-sk': HTMLElement;
    'error-outline-icon-sk': HTMLElement;
    'euro-symbol-icon-sk': HTMLElement;
    'event-available-icon-sk': HTMLElement;
    'event-busy-icon-sk': HTMLElement;
    'event-icon-sk': HTMLElement;
    'event-note-icon-sk': HTMLElement;
    'event-seat-icon-sk': HTMLElement;
    'ev-station-icon-sk': HTMLElement;
    'exit-to-app-icon-sk': HTMLElement;
    'expand-less-icon-sk': HTMLElement;
    'expand-more-icon-sk': HTMLElement;
    'explicit-icon-sk': HTMLElement;
    'explore-icon-sk': HTMLElement;
    'exposure-icon-sk': HTMLElement;
    'exposure-neg-1-icon-sk': HTMLElement;
    'exposure-neg-2-icon-sk': HTMLElement;
    'exposure-plus-1-icon-sk': HTMLElement;
    'exposure-plus-2-icon-sk': HTMLElement;
    'exposure-zero-icon-sk': HTMLElement;
    'extension-icon-sk': HTMLElement;
    'face-icon-sk': HTMLElement;
    'fast-forward-icon-sk': HTMLElement;
    'fast-rewind-icon-sk': HTMLElement;
    'favorite-border-icon-sk': HTMLElement;
    'favorite-icon-sk': HTMLElement;
    'featured-play-list-icon-sk': HTMLElement;
    'featured-video-icon-sk': HTMLElement;
    'feedback-icon-sk': HTMLElement;
    'fiber-dvr-icon-sk': HTMLElement;
    'fiber-manual-record-icon-sk': HTMLElement;
    'fiber-new-icon-sk': HTMLElement;
    'fiber-pin-icon-sk': HTMLElement;
    'fiber-smart-record-icon-sk': HTMLElement;
    'file-download-icon-sk': HTMLElement;
    'file-upload-icon-sk': HTMLElement;
    'filter-1-icon-sk': HTMLElement;
    'filter-2-icon-sk': HTMLElement;
    'filter-3-icon-sk': HTMLElement;
    'filter-4-icon-sk': HTMLElement;
    'filter-5-icon-sk': HTMLElement;
    'filter-6-icon-sk': HTMLElement;
    'filter-7-icon-sk': HTMLElement;
    'filter-8-icon-sk': HTMLElement;
    'filter-9-icon-sk': HTMLElement;
    'filter-9-plus-icon-sk': HTMLElement;
    'filter-b-and-w-icon-sk': HTMLElement;
    'filter-center-focus-icon-sk': HTMLElement;
    'filter-drama-icon-sk': HTMLElement;
    'filter-frames-icon-sk': HTMLElement;
    'filter-hdr-icon-sk': HTMLElement;
    'filter-icon-sk': HTMLElement;
    'filter-list-icon-sk': HTMLElement;
    'filter-none-icon-sk': HTMLElement;
    'filter-tilt-shift-icon-sk': HTMLElement;
    'filter-vintage-icon-sk': HTMLElement;
    'find-in-page-icon-sk': HTMLElement;
    'find-replace-icon-sk': HTMLElement;
    'fingerprint-icon-sk': HTMLElement;
    'first-page-icon-sk': HTMLElement;
    'fitness-center-icon-sk': HTMLElement;
    'flag-icon-sk': HTMLElement;
    'flare-icon-sk': HTMLElement;
    'flash-auto-icon-sk': HTMLElement;
    'flash-off-icon-sk': HTMLElement;
    'flash-on-icon-sk': HTMLElement;
    'flight-icon-sk': HTMLElement;
    'flight-land-icon-sk': HTMLElement;
    'flight-takeoff-icon-sk': HTMLElement;
    'flip-icon-sk': HTMLElement;
    'flip-to-back-icon-sk': HTMLElement;
    'flip-to-front-icon-sk': HTMLElement;
    'folder-icon-sk': HTMLElement;
    'folder-open-icon-sk': HTMLElement;
    'folder-shared-icon-sk': HTMLElement;
    'folder-special-icon-sk': HTMLElement;
    'font-download-icon-sk': HTMLElement;
    'format-align-center-icon-sk': HTMLElement;
    'format-align-justify-icon-sk': HTMLElement;
    'format-align-left-icon-sk': HTMLElement;
    'format-align-right-icon-sk': HTMLElement;
    'format-bold-icon-sk': HTMLElement;
    'format-clear-icon-sk': HTMLElement;
    'format-color-fill-icon-sk': HTMLElement;
    'format-color-reset-icon-sk': HTMLElement;
    'format-color-text-icon-sk': HTMLElement;
    'format-indent-decrease-icon-sk': HTMLElement;
    'format-indent-increase-icon-sk': HTMLElement;
    'format-italic-icon-sk': HTMLElement;
    'format-line-spacing-icon-sk': HTMLElement;
    'format-list-bulleted-icon-sk': HTMLElement;
    'format-list-numbered-icon-sk': HTMLElement;
    'format-paint-icon-sk': HTMLElement;
    'format-quote-icon-sk': HTMLElement;
    'format-shapes-icon-sk': HTMLElement;
    'format-size-icon-sk': HTMLElement;
    'format-strikethrough-icon-sk': HTMLElement;
    'format-textdirection-l-to-r-icon-sk': HTMLElement;
    'format-textdirection-r-to-l-icon-sk': HTMLElement;
    'format-underlined-icon-sk': HTMLElement;
    'forum-icon-sk': HTMLElement;
    'forward-10-icon-sk': HTMLElement;
    'forward-30-icon-sk': HTMLElement;
    'forward-5-icon-sk': HTMLElement;
    'forward-icon-sk': HTMLElement;
    'free-breakfast-icon-sk': HTMLElement;
    'fullscreen-exit-icon-sk': HTMLElement;
    'fullscreen-icon-sk': HTMLElement;
    'functions-icon-sk': HTMLElement;
    'gamepad-icon-sk': HTMLElement;
    'games-icon-sk': HTMLElement;
    'gavel-icon-sk': HTMLElement;
    'gesture-icon-sk': HTMLElement;
    'get-app-icon-sk': HTMLElement;
    'gif-icon-sk': HTMLElement;
    'golf-course-icon-sk': HTMLElement;
    'gps-fixed-icon-sk': HTMLElement;
    'gps-not-fixed-icon-sk': HTMLElement;
    'gps-off-icon-sk': HTMLElement;
    'grade-icon-sk': HTMLElement;
    'gradient-icon-sk': HTMLElement;
    'grain-icon-sk': HTMLElement;
    'graphic-eq-icon-sk': HTMLElement;
    'grid-off-icon-sk': HTMLElement;
    'grid-on-icon-sk': HTMLElement;
    'group-add-icon-sk': HTMLElement;
    'group-icon-sk': HTMLElement;
    'group-work-icon-sk': HTMLElement;
    'g-translate-icon-sk': HTMLElement;
    'hd-icon-sk': HTMLElement;
    'hdr-off-icon-sk': HTMLElement;
    'hdr-on-icon-sk': HTMLElement;
    'hdr-strong-icon-sk': HTMLElement;
    'hdr-weak-icon-sk': HTMLElement;
    'headset-icon-sk': HTMLElement;
    'headset-mic-icon-sk': HTMLElement;
    'healing-icon-sk': HTMLElement;
    'hearing-icon-sk': HTMLElement;
    'help-icon-sk': HTMLElement;
    'help-outline-icon-sk': HTMLElement;
    'highlight-icon-sk': HTMLElement;
    'highlight-off-icon-sk': HTMLElement;
    'high-quality-icon-sk': HTMLElement;
    'history-icon-sk': HTMLElement;
    'home-icon-sk': HTMLElement;
    'hotel-icon-sk': HTMLElement;
    'hot-tub-icon-sk': HTMLElement;
    'hourglass-empty-icon-sk': HTMLElement;
    'hourglass-full-icon-sk': HTMLElement;
    'http-icon-sk': HTMLElement;
    'https-icon-sk': HTMLElement;
    'image-aspect-ratio-icon-sk': HTMLElement;
    'image-icon-sk': HTMLElement;
    'important-devices-icon-sk': HTMLElement;
    'import-contacts-icon-sk': HTMLElement;
    'import-export-icon-sk': HTMLElement;
    'inbox-icon-sk': HTMLElement;
    'indeterminate-check-box-icon-sk': HTMLElement;
    'info-icon-sk': HTMLElement;
    'info-outline-icon-sk': HTMLElement;
    'input-icon-sk': HTMLElement;
    'insert-chart-icon-sk': HTMLElement;
    'insert-comment-icon-sk': HTMLElement;
    'insert-drive-file-icon-sk': HTMLElement;
    'insert-emoticon-icon-sk': HTMLElement;
    'insert-invitation-icon-sk': HTMLElement;
    'insert-link-icon-sk': HTMLElement;
    'insert-photo-icon-sk': HTMLElement;
    'invert-colors-icon-sk': HTMLElement;
    'invert-colors-off-icon-sk': HTMLElement;
    'iso-icon-sk': HTMLElement;
    'keyboard-arrow-down-icon-sk': HTMLElement;
    'keyboard-arrow-left-icon-sk': HTMLElement;
    'keyboard-arrow-right-icon-sk': HTMLElement;
    'keyboard-arrow-up-icon-sk': HTMLElement;
    'keyboard-backspace-icon-sk': HTMLElement;
    'keyboard-capslock-icon-sk': HTMLElement;
    'keyboard-hide-icon-sk': HTMLElement;
    'keyboard-icon-sk': HTMLElement;
    'keyboard-return-icon-sk': HTMLElement;
    'keyboard-tab-icon-sk': HTMLElement;
    'keyboard-voice-icon-sk': HTMLElement;
    'kitchen-icon-sk': HTMLElement;
    'label-icon-sk': HTMLElement;
    'label-outline-icon-sk': HTMLElement;
    'landscape-icon-sk': HTMLElement;
    'language-icon-sk': HTMLElement;
    'laptop-chromebook-icon-sk': HTMLElement;
    'laptop-icon-sk': HTMLElement;
    'laptop-mac-icon-sk': HTMLElement;
    'laptop-windows-icon-sk': HTMLElement;
    'last-page-icon-sk': HTMLElement;
    'launch-icon-sk': HTMLElement;
    'layers-clear-icon-sk': HTMLElement;
    'layers-icon-sk': HTMLElement;
    'leak-add-icon-sk': HTMLElement;
    'leak-remove-icon-sk': HTMLElement;
    'lens-icon-sk': HTMLElement;
    'library-add-icon-sk': HTMLElement;
    'library-books-icon-sk': HTMLElement;
    'library-music-icon-sk': HTMLElement;
    'lightbulb-outline-icon-sk': HTMLElement;
    'linear-scale-icon-sk': HTMLElement;
    'line-style-icon-sk': HTMLElement;
    'line-weight-icon-sk': HTMLElement;
    'linked-camera-icon-sk': HTMLElement;
    'link-icon-sk': HTMLElement;
    'list-icon-sk': HTMLElement;
    'live-help-icon-sk': HTMLElement;
    'live-tv-icon-sk': HTMLElement;
    'local-activity-icon-sk': HTMLElement;
    'local-airport-icon-sk': HTMLElement;
    'local-atm-icon-sk': HTMLElement;
    'local-bar-icon-sk': HTMLElement;
    'local-cafe-icon-sk': HTMLElement;
    'local-car-wash-icon-sk': HTMLElement;
    'local-convenience-store-icon-sk': HTMLElement;
    'local-dining-icon-sk': HTMLElement;
    'local-drink-icon-sk': HTMLElement;
    'local-florist-icon-sk': HTMLElement;
    'local-gas-station-icon-sk': HTMLElement;
    'local-grocery-store-icon-sk': HTMLElement;
    'local-hospital-icon-sk': HTMLElement;
    'local-hotel-icon-sk': HTMLElement;
    'local-laundry-service-icon-sk': HTMLElement;
    'local-library-icon-sk': HTMLElement;
    'local-mall-icon-sk': HTMLElement;
    'local-movies-icon-sk': HTMLElement;
    'local-offer-icon-sk': HTMLElement;
    'local-parking-icon-sk': HTMLElement;
    'local-pharmacy-icon-sk': HTMLElement;
    'local-phone-icon-sk': HTMLElement;
    'local-pizza-icon-sk': HTMLElement;
    'local-play-icon-sk': HTMLElement;
    'local-post-office-icon-sk': HTMLElement;
    'local-printshop-icon-sk': HTMLElement;
    'local-see-icon-sk': HTMLElement;
    'local-shipping-icon-sk': HTMLElement;
    'local-taxi-icon-sk': HTMLElement;
    'location-city-icon-sk': HTMLElement;
    'location-disabled-icon-sk': HTMLElement;
    'location-off-icon-sk': HTMLElement;
    'location-on-icon-sk': HTMLElement;
    'location-searching-icon-sk': HTMLElement;
    'lock-icon-sk': HTMLElement;
    'lock-open-icon-sk': HTMLElement;
    'lock-outline-icon-sk': HTMLElement;
    'looks-3-icon-sk': HTMLElement;
    'looks-4-icon-sk': HTMLElement;
    'looks-5-icon-sk': HTMLElement;
    'looks-6-icon-sk': HTMLElement;
    'looks-icon-sk': HTMLElement;
    'looks-one-icon-sk': HTMLElement;
    'looks-two-icon-sk': HTMLElement;
    'loop-icon-sk': HTMLElement;
    'loupe-icon-sk': HTMLElement;
    'low-priority-icon-sk': HTMLElement;
    'loyalty-icon-sk': HTMLElement;
    'mail-icon-sk': HTMLElement;
    'mail-outline-icon-sk': HTMLElement;
    'map-icon-sk': HTMLElement;
    'markunread-icon-sk': HTMLElement;
    'markunread-mailbox-icon-sk': HTMLElement;
    'memory-icon-sk': HTMLElement;
    'menu-icon-sk': HTMLElement;
    'merge-type-icon-sk': HTMLElement;
    'message-icon-sk': HTMLElement;
    'mic-icon-sk': HTMLElement;
    'mic-none-icon-sk': HTMLElement;
    'mic-off-icon-sk': HTMLElement;
    'mms-icon-sk': HTMLElement;
    'mode-comment-icon-sk': HTMLElement;
    'mode-edit-icon-sk': HTMLElement;
    'monetization-on-icon-sk': HTMLElement;
    'money-off-icon-sk': HTMLElement;
    'monochrome-photos-icon-sk': HTMLElement;
    'mood-bad-icon-sk': HTMLElement;
    'mood-icon-sk': HTMLElement;
    'more-horiz-icon-sk': HTMLElement;
    'more-icon-sk': HTMLElement;
    'more-vert-icon-sk': HTMLElement;
    'motorcycle-icon-sk': HTMLElement;
    'mouse-icon-sk': HTMLElement;
    'move-to-inbox-icon-sk': HTMLElement;
    'movie-creation-icon-sk': HTMLElement;
    'movie-filter-icon-sk': HTMLElement;
    'movie-icon-sk': HTMLElement;
    'multiline-chart-icon-sk': HTMLElement;
    'music-note-icon-sk': HTMLElement;
    'music-video-icon-sk': HTMLElement;
    'my-element': HTMLElement;
    'my-location-icon-sk': HTMLElement;
    'nature-icon-sk': HTMLElement;
    'nature-people-icon-sk': HTMLElement;
    'navigate-before-icon-sk': HTMLElement;
    'navigate-next-icon-sk': HTMLElement;
    'navigation-icon-sk': HTMLElement;
    'near-me-icon-sk': HTMLElement;
    'network-cell-icon-sk': HTMLElement;
    'network-check-icon-sk': HTMLElement;
    'network-locked-icon-sk': HTMLElement;
    'network-wifi-icon-sk': HTMLElement;
    'new-releases-icon-sk': HTMLElement;
    'next-week-icon-sk': HTMLElement;
    'nfc-icon-sk': HTMLElement;
    'no-encryption-icon-sk': HTMLElement;
    'no-sim-icon-sk': HTMLElement;
    'note-add-icon-sk': HTMLElement;
    'note-icon-sk': HTMLElement;
    'notifications-active-icon-sk': HTMLElement;
    'notifications-icon-sk': HTMLElement;
    'notifications-none-icon-sk': HTMLElement;
    'notifications-off-icon-sk': HTMLElement;
    'notifications-paused-icon-sk': HTMLElement;
    'not-interested-icon-sk': HTMLElement;
    'offline-pin-icon-sk': HTMLElement;
    'ondemand-video-icon-sk': HTMLElement;
    'opacity-icon-sk': HTMLElement;
    'open-in-browser-icon-sk': HTMLElement;
    'open-in-new-icon-sk': HTMLElement;
    'open-with-icon-sk': HTMLElement;
    'pages-icon-sk': HTMLElement;
    'pageview-icon-sk': HTMLElement;
    'palette-icon-sk': HTMLElement;
    'panorama-fish-eye-icon-sk': HTMLElement;
    'panorama-horizontal-icon-sk': HTMLElement;
    'panorama-icon-sk': HTMLElement;
    'panorama-vertical-icon-sk': HTMLElement;
    'panorama-wide-angle-icon-sk': HTMLElement;
    'pan-tool-icon-sk': HTMLElement;
    'party-mode-icon-sk': HTMLElement;
    'pause-circle-filled-icon-sk': HTMLElement;
    'pause-circle-outline-icon-sk': HTMLElement;
    'pause-icon-sk': HTMLElement;
    'payment-icon-sk': HTMLElement;
    'people-icon-sk': HTMLElement;
    'people-outline-icon-sk': HTMLElement;
    'perm-camera-mic-icon-sk': HTMLElement;
    'perm-contact-calendar-icon-sk': HTMLElement;
    'perm-data-setting-icon-sk': HTMLElement;
    'perm-device-information-icon-sk': HTMLElement;
    'perm-identity-icon-sk': HTMLElement;
    'perm-media-icon-sk': HTMLElement;
    'perm-phone-msg-icon-sk': HTMLElement;
    'perm-scan-wifi-icon-sk': HTMLElement;
    'person-add-icon-sk': HTMLElement;
    'personal-video-icon-sk': HTMLElement;
    'person-icon-sk': HTMLElement;
    'person-outline-icon-sk': HTMLElement;
    'person-pin-circle-icon-sk': HTMLElement;
    'person-pin-icon-sk': HTMLElement;
    'pets-icon-sk': HTMLElement;
    'phone-android-icon-sk': HTMLElement;
    'phone-bluetooth-speaker-icon-sk': HTMLElement;
    'phone-forwarded-icon-sk': HTMLElement;
    'phone-icon-sk': HTMLElement;
    'phone-in-talk-icon-sk': HTMLElement;
    'phone-iphone-icon-sk': HTMLElement;
    'phonelink-erase-icon-sk': HTMLElement;
    'phonelink-icon-sk': HTMLElement;
    'phonelink-lock-icon-sk': HTMLElement;
    'phonelink-off-icon-sk': HTMLElement;
    'phonelink-ring-icon-sk': HTMLElement;
    'phonelink-setup-icon-sk': HTMLElement;
    'phone-locked-icon-sk': HTMLElement;
    'phone-missed-icon-sk': HTMLElement;
    'phone-paused-icon-sk': HTMLElement;
    'photo-album-icon-sk': HTMLElement;
    'photo-camera-icon-sk': HTMLElement;
    'photo-filter-icon-sk': HTMLElement;
    'photo-icon-sk': HTMLElement;
    'photo-library-icon-sk': HTMLElement;
    'photo-size-select-actual-icon-sk': HTMLElement;
    'photo-size-select-large-icon-sk': HTMLElement;
    'photo-size-select-small-icon-sk': HTMLElement;
    'picture-as-pdf-icon-sk': HTMLElement;
    'picture-in-picture-alt-icon-sk': HTMLElement;
    'picture-in-picture-icon-sk': HTMLElement;
    'pie-chart-icon-sk': HTMLElement;
    'pie-chart-outlined-icon-sk': HTMLElement;
    'pin-drop-icon-sk': HTMLElement;
    'place-icon-sk': HTMLElement;
    'play-arrow-icon-sk': HTMLElement;
    'play-circle-filled-icon-sk': HTMLElement;
    'play-circle-outline-icon-sk': HTMLElement;
    'play-for-work-icon-sk': HTMLElement;
    'playlist-add-check-icon-sk': HTMLElement;
    'playlist-add-icon-sk': HTMLElement;
    'playlist-play-icon-sk': HTMLElement;
    'plus-one-icon-sk': HTMLElement;
    'poll-icon-sk': HTMLElement;
    'polymer-icon-sk': HTMLElement;
    'pool-icon-sk': HTMLElement;
    'portable-wifi-off-icon-sk': HTMLElement;
    'portrait-icon-sk': HTMLElement;
    'power-icon-sk': HTMLElement;
    'power-input-icon-sk': HTMLElement;
    'power-settings-new-icon-sk': HTMLElement;
    'pregnant-woman-icon-sk': HTMLElement;
    'present-to-all-icon-sk': HTMLElement;
    'print-icon-sk': HTMLElement;
    'priority-high-icon-sk': HTMLElement;
    'public-icon-sk': HTMLElement;
    'publish-icon-sk': HTMLElement;
    'query-builder-icon-sk': HTMLElement;
    'question-answer-icon-sk': HTMLElement;
    'queue-icon-sk': HTMLElement;
    'queue-music-icon-sk': HTMLElement;
    'queue-play-next-icon-sk': HTMLElement;
    'radio-button-checked-icon-sk': HTMLElement;
    'radio-button-unchecked-icon-sk': HTMLElement;
    'radio-icon-sk': HTMLElement;
    'rate-review-icon-sk': HTMLElement;
    'receipt-icon-sk': HTMLElement;
    'recent-actors-icon-sk': HTMLElement;
    'record-voice-over-icon-sk': HTMLElement;
    'redeem-icon-sk': HTMLElement;
    'redo-icon-sk': HTMLElement;
    'refresh-icon-sk': HTMLElement;
    'remove-circle-icon-sk': HTMLElement;
    'remove-circle-outline-icon-sk': HTMLElement;
    'remove-from-queue-icon-sk': HTMLElement;
    'remove-icon-sk': HTMLElement;
    'remove-red-eye-icon-sk': HTMLElement;
    'remove-shopping-cart-icon-sk': HTMLElement;
    'reorder-icon-sk': HTMLElement;
    'repeat-icon-sk': HTMLElement;
    'repeat-one-icon-sk': HTMLElement;
    'replay-10-icon-sk': HTMLElement;
    'replay-30-icon-sk': HTMLElement;
    'replay-5-icon-sk': HTMLElement;
    'replay-icon-sk': HTMLElement;
    'reply-all-icon-sk': HTMLElement;
    'reply-icon-sk': HTMLElement;
    'report-icon-sk': HTMLElement;
    'report-problem-icon-sk': HTMLElement;
    'restaurant-icon-sk': HTMLElement;
    'restaurant-menu-icon-sk': HTMLElement;
    'restore-icon-sk': HTMLElement;
    'restore-page-icon-sk': HTMLElement;
    'ring-volume-icon-sk': HTMLElement;
    'room-icon-sk': HTMLElement;
    'room-service-icon-sk': HTMLElement;
    'rotate-90-degrees-ccw-icon-sk': HTMLElement;
    'rotate-left-icon-sk': HTMLElement;
    'rotate-right-icon-sk': HTMLElement;
    'rounded-corner-icon-sk': HTMLElement;
    'router-icon-sk': HTMLElement;
    'rowing-icon-sk': HTMLElement;
    'rss-feed-icon-sk': HTMLElement;
    'rv-hookup-icon-sk': HTMLElement;
    'satellite-icon-sk': HTMLElement;
    'save-icon-sk': HTMLElement;
    'scanner-icon-sk': HTMLElement;
    'schedule-icon-sk': HTMLElement;
    'school-icon-sk': HTMLElement;
    'screen-lock-landscape-icon-sk': HTMLElement;
    'screen-lock-portrait-icon-sk': HTMLElement;
    'screen-lock-rotation-icon-sk': HTMLElement;
    'screen-rotation-icon-sk': HTMLElement;
    'screen-share-icon-sk': HTMLElement;
    'sd-card-icon-sk': HTMLElement;
    'sd-storage-icon-sk': HTMLElement;
    'search-icon-sk': HTMLElement;
    'security-icon-sk': HTMLElement;
    'select-all-icon-sk': HTMLElement;
    'send-icon-sk': HTMLElement;
    'sentiment-dissatisfied-icon-sk': HTMLElement;
    'sentiment-neutral-icon-sk': HTMLElement;
    'sentiment-satisfied-icon-sk': HTMLElement;
    'sentiment-very-dissatisfied-icon-sk': HTMLElement;
    'sentiment-very-satisfied-icon-sk': HTMLElement;
    'settings-applications-icon-sk': HTMLElement;
    'settings-backup-restore-icon-sk': HTMLElement;
    'settings-bluetooth-icon-sk': HTMLElement;
    'settings-brightness-icon-sk': HTMLElement;
    'settings-cell-icon-sk': HTMLElement;
    'settings-ethernet-icon-sk': HTMLElement;
    'settings-icon-sk': HTMLElement;
    'settings-input-antenna-icon-sk': HTMLElement;
    'settings-input-component-icon-sk': HTMLElement;
    'settings-input-composite-icon-sk': HTMLElement;
    'settings-input-hdmi-icon-sk': HTMLElement;
    'settings-input-svideo-icon-sk': HTMLElement;
    'settings-overscan-icon-sk': HTMLElement;
    'settings-phone-icon-sk': HTMLElement;
    'settings-power-icon-sk': HTMLElement;
    'settings-remote-icon-sk': HTMLElement;
    'settings-system-daydream-icon-sk': HTMLElement;
    'settings-voice-icon-sk': HTMLElement;
    'share-icon-sk': HTMLElement;
    'shop-icon-sk': HTMLElement;
    'shopping-basket-icon-sk': HTMLElement;
    'shopping-cart-icon-sk': HTMLElement;
    'shop-two-icon-sk': HTMLElement;
    'short-text-icon-sk': HTMLElement;
    'show-chart-icon-sk': HTMLElement;
    'shuffle-icon-sk': HTMLElement;
    'signal-cellular-0-bar-icon-sk': HTMLElement;
    'signal-cellular-1-bar-icon-sk': HTMLElement;
    'signal-cellular-2-bar-icon-sk': HTMLElement;
    'signal-cellular-3-bar-icon-sk': HTMLElement;
    'signal-cellular-4-bar-icon-sk': HTMLElement;
    'signal-cellular-connected-no-internet-0-bar-icon-sk': HTMLElement;
    'signal-cellular-connected-no-internet-1-bar-icon-sk': HTMLElement;
    'signal-cellular-connected-no-internet-2-bar-icon-sk': HTMLElement;
    'signal-cellular-connected-no-internet-3-bar-icon-sk': HTMLElement;
    'signal-cellular-connected-no-internet-4-bar-icon-sk': HTMLElement;
    'signal-cellular-no-sim-icon-sk': HTMLElement;
    'signal-cellular-null-icon-sk': HTMLElement;
    'signal-cellular-off-icon-sk': HTMLElement;
    'signal-wifi-0-bar-icon-sk': HTMLElement;
    'signal-wifi-1-bar-icon-sk': HTMLElement;
    'signal-wifi-1-bar-lock-icon-sk': HTMLElement;
    'signal-wifi-2-bar-icon-sk': HTMLElement;
    'signal-wifi-2-bar-lock-icon-sk': HTMLElement;
    'signal-wifi-3-bar-icon-sk': HTMLElement;
    'signal-wifi-3-bar-lock-icon-sk': HTMLElement;
    'signal-wifi-4-bar-icon-sk': HTMLElement;
    'signal-wifi-4-bar-lock-icon-sk': HTMLElement;
    'signal-wifi-off-icon-sk': HTMLElement;
    'sim-card-alert-icon-sk': HTMLElement;
    'sim-card-icon-sk': HTMLElement;
    'skip-next-icon-sk': HTMLElement;
    'skip-previous-icon-sk': HTMLElement;
    'slideshow-icon-sk': HTMLElement;
    'slow-motion-video-icon-sk': HTMLElement;
    'smartphone-icon-sk': HTMLElement;
    'smoke-free-icon-sk': HTMLElement;
    'smoking-rooms-icon-sk': HTMLElement;
    'sms-failed-icon-sk': HTMLElement;
    'sms-icon-sk': HTMLElement;
    'snooze-icon-sk': HTMLElement;
    'sort-by-alpha-icon-sk': HTMLElement;
    'sort-icon-sk': HTMLElement;
    'space-bar-icon-sk': HTMLElement;
    'spa-icon-sk': HTMLElement;
    'speaker-group-icon-sk': HTMLElement;
    'speaker-icon-sk': HTMLElement;
    'speaker-notes-icon-sk': HTMLElement;
    'speaker-notes-off-icon-sk': HTMLElement;
    'speaker-phone-icon-sk': HTMLElement;
    'spellcheck-icon-sk': HTMLElement;
    'star-border-icon-sk': HTMLElement;
    'star-half-icon-sk': HTMLElement;
    'star-icon-sk': HTMLElement;
    'stars-icon-sk': HTMLElement;
    'stay-current-landscape-icon-sk': HTMLElement;
    'stay-current-portrait-icon-sk': HTMLElement;
    'stay-primary-landscape-icon-sk': HTMLElement;
    'stay-primary-portrait-icon-sk': HTMLElement;
    'stop-icon-sk': HTMLElement;
    'stop-screen-share-icon-sk': HTMLElement;
    'storage-icon-sk': HTMLElement;
    'store-icon-sk': HTMLElement;
    'store-mall-directory-icon-sk': HTMLElement;
    'straighten-icon-sk': HTMLElement;
    'streetview-icon-sk': HTMLElement;
    'strikethrough-s-icon-sk': HTMLElement;
    'style-icon-sk': HTMLElement;
    'subdirectory-arrow-left-icon-sk': HTMLElement;
    'subdirectory-arrow-right-icon-sk': HTMLElement;
    'subject-icon-sk': HTMLElement;
    'subscriptions-icon-sk': HTMLElement;
    'subtitles-icon-sk': HTMLElement;
    'subway-icon-sk': HTMLElement;
    'supervisor-account-icon-sk': HTMLElement;
    'surround-sound-icon-sk': HTMLElement;
    'swap-calls-icon-sk': HTMLElement;
    'swap-horiz-icon-sk': HTMLElement;
    'swap-vertical-circle-icon-sk': HTMLElement;
    'swap-vert-icon-sk': HTMLElement;
    'switch-camera-icon-sk': HTMLElement;
    'switch-video-icon-sk': HTMLElement;
    'sync-disabled-icon-sk': HTMLElement;
    'sync-icon-sk': HTMLElement;
    'sync-problem-icon-sk': HTMLElement;
    'system-update-alt-icon-sk': HTMLElement;
    'system-update-icon-sk': HTMLElement;
    'tab-icon-sk': HTMLElement;
    'tablet-android-icon-sk': HTMLElement;
    'tablet-icon-sk': HTMLElement;
    'tablet-mac-icon-sk': HTMLElement;
    'tab-unselected-icon-sk': HTMLElement;
    'tag-faces-icon-sk': HTMLElement;
    'tap-and-play-icon-sk': HTMLElement;
    'terrain-icon-sk': HTMLElement;
    'text-fields-icon-sk': HTMLElement;
    'text-format-icon-sk': HTMLElement;
    'textsms-icon-sk': HTMLElement;
    'texture-icon-sk': HTMLElement;
    'theaters-icon-sk': HTMLElement;
    'three-d-rotation-icon-sk': HTMLElement;
    'thumb-down-icon-sk': HTMLElement;
    'thumbs-up-down-icon-sk': HTMLElement;
    'thumb-up-icon-sk': HTMLElement;
    'timelapse-icon-sk': HTMLElement;
    'timeline-icon-sk': HTMLElement;
    'timer-10-icon-sk': HTMLElement;
    'timer-3-icon-sk': HTMLElement;
    'timer-icon-sk': HTMLElement;
    'timer-off-icon-sk': HTMLElement;
    'time-to-leave-icon-sk': HTMLElement;
    'title-icon-sk': HTMLElement;
    'toc-icon-sk': HTMLElement;
    'today-icon-sk': HTMLElement;
    'toll-icon-sk': HTMLElement;
    'tonality-icon-sk': HTMLElement;
    'touch-app-icon-sk': HTMLElement;
    'toys-icon-sk': HTMLElement;
    'track-changes-icon-sk': HTMLElement;
    'traffic-icon-sk': HTMLElement;
    'train-icon-sk': HTMLElement;
    'tram-icon-sk': HTMLElement;
    'transfer-within-a-station-icon-sk': HTMLElement;
    'transform-icon-sk': HTMLElement;
    'translate-icon-sk': HTMLElement;
    'trending-down-icon-sk': HTMLElement;
    'trending-flat-icon-sk': HTMLElement;
    'trending-up-icon-sk': HTMLElement;
    'tune-icon-sk': HTMLElement;
    'turned-in-icon-sk': HTMLElement;
    'turned-in-not-icon-sk': HTMLElement;
    'tv-icon-sk': HTMLElement;
    'unarchive-icon-sk': HTMLElement;
    'undo-icon-sk': HTMLElement;
    'unfold-less-icon-sk': HTMLElement;
    'unfold-more-icon-sk': HTMLElement;
    'update-icon-sk': HTMLElement;
    'usb-icon-sk': HTMLElement;
    'verified-user-icon-sk': HTMLElement;
    'vertical-align-bottom-icon-sk': HTMLElement;
    'vertical-align-center-icon-sk': HTMLElement;
    'vertical-align-top-icon-sk': HTMLElement;
    'vibration-icon-sk': HTMLElement;
    'video-call-icon-sk': HTMLElement;
    'videocam-icon-sk': HTMLElement;
    'videocam-off-icon-sk': HTMLElement;
    'videogame-asset-icon-sk': HTMLElement;
    'video-label-icon-sk': HTMLElement;
    'video-library-icon-sk': HTMLElement;
    'view-agenda-icon-sk': HTMLElement;
    'view-array-icon-sk': HTMLElement;
    'view-carousel-icon-sk': HTMLElement;
    'view-column-icon-sk': HTMLElement;
    'view-comfy-icon-sk': HTMLElement;
    'view-compact-icon-sk': HTMLElement;
    'view-day-icon-sk': HTMLElement;
    'view-headline-icon-sk': HTMLElement;
    'view-list-icon-sk': HTMLElement;
    'view-module-icon-sk': HTMLElement;
    'view-quilt-icon-sk': HTMLElement;
    'view-stream-icon-sk': HTMLElement;
    'view-week-icon-sk': HTMLElement;
    'vignette-icon-sk': HTMLElement;
    'visibility-icon-sk': HTMLElement;
    'visibility-off-icon-sk': HTMLElement;
    'voice-chat-icon-sk': HTMLElement;
    'voicemail-icon-sk': HTMLElement;
    'volume-down-icon-sk': HTMLElement;
    'volume-mute-icon-sk': HTMLElement;
    'volume-off-icon-sk': HTMLElement;
    'volume-up-icon-sk': HTMLElement;
    'vpn-key-icon-sk': HTMLElement;
    'vpn-lock-icon-sk': HTMLElement;
    'wallpaper-icon-sk': HTMLElement;
    'warning-icon-sk': HTMLElement;
    'watch-icon-sk': HTMLElement;
    'watch-later-icon-sk': HTMLElement;
    'wb-auto-icon-sk': HTMLElement;
    'wb-cloudy-icon-sk': HTMLElement;
    'wb-incandescent-icon-sk': HTMLElement;
    'wb-iridescent-icon-sk': HTMLElement;
    'wb-sunny-icon-sk': HTMLElement;
    'wc-icon-sk': HTMLElement;
    'web-asset-icon-sk': HTMLElement;
    'web-icon-sk': HTMLElement;
    'weekend-icon-sk': HTMLElement;
    'whatshot-icon-sk': HTMLElement;
    'widgets-icon-sk': HTMLElement;
    'wifi-icon-sk': HTMLElement;
    'wifi-lock-icon-sk': HTMLElement;
    'wifi-tethering-icon-sk': HTMLElement;
    'work-icon-sk': HTMLElement;
    'wrap-text-icon-sk': HTMLElement;
    'youtube-searched-for-icon-sk': HTMLElement;
    'zoom-in-icon-sk': HTMLElement;
    'zoom-out-icon-sk': HTMLElement;
    'zoom-out-map-icon-sk': HTMLElement;
    // Remaining components define custom classes.
    'admin-task-runs-sk': AdminTaskRunsSk;
    'admin-tasks-sk': AdminTasksSk;
    'alert-config-sk': AlertConfigSk;
    'alert-manager-sk': AlertManagerSk;
    'algo-select-sk': AlgoSelectSk;
    'alogin-sk': AloginSk;
    'android-layers-sk': AndroidLayersSk;
    'anomalies-table-sk': AnomaliesTableSk;
    'app-sk': AppSk;
    'arb-config-sk': ARBConfigSk;
    'arb-mode-history-sk': ARBModeHistorySk;
    'arb-roll-history-sk': ARBRollHistorySk;
    'arb-scaffold-sk': ARBScaffoldSk;
    'arb-status-sk': ARBStatusSk;
    'arb-strategy-history-sk': ARBStrategyHistorySk;
    'arb-table-sk': ARBTableSk;
    'auto-assign-sk': AutoAssignSk;
    'auto-refresh-sk': AutoRefreshSk;
    'autogrow-textarea-sk': AutogrowTextareaSk;
    'autoroller-status-sk': AutorollerStatusSk;
    'binary-diff-page-sk': BinaryDiffPageSk;
    'binary-page-sk': BinaryPageSk;
    'bisect-dialog-sk': BisectDialogSk;
    'blamelist-panel-sk': BlamelistPanelSk;
    'bot-chooser-sk': BotChooserSk;
    'branches-sk': BranchesSk;
    'bugs-central-scaffold-sk': BugsCentralScaffoldSk;
    'bugs-central-sk': BugsCentralSk;
    'bugs-chart-sk': BugsChartSk;
    'bugs-slo-popup-sk': BugsSLOPopupSk;
    'bugs-status-sk': BugsStatusSk;
    'bug-tooltip-sk': BugTooltipSk;
    'bulk-triage-sk': BulkTriageSk;
    'byblame-page-sk': ByBlamePageSk;
    'byblameentry-sk': ByBlameEntrySk;
    'calendar-input-sk': CalendarInputSk;
    'calendar-sk': CalendarSk;
    'capacity-sk': CapacitySk;
    'changelist-controls-sk': ChangelistControlsSk;
    'changelists-page-sk': ChangelistsPageSk;
    'chart-tooltip-sk': ChartTooltipSk;
    'checkbox-sk': CheckOrRadio;
    'chromium-analysis-runs-sk': ChromiumAnalysisRunsSk;
    'chromium-analysis-sk': ChromiumAnalysisSk;
    'chromium-perf-runs-sk': ChromiumPerfRunsSk;
    'chromium-perf-sk': ChromiumPerfSk;
    'clipboard-sk': ClipboardSk;
    'cluster-digests-sk': ClusterDigestsSk;
    'cluster-lastn-page-sk': ClusterLastNPageSk;
    'cluster-page-sk': ClusterPageSk;
    'cluster-summary2-sk': ClusterSummary2Sk;
    'codesize-scaffold-sk': CodesizeScaffoldSk;
    'collapse-sk': CollapseSk;
    'commands-sk': CommandsSk;
    'comments-sk': CommentsSk;
    'commit-detail-panel-sk': CommitDetailPanelSk;
    'commit-detail-picker-sk': CommitDetailPickerSk;
    'commit-detail-sk': CommitDetailSk;
    'commit-range-sk': CommitRangeSk;
    'commits-table-sk': CommitsTableSk;
    'confirm-dialog-sk': ConfirmDialogSk;
    'corpus-selector-sk': CorpusSelectorSk<any>;
    'ct-scaffold-sk': CtScaffoldSk;
    'cycler-button-sk': CyclerButtonSk;
    'day-range-sk': DayRangeSk;
    'debug-view-sk': DebugViewSk;
    'debugger-app-sk': DebuggerAppSk;
    'debugger-page-sk': DebuggerPageSk;
    'demo-list-sk': DemoListSk;
    'details-dialog-sk': DetailsDialogSk;
    'details-page-sk': DetailsPageSk;
    'device-editor-sk': DeviceEditorSk;
    'diff-page-sk': DiffPageSk;
    'digest-details-sk': DigestDetailsSk;
    'display-tree-status-sk': DisplayTreeStatusSk;
    'domain-picker-sk': DomainPickerSk;
    'dots-legend-sk': DotsLegendSk;
    'dots-sk': DotsSk;
    'edit-child-shader-sk': EditChildShaderSk;
    'edit-ignore-rule-sk': EditIgnoreRuleSk;
    'email-chooser-sk': EmailChooserSk;
    'enter-tree-status-sk': EnterTreeStatus;
    'error-toast-sk': ErrorToastSk;
    'example-control-sk': ExampleControlSk;
    'existing-bug-dialog-sk': ExistingBugDialogSk;
    'expandable-textarea-sk': ExpandableTextareaSk;
    'explore-multi-sk': ExploreMultiSk;
    'explore-simple-sk': ExploreSimpleSk;
    'explore-sk': ExploreSk;
    'favorites-dialog-sk': FavoritesDialogSk;
    'favorites-sk': FavoritesSk;
    'fiddle-embed-sk': FiddleEmbed;
    'fiddle-sk': FiddleSk;
    'filter-dialog-sk': FilterDialogSk;
    'gold-scaffold-sk': GoldScaffoldSk;
    'gold-status-sk': GoldStatusSk;
    'graph-title-sk': GraphTitleSk;
    'histogram-sk': HistogramSk;
    'human-date-sk': HumanDateSk;
    'ignores-page-sk': IgnoresPageSk;
    'image-compare-sk': ImageCompareSk;
    'incident-sk': IncidentSk;
    'index-page-sk': IndexPageSk;
    'input-sk': InputSk;
    'job-search-sk': JobSearchSk;
    'job-sk': JobSk;
    'job-timeline-sk': JobTimelineSk;
    'job-trigger-sk': JobTriggerSk;
    'json-source-sk': JSONSourceSk;
    'last-commit-sk': LastCommitSk;
    'leasing-list-sk': LeasingListSk;
    'leasing-scaffold-sk': LeasingScaffoldSk;
    'leasing-selections-sk': LeasingSelectionsSk;
    'leasing-task-sk': LeasingTaskSk;
    'list-autorollers-sk': ListAutorollersSk;
    'list-page-sk': ListPageSk;
    'machine-app-sk': MachineAppSk;
    'machine-table-columns-dialog-sk': MachineTableColumnsDialogSk;
    'machines-table-sk': MachinesTableSk;
    'metrics-analysis-runs-sk': MetricsAnalysisRunsSk;
    'metrics-analysis-sk': MetricsAnalysisSk;
    'multi-input-sk': MultiInputSk;
    'multi-select-sk': MultiSelectSk;
    'multi-zoom-sk': MultiZoomSk;
    'nav-button-sk': NavButtonSk;
    'nav-links-sk': NavLinksSk;
    'navigation-sk': NavigationSk;
    'new-bug-dialog-sk': NewBugDialogSk;
    'note-editor-sk': NoteEditorSk;
    'pageset-selector-sk': PagesetSelectorSk;
    'pagination-sk': PaginationSk;
    'paramset-sk': ParamSetSk;
    'patch-sk': PatchSk;
    'perf-scaffold-sk': PerfScaffoldSk;
    'perf-status-sk': PerfStatusSk;
    'picker-field-sk': PickerFieldSk;
    'pinpoint-try-job-dialog-sk': PinpointTryJobDialogSk;
    'pivot-query-sk': PivotQuerySk;
    'pivot-table-sk': PivotTableSk;
    'play-sk': PlaySk;
    'plot-google-chart-sk': PlotGoogleChartSk;
    'plot-simple-sk': PlotSimpleSk;
    'plot-summary-sk': PlotSummarySk;
    'point-links-sk': PointLinksSk;
    'processing-table-sk': ProcessingTableSk;
    'query-chooser-sk': QueryChooserSk;
    'query-count-sk': QueryCountSk;
    'query-dialog-sk': QueryDialogSk;
    'query-sk': QuerySk;
    'query-values-sk': QueryValuesSk;
    'radio-sk': RadioElement;
    'regressions-page-sk': RegressionsPageSk;
    'report-page-sk': ReportPageSk;
    'resources-sk': ResourcesSk;
    'revision-info-sk': RevisionInfoSk;
    'rotations-sk': RotationsSk;
    'runs-history-summary-sk': RunsHistorySummarySk;
    'scrap-exchange-sk': ScrapExchangeSk;
    'screenshots-viewer-sk': ScreenshotsViewerSk;
    'search-controls-sk': SearchControlsSk;
    'search-page-sk': SearchPageSk;
    'select-sk': SelectSk;
    'shaders-app-sk': ShadersAppSk;
    'silence-sk': SilenceSk;
    'skcq-scaffold-sk': SkCQScaffold;
    'skcq-sk': SkCQ;
    'skip-tasks-sk': SkipTasksSk;
    'skottie-audio-sk': SkottieAudioSk;
    'skottie-background-settings-sk': SkottieBackgroundSettingsSk;
    'skottie-button-sk': SkottieButtonSk;
    'skottie-color-input-sk': SkottieColorInputSk;
    'skottie-color-manager-sk': SkottieColorManagerSk;
    'skottie-compatibility-sk': SkottieCompatibilitySk;
    'skottie-config-sk': SkottieConfigSk;
    'skottie-drive-sk': SkottieDriveSk;
    'skottie-dropdown-sk': SkottieDropdownSk;
    'skottie-embed-sk': SkottieEmbedSk;
    'skottie-exporter-base-sk': SkottieExporterBaseSk;
    'skottie-exporter-gif-sk': SkottieExporterGifSk;
    'skottie-exporter-png-sk': SkottieExporterPNGSk;
    'skottie-exporter-sk': SkottieExporterSk;
    'skottie-exporter-webm-sk': SkottieExporterWebMSk;
    'skottie-file-form-sk': SkottieFileFormSk;
    'skottie-file-settings-sk': SkottieFileSettingsSk;
    'skottie-font-selector-sk': SkottieFontSelectorSk;
    'skottie-gif-exporter-sk': SkottieGifExporterSk;
    'skottie-inline-sk': SkottieInlineSk;
    'skottie-library-sk': SkottieLibrarySk;
    'skottie-performance-sk': SkottiePerformanceSk;
    'skottie-player-sk': SkottiePlayerSk;
    'skottie-shader-editor-sk': ShaderEditorSk;
    'skottie-sk': SkottieSk;
    'skottie-slot-manager-sk': SkottieSlotManagerSk;
    'skottie-text-editor-box-sk': SkottieTextEditorBoxSk;
    'skottie-text-editor-sk': SkottieTextEditorSk;
    'skottie-text-sampler-sk': SkottieTextSamplerSk;
    'skottie-vec2-input-sk': SkottieVec2InputSk;
    'sort-sk': SortSk;
    'sort-toggle-sk': SortToggleSk<any>;
    'spinner-sk': SpinnerSk;
    'split-chart-menu-sk': SplitChartMenuSk;
    'status-sk': StatusSk;
    'subscription-table-sk': SubscriptionTableSk;
    'suggest-input-sk': SuggestInputSk;
    'tabs-panel-sk': TabsPanelSk;
    'tabs-sk': TabsSk;
    'task-driver-sk': TaskDriverSk;
    'task-graph-sk': TaskGraphSk;
    'task-priority-sk': TaskPrioritySk;
    'task-queue-sk': TaskQueueSk;
    'task-repeater-sk': TaskRepeaterSk;
    'task-scheduler-scaffold-sk': TaskSchedulerScaffoldSk;
    'task-sk': TaskSk;
    'test-picker-sk': TestPickerSk;
    'test-src-sk': TestSrcSk;
    'textarea-numbers-sk': TextareaNumbersSk;
    'theme-chooser-sk': ThemeChooserSk;
    'timeline-sk': TimelineSk;
    'toast-sk': ToastSk;
    'tools-sk': ToolsSk;
    'tooltip-sk': TooltipSk;
    'trace-filter-sk': TraceFilterSk;
    'tree-scaffold-sk': TreeScaffoldSk;
    'tree-status-sk': TreeStatusSk;
    'triage-menu-sk': TriageMenuSk;
    'triage-page-sk': TriagePageSk;
    'triage-sk': TriageSk;
    'triage-status-sk': TriageStatusSk;
    'triage2-sk': TriageSk;
    'triagelog-page-sk': TriagelogPageSk;
    'tricon2-sk': TriconSk;
    'uniform-color-sk': UniformColorSk;
    'uniform-dimensions-sk': UniformDimensionsSk;
    'uniform-fps-sk': UniformFpsSk;
    'uniform-generic-sk': UniformGenericSk;
    'uniform-imageresolution-sk': UniformImageresolutionSk;
    'uniform-mouse-sk': UniformMouseSk;
    'uniform-slider-sk': UniformSliderSk;
    'uniform-time-sk': UniformTimeSk;
    'user-issue-sk': UserIssueSk;
    'verifiers-detail-sk': VerifiersDetailSk;
    'version-page-sk': VersionPageSk;
    'word-cloud-sk': WordCloudSk;
    'zoom-sk': ZoomSk;
  }
}
