- name: Make sure we have a 'sudo' group
  group:
    name: sudo
    state: present

- name: Allow 'sudo' group to have passwordless sudo
  become: true
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%sudo'
    line: '%sudo ALL=(ALL) NOPASSWD: ALL'
    validate: visudo -cf %s

- name: Add sudo users to sudo group
  become: true
  user:
    name: chrome-bot
    groups: sudo
    append: true

- name: Create chrome-bot user.
  become: true
  user:
    name: chrome-bot
    groups: plugdev,sudo
    generate_ssh_key: true
    ssh_key_type: ed25519
    shell: /bin/bash
    password: "{{ secrets.skolo_password | password_hash('sha256') }}"

# The environment monitor's sensor is a serial device, so add dialout group
# membership.
- name: Add serial port users to dialout group
  become: true
  when: install_environment_monitor__needs_environment_monitor is defined and install_environment_monitor__needs_environment_monitor == true
  user:
    name: chrome-bot
    group: chrome-bot
    groups: dialout
    append: true

# https://stackoverflow.com/a/64701430
- name: Boot into Gnome by default
  file:
    src: /usr/lib/systemd/system/graphical.target
    dest: /etc/systemd/system/default.target
    state: link

# For some reason, if we don't reboot GCE Linux machines after running the above task, subsequent
# SSH connections fail with "chrome-bot@<IP address>: Permission denied (publickey)".
#
# Note that this does not happen when this role is ran for the first time on a fresh GCE Linux
# machine. It only happens on subsequent runs of this role on the same machine (for example, when
# iterating on the linux.yml playbook).
#
# lovisolo@ has not checked whether Skolo Linux machines have this issue, but rebooting all
# machines, and not just GCE ones, seems like a harmless precaution.
- name: Reboot
  become: true
  reboot:
