apiVersion: v1
kind: Service
metadata:
  labels:
    app: metadata-server
  name: metadata-server
spec:
  ports:
    - name: metrics
      port: 20000
    - name: http
      port: 8000
  selector:
    name: metadata-server
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metadata-server
spec:
  selector:
    matchLabels:
      name: metadata-server
  template:
    metadata:
      labels:
        name: metadata-server
      annotations:
        prometheus.io.scrape: "true"
        prometheus.io.port: "20000"
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsUser: 2000 # aka skia
        fsGroup: 2000   # aka skia
      containers:
        - name: metadata-server
          image: gcr.io/skia-public/metadata-server:2019-06-04T17_45_44Z-jcgregorio-87cb907-dirty
          args:
            - "--logtostderr=true"
            - "--conf=/etc/metadata-server/metadata-rpi2.json5"
            - "--port=:8000"
            - "--prom_port=:20000"
          ports:
            - containerPort: 20000
            - containerPort: 8000
          volumeMounts:
            - name: skolo-service-account-secrets
              mountPath: /etc/service-accounts
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 1
            periodSeconds: 3
      volumes:
        - name: skolo-service-account-secrets
          secret:
            secretName: skolo-service-accounts
