apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: rpi-swarming-client
spec:
  selector:
    matchLabels:
      name: rpi-swarming-client
  template:
    metadata:
      labels:
        name: rpi-swarming-client
    spec:
      securityContext:
        fsGroup: 2000
      containers:
        - name: rpi-swarming-client
          image: gcr.io/skia-public/rpi-swarming-client:2019-06-13T13_42_23Z-jcgregorio-2fce14a-dirty
          securityContext:
            privileged: true
            capabilities:
              add:
                - ALL
          env:
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: REMOTE_BOT_CONFIG
              value: /etc/swarming/remote-bot-config/remote-bot-config.json
          volumeMounts:
          - mountPath: /b
            name: local-swarming-workingset
          - mountPath: /dev/ttyAMA0
            name: usb
          - mountPath: /dev/bus/usb
            name: usb2
          - mountPath: /home/chrome-bot/.android
            name: skolo-rpi-adb-key
          - mountPath: /etc/swarming/remote-bot-config/
            name: remote-bot-config
      volumes:
      - name: local-swarming-workingset
        hostPath:
          # directory location on host
          path: /var/swarming
          # this field is optional
          type: Directory
      - name: usb
        hostPath:
          path: /dev/ttyAMA0
      - name: usb2
        hostPath:
          path: /dev/bus/usb
      - name: skolo-rpi-adb-key
        secret:
          secretName: skolo-rpi-adb-key
      - name: remote-bot-config
        secret:
          secretName: remote-bot-config
