apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: rpi-swarming-client
spec:
  selector:
    matchLabels:
      name: rpi-swarming-client
  template:
    metadata:
      labels:
        name: rpi-swarming-client
    spec:
      containers:
        - name: rpi-swarming-client
          image: gcr.io/skia-public/rpi-swarming-client:2019-06-05T16_21_50Z-jcgregorio-a5e5904-dirty
          env:
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          securityContext:
            privileged: true
          volumeMounts:
          - mountPath: /b
            name: local-swarming-workingset
      volumes:
      - name: local-swarming-workingset
        hostPath:
          # directory location on host
          path: /var/swarming
          # this field is optional
          type: Directory
