# Once this is run then the 'rpi.yml' playbook can be run to finish/update the
# machine.
- hosts: fleet_rpis
  user: root
  gather_facts: false

  pre_tasks:
    # First install python3 so we can use more issue more than 'raw' commands.
    - name: install python3
      raw:
        'apt update && apt -y install sudo python3 python3-apt python3-distutils'

    # We can gather facts now that python3 is installed.
    # Needed for create_chrome_bot_user.
    - name: gather facts
      setup:

  roles:
    - set_root_password
    - create_chrome_bot_user
