- hosts: '{{ variable_hosts }}'
  user: root
  gather_facts: False
  tasks:
    - name:
        Copy skolo-bot-service-account@skia-public.iam.gserviceaccount.com
        service account key over.
      ansible.builtin.copy:
        src: /tmp/key.json
        dest: /home/chrome-bot/.config/gcloud/application_default_credentials.json
        owner: chrome-bot
        group: chrome-bot
        mode: '0644'
