// Code generated by protoc-gen-twirp v5.12.1, DO NOT EDIT.
// source: status.proto

/*
Package rpc is a generated twirp stub package.
This code was generated with github.com/twitchtv/twirp/protoc-gen-twirp v5.12.1.

It is generated from these files:
	status.proto
*/
package rpc

import (
	bytes "bytes"
	strings "strings"

	context "context"

	fmt "fmt"

	ioutil "io/ioutil"

	http "net/http"

	strconv "strconv"

	jsonpb "github.com/golang/protobuf/jsonpb"

	proto "github.com/golang/protobuf/proto"

	twirp "github.com/twitchtv/twirp"

	ctxsetters "github.com/twitchtv/twirp/ctxsetters"

	// Imports only used by utility functions:

	io "io"

	json "encoding/json"

	url "net/url"
)

// =======================
// StatusService Interface
// =======================

// API (non-page, non-resource) endpoints for Status.
type StatusService interface {
	// Method to get updates to the lists of recent commits, their tasks, etc.
	GetIncrementalCommits(context.Context, *GetIncrementalCommitsRequest) (*GetIncrementalCommitsResponse, error)

	// Method to add a comment to a task, commit, or task spec.
	AddComment(context.Context, *AddCommentRequest) (*AddCommentResponse, error)

	// Method to delete a comment to a task, commit, or task spec.
	DeleteComment(context.Context, *DeleteCommentRequest) (*DeleteCommentResponse, error)
}

// =============================
// StatusService Protobuf Client
// =============================

type statusServiceProtobufClient struct {
	client HTTPClient
	urls   [3]string
	opts   twirp.ClientOptions
}

// NewStatusServiceProtobufClient creates a Protobuf client that implements the StatusService interface.
// It communicates using Protobuf and can be configured with a custom HTTPClient.
func NewStatusServiceProtobufClient(addr string, client HTTPClient, opts ...twirp.ClientOption) StatusService {
	if c, ok := client.(*http.Client); ok {
		client = withoutRedirects(c)
	}

	clientOpts := twirp.ClientOptions{}
	for _, o := range opts {
		o(&clientOpts)
	}

	prefix := urlBase(addr) + StatusServicePathPrefix
	urls := [3]string{
		prefix + "GetIncrementalCommits",
		prefix + "AddComment",
		prefix + "DeleteComment",
	}

	return &statusServiceProtobufClient{
		client: client,
		urls:   urls,
		opts:   clientOpts,
	}
}

func (c *statusServiceProtobufClient) GetIncrementalCommits(ctx context.Context, in *GetIncrementalCommitsRequest) (*GetIncrementalCommitsResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "status")
	ctx = ctxsetters.WithServiceName(ctx, "StatusService")
	ctx = ctxsetters.WithMethodName(ctx, "GetIncrementalCommits")
	out := new(GetIncrementalCommitsResponse)
	ctx, err := doProtobufRequest(ctx, c.client, c.opts.Hooks, c.urls[0], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *statusServiceProtobufClient) AddComment(ctx context.Context, in *AddCommentRequest) (*AddCommentResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "status")
	ctx = ctxsetters.WithServiceName(ctx, "StatusService")
	ctx = ctxsetters.WithMethodName(ctx, "AddComment")
	out := new(AddCommentResponse)
	ctx, err := doProtobufRequest(ctx, c.client, c.opts.Hooks, c.urls[1], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *statusServiceProtobufClient) DeleteComment(ctx context.Context, in *DeleteCommentRequest) (*DeleteCommentResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "status")
	ctx = ctxsetters.WithServiceName(ctx, "StatusService")
	ctx = ctxsetters.WithMethodName(ctx, "DeleteComment")
	out := new(DeleteCommentResponse)
	ctx, err := doProtobufRequest(ctx, c.client, c.opts.Hooks, c.urls[2], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

// =========================
// StatusService JSON Client
// =========================

type statusServiceJSONClient struct {
	client HTTPClient
	urls   [3]string
	opts   twirp.ClientOptions
}

// NewStatusServiceJSONClient creates a JSON client that implements the StatusService interface.
// It communicates using JSON and can be configured with a custom HTTPClient.
func NewStatusServiceJSONClient(addr string, client HTTPClient, opts ...twirp.ClientOption) StatusService {
	if c, ok := client.(*http.Client); ok {
		client = withoutRedirects(c)
	}

	clientOpts := twirp.ClientOptions{}
	for _, o := range opts {
		o(&clientOpts)
	}

	prefix := urlBase(addr) + StatusServicePathPrefix
	urls := [3]string{
		prefix + "GetIncrementalCommits",
		prefix + "AddComment",
		prefix + "DeleteComment",
	}

	return &statusServiceJSONClient{
		client: client,
		urls:   urls,
		opts:   clientOpts,
	}
}

func (c *statusServiceJSONClient) GetIncrementalCommits(ctx context.Context, in *GetIncrementalCommitsRequest) (*GetIncrementalCommitsResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "status")
	ctx = ctxsetters.WithServiceName(ctx, "StatusService")
	ctx = ctxsetters.WithMethodName(ctx, "GetIncrementalCommits")
	out := new(GetIncrementalCommitsResponse)
	ctx, err := doJSONRequest(ctx, c.client, c.opts.Hooks, c.urls[0], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *statusServiceJSONClient) AddComment(ctx context.Context, in *AddCommentRequest) (*AddCommentResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "status")
	ctx = ctxsetters.WithServiceName(ctx, "StatusService")
	ctx = ctxsetters.WithMethodName(ctx, "AddComment")
	out := new(AddCommentResponse)
	ctx, err := doJSONRequest(ctx, c.client, c.opts.Hooks, c.urls[1], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *statusServiceJSONClient) DeleteComment(ctx context.Context, in *DeleteCommentRequest) (*DeleteCommentResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "status")
	ctx = ctxsetters.WithServiceName(ctx, "StatusService")
	ctx = ctxsetters.WithMethodName(ctx, "DeleteComment")
	out := new(DeleteCommentResponse)
	ctx, err := doJSONRequest(ctx, c.client, c.opts.Hooks, c.urls[2], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

// ============================
// StatusService Server Handler
// ============================

type statusServiceServer struct {
	StatusService
	hooks *twirp.ServerHooks
}

func NewStatusServiceServer(svc StatusService, hooks *twirp.ServerHooks) TwirpServer {
	return &statusServiceServer{
		StatusService: svc,
		hooks:         hooks,
	}
}

// writeError writes an HTTP response with a valid Twirp error format, and triggers hooks.
// If err is not a twirp.Error, it will get wrapped with twirp.InternalErrorWith(err)
func (s *statusServiceServer) writeError(ctx context.Context, resp http.ResponseWriter, err error) {
	writeError(ctx, resp, err, s.hooks)
}

// StatusServicePathPrefix is used for all URL paths on a twirp StatusService server.
// Requests are always: POST StatusServicePathPrefix/method
// It can be used in an HTTP mux to route twirp requests along with non-twirp requests on other routes.
const StatusServicePathPrefix = "/twirp/status.StatusService/"

func (s *statusServiceServer) ServeHTTP(resp http.ResponseWriter, req *http.Request) {
	ctx := req.Context()
	ctx = ctxsetters.WithPackageName(ctx, "status")
	ctx = ctxsetters.WithServiceName(ctx, "StatusService")
	ctx = ctxsetters.WithResponseWriter(ctx, resp)

	var err error
	ctx, err = callRequestReceived(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	if req.Method != "POST" {
		msg := fmt.Sprintf("unsupported method %q (only POST is allowed)", req.Method)
		err = badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, err)
		return
	}

	switch req.URL.Path {
	case "/twirp/status.StatusService/GetIncrementalCommits":
		s.serveGetIncrementalCommits(ctx, resp, req)
		return
	case "/twirp/status.StatusService/AddComment":
		s.serveAddComment(ctx, resp, req)
		return
	case "/twirp/status.StatusService/DeleteComment":
		s.serveDeleteComment(ctx, resp, req)
		return
	default:
		msg := fmt.Sprintf("no handler for path %q", req.URL.Path)
		err = badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, err)
		return
	}
}

func (s *statusServiceServer) serveGetIncrementalCommits(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveGetIncrementalCommitsJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveGetIncrementalCommitsProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *statusServiceServer) serveGetIncrementalCommitsJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "GetIncrementalCommits")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	reqContent := new(GetIncrementalCommitsRequest)
	unmarshaler := jsonpb.Unmarshaler{AllowUnknownFields: true}
	if err = unmarshaler.Unmarshal(req.Body, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the json request could not be decoded"))
		return
	}

	// Call service method
	var respContent *GetIncrementalCommitsResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = s.StatusService.GetIncrementalCommits(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *GetIncrementalCommitsResponse and nil error while calling GetIncrementalCommits. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	var buf bytes.Buffer
	marshaler := &jsonpb.Marshaler{OrigName: true}
	if err = marshaler.Marshal(&buf, respContent); err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal json response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	respBytes := buf.Bytes()
	resp.Header().Set("Content-Type", "application/json")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)

	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *statusServiceServer) serveGetIncrementalCommitsProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "GetIncrementalCommits")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := ioutil.ReadAll(req.Body)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to read request body"))
		return
	}
	reqContent := new(GetIncrementalCommitsRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the protobuf request could not be decoded"))
		return
	}

	// Call service method
	var respContent *GetIncrementalCommitsResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = s.StatusService.GetIncrementalCommits(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *GetIncrementalCommitsResponse and nil error while calling GetIncrementalCommits. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal proto response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *statusServiceServer) serveAddComment(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveAddCommentJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveAddCommentProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *statusServiceServer) serveAddCommentJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "AddComment")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	reqContent := new(AddCommentRequest)
	unmarshaler := jsonpb.Unmarshaler{AllowUnknownFields: true}
	if err = unmarshaler.Unmarshal(req.Body, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the json request could not be decoded"))
		return
	}

	// Call service method
	var respContent *AddCommentResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = s.StatusService.AddComment(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *AddCommentResponse and nil error while calling AddComment. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	var buf bytes.Buffer
	marshaler := &jsonpb.Marshaler{OrigName: true}
	if err = marshaler.Marshal(&buf, respContent); err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal json response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	respBytes := buf.Bytes()
	resp.Header().Set("Content-Type", "application/json")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)

	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *statusServiceServer) serveAddCommentProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "AddComment")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := ioutil.ReadAll(req.Body)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to read request body"))
		return
	}
	reqContent := new(AddCommentRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the protobuf request could not be decoded"))
		return
	}

	// Call service method
	var respContent *AddCommentResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = s.StatusService.AddComment(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *AddCommentResponse and nil error while calling AddComment. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal proto response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *statusServiceServer) serveDeleteComment(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveDeleteCommentJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveDeleteCommentProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *statusServiceServer) serveDeleteCommentJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "DeleteComment")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	reqContent := new(DeleteCommentRequest)
	unmarshaler := jsonpb.Unmarshaler{AllowUnknownFields: true}
	if err = unmarshaler.Unmarshal(req.Body, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the json request could not be decoded"))
		return
	}

	// Call service method
	var respContent *DeleteCommentResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = s.StatusService.DeleteComment(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *DeleteCommentResponse and nil error while calling DeleteComment. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	var buf bytes.Buffer
	marshaler := &jsonpb.Marshaler{OrigName: true}
	if err = marshaler.Marshal(&buf, respContent); err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal json response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	respBytes := buf.Bytes()
	resp.Header().Set("Content-Type", "application/json")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)

	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *statusServiceServer) serveDeleteCommentProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "DeleteComment")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := ioutil.ReadAll(req.Body)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to read request body"))
		return
	}
	reqContent := new(DeleteCommentRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the protobuf request could not be decoded"))
		return
	}

	// Call service method
	var respContent *DeleteCommentResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = s.StatusService.DeleteComment(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *DeleteCommentResponse and nil error while calling DeleteComment. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal proto response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *statusServiceServer) ServiceDescriptor() ([]byte, int) {
	return twirpFileDescriptor0, 0
}

func (s *statusServiceServer) ProtocGenTwirpVersion() string {
	return "v5.12.1"
}

func (s *statusServiceServer) PathPrefix() string {
	return StatusServicePathPrefix
}

// =====
// Utils
// =====

// HTTPClient is the interface used by generated clients to send HTTP requests.
// It is fulfilled by *(net/http).Client, which is sufficient for most users.
// Users can provide their own implementation for special retry policies.
//
// HTTPClient implementations should not follow redirects. Redirects are
// automatically disabled if *(net/http).Client is passed to client
// constructors. See the withoutRedirects function in this file for more
// details.
type HTTPClient interface {
	Do(req *http.Request) (*http.Response, error)
}

// TwirpServer is the interface generated server structs will support: they're
// HTTP handlers with additional methods for accessing metadata about the
// service. Those accessors are a low-level API for building reflection tools.
// Most people can think of TwirpServers as just http.Handlers.
type TwirpServer interface {
	http.Handler
	// ServiceDescriptor returns gzipped bytes describing the .proto file that
	// this service was generated from. Once unzipped, the bytes can be
	// unmarshalled as a
	// github.com/golang/protobuf/protoc-gen-go/descriptor.FileDescriptorProto.
	//
	// The returned integer is the index of this particular service within that
	// FileDescriptorProto's 'Service' slice of ServiceDescriptorProtos. This is a
	// low-level field, expected to be used for reflection.
	ServiceDescriptor() ([]byte, int)
	// ProtocGenTwirpVersion is the semantic version string of the version of
	// twirp used to generate this file.
	ProtocGenTwirpVersion() string
	// PathPrefix returns the HTTP URL path prefix for all methods handled by this
	// service. This can be used with an HTTP mux to route twirp requests
	// alongside non-twirp requests on one HTTP listener.
	PathPrefix() string
}

// WriteError writes an HTTP response with a valid Twirp error format (code, msg, meta).
// Useful outside of the Twirp server (e.g. http middleware), but does not trigger hooks.
// If err is not a twirp.Error, it will get wrapped with twirp.InternalErrorWith(err)
func WriteError(resp http.ResponseWriter, err error) {
	writeError(context.Background(), resp, err, nil)
}

// writeError writes Twirp errors in the response and triggers hooks.
func writeError(ctx context.Context, resp http.ResponseWriter, err error, hooks *twirp.ServerHooks) {
	// Non-twirp errors are wrapped as Internal (default)
	twerr, ok := err.(twirp.Error)
	if !ok {
		twerr = twirp.InternalErrorWith(err)
	}

	statusCode := twirp.ServerHTTPStatusFromErrorCode(twerr.Code())
	ctx = ctxsetters.WithStatusCode(ctx, statusCode)
	ctx = callError(ctx, hooks, twerr)

	respBody := marshalErrorToJSON(twerr)

	resp.Header().Set("Content-Type", "application/json") // Error responses are always JSON
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBody)))
	resp.WriteHeader(statusCode) // set HTTP status code and send response

	_, writeErr := resp.Write(respBody)
	if writeErr != nil {
		// We have three options here. We could log the error, call the Error
		// hook, or just silently ignore the error.
		//
		// Logging is unacceptable because we don't have a user-controlled
		// logger; writing out to stderr without permission is too rude.
		//
		// Calling the Error hook would confuse users: it would mean the Error
		// hook got called twice for one request, which is likely to lead to
		// duplicated log messages and metrics, no matter how well we document
		// the behavior.
		//
		// Silently ignoring the error is our least-bad option. It's highly
		// likely that the connection is broken and the original 'err' says
		// so anyway.
		_ = writeErr
	}

	callResponseSent(ctx, hooks)
}

// urlBase helps ensure that addr specifies a scheme. If it is unparsable
// as a URL, it returns addr unchanged.
func urlBase(addr string) string {
	// If the addr specifies a scheme, use it. If not, default to
	// http. If url.Parse fails on it, return it unchanged.
	url, err := url.Parse(addr)
	if err != nil {
		return addr
	}
	if url.Scheme == "" {
		url.Scheme = "http"
	}
	return url.String()
}

// getCustomHTTPReqHeaders retrieves a copy of any headers that are set in
// a context through the twirp.WithHTTPRequestHeaders function.
// If there are no headers set, or if they have the wrong type, nil is returned.
func getCustomHTTPReqHeaders(ctx context.Context) http.Header {
	header, ok := twirp.HTTPRequestHeaders(ctx)
	if !ok || header == nil {
		return nil
	}
	copied := make(http.Header)
	for k, vv := range header {
		if vv == nil {
			copied[k] = nil
			continue
		}
		copied[k] = make([]string, len(vv))
		copy(copied[k], vv)
	}
	return copied
}

// newRequest makes an http.Request from a client, adding common headers.
func newRequest(ctx context.Context, url string, reqBody io.Reader, contentType string) (*http.Request, error) {
	req, err := http.NewRequest("POST", url, reqBody)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if customHeader := getCustomHTTPReqHeaders(ctx); customHeader != nil {
		req.Header = customHeader
	}
	req.Header.Set("Accept", contentType)
	req.Header.Set("Content-Type", contentType)
	req.Header.Set("Twirp-Version", "v5.12.1")
	return req, nil
}

// JSON serialization for errors
type twerrJSON struct {
	Code string            `json:"code"`
	Msg  string            `json:"msg"`
	Meta map[string]string `json:"meta,omitempty"`
}

// marshalErrorToJSON returns JSON from a twirp.Error, that can be used as HTTP error response body.
// If serialization fails, it will use a descriptive Internal error instead.
func marshalErrorToJSON(twerr twirp.Error) []byte {
	// make sure that msg is not too large
	msg := twerr.Msg()
	if len(msg) > 1e6 {
		msg = msg[:1e6]
	}

	tj := twerrJSON{
		Code: string(twerr.Code()),
		Msg:  msg,
		Meta: twerr.MetaMap(),
	}

	buf, err := json.Marshal(&tj)
	if err != nil {
		buf = []byte("{\"type\": \"" + twirp.Internal + "\", \"msg\": \"There was an error but it could not be serialized into JSON\"}") // fallback
	}

	return buf
}

// errorFromResponse builds a twirp.Error from a non-200 HTTP response.
// If the response has a valid serialized Twirp error, then it's returned.
// If not, the response status code is used to generate a similar twirp
// error. See twirpErrorFromIntermediary for more info on intermediary errors.
func errorFromResponse(resp *http.Response) twirp.Error {
	statusCode := resp.StatusCode
	statusText := http.StatusText(statusCode)

	if isHTTPRedirect(statusCode) {
		// Unexpected redirect: it must be an error from an intermediary.
		// Twirp clients don't follow redirects automatically, Twirp only handles
		// POST requests, redirects should only happen on GET and HEAD requests.
		location := resp.Header.Get("Location")
		msg := fmt.Sprintf("unexpected HTTP status code %d %q received, Location=%q", statusCode, statusText, location)
		return twirpErrorFromIntermediary(statusCode, msg, location)
	}

	respBodyBytes, err := ioutil.ReadAll(resp.Body)
	if err != nil {
		return wrapInternal(err, "failed to read server error response body")
	}

	var tj twerrJSON
	dec := json.NewDecoder(bytes.NewReader(respBodyBytes))
	dec.DisallowUnknownFields()
	if err := dec.Decode(&tj); err != nil || tj.Code == "" {
		// Invalid JSON response; it must be an error from an intermediary.
		msg := fmt.Sprintf("Error from intermediary with HTTP status code %d %q", statusCode, statusText)
		return twirpErrorFromIntermediary(statusCode, msg, string(respBodyBytes))
	}

	errorCode := twirp.ErrorCode(tj.Code)
	if !twirp.IsValidErrorCode(errorCode) {
		msg := "invalid type returned from server error response: " + tj.Code
		return twirp.InternalError(msg).WithMeta("body", string(respBodyBytes))
	}

	twerr := twirp.NewError(errorCode, tj.Msg)
	for k, v := range tj.Meta {
		twerr = twerr.WithMeta(k, v)
	}
	return twerr
}

// twirpErrorFromIntermediary maps HTTP errors from non-twirp sources to twirp errors.
// The mapping is similar to gRPC: https://github.com/grpc/grpc/blob/master/doc/http-grpc-status-mapping.md.
// Returned twirp Errors have some additional metadata for inspection.
func twirpErrorFromIntermediary(status int, msg string, bodyOrLocation string) twirp.Error {
	var code twirp.ErrorCode
	if isHTTPRedirect(status) { // 3xx
		code = twirp.Internal
	} else {
		switch status {
		case 400: // Bad Request
			code = twirp.Internal
		case 401: // Unauthorized
			code = twirp.Unauthenticated
		case 403: // Forbidden
			code = twirp.PermissionDenied
		case 404: // Not Found
			code = twirp.BadRoute
		case 429, 502, 503, 504: // Too Many Requests, Bad Gateway, Service Unavailable, Gateway Timeout
			code = twirp.Unavailable
		default: // All other codes
			code = twirp.Unknown
		}
	}

	twerr := twirp.NewError(code, msg)
	twerr = twerr.WithMeta("http_error_from_intermediary", "true") // to easily know if this error was from intermediary
	twerr = twerr.WithMeta("status_code", strconv.Itoa(status))
	if isHTTPRedirect(status) {
		twerr = twerr.WithMeta("location", bodyOrLocation)
	} else {
		twerr = twerr.WithMeta("body", bodyOrLocation)
	}
	return twerr
}

func isHTTPRedirect(status int) bool {
	return status >= 300 && status <= 399
}

// wrapInternal wraps an error with a prefix as an Internal error.
// The original error cause is accessible by github.com/pkg/errors.Cause.
func wrapInternal(err error, prefix string) twirp.Error {
	return twirp.InternalErrorWith(&wrappedError{prefix: prefix, cause: err})
}

type wrappedError struct {
	prefix string
	cause  error
}

func (e *wrappedError) Error() string { return e.prefix + ": " + e.cause.Error() }
func (e *wrappedError) Unwrap() error { return e.cause } // for go1.13 + errors.Is/As
func (e *wrappedError) Cause() error  { return e.cause } // for github.com/pkg/errors

// ensurePanicResponses makes sure that rpc methods causing a panic still result in a Twirp Internal
// error response (status 500), and error hooks are properly called with the panic wrapped as an error.
// The panic is re-raised so it can be handled normally with middleware.
func ensurePanicResponses(ctx context.Context, resp http.ResponseWriter, hooks *twirp.ServerHooks) {
	if r := recover(); r != nil {
		// Wrap the panic as an error so it can be passed to error hooks.
		// The original error is accessible from error hooks, but not visible in the response.
		err := errFromPanic(r)
		twerr := &internalWithCause{msg: "Internal service panic", cause: err}
		// Actually write the error
		writeError(ctx, resp, twerr, hooks)
		// If possible, flush the error to the wire.
		f, ok := resp.(http.Flusher)
		if ok {
			f.Flush()
		}

		panic(r)
	}
}

// errFromPanic returns the typed error if the recovered panic is an error, otherwise formats as error.
func errFromPanic(p interface{}) error {
	if err, ok := p.(error); ok {
		return err
	}
	return fmt.Errorf("panic: %v", p)
}

// internalWithCause is a Twirp Internal error wrapping an original error cause,
// but the original error message is not exposed on Msg(). The original error
// can be checked with go1.13+ errors.Is/As, and also by (github.com/pkg/errors).Unwrap
type internalWithCause struct {
	msg   string
	cause error
}

func (e *internalWithCause) Unwrap() error                               { return e.cause } // for go1.13 + errors.Is/As
func (e *internalWithCause) Cause() error                                { return e.cause } // for github.com/pkg/errors
func (e *internalWithCause) Error() string                               { return e.msg + ": " + e.cause.Error() }
func (e *internalWithCause) Code() twirp.ErrorCode                       { return twirp.Internal }
func (e *internalWithCause) Msg() string                                 { return e.msg }
func (e *internalWithCause) Meta(key string) string                      { return "" }
func (e *internalWithCause) MetaMap() map[string]string                  { return nil }
func (e *internalWithCause) WithMeta(key string, val string) twirp.Error { return e }

// malformedRequestError is used when the twirp server cannot unmarshal a request
func malformedRequestError(msg string) twirp.Error {
	return twirp.NewError(twirp.Malformed, msg)
}

// badRouteError is used when the twirp server cannot route a request
func badRouteError(msg string, method, url string) twirp.Error {
	err := twirp.NewError(twirp.BadRoute, msg)
	err = err.WithMeta("twirp_invalid_route", method+" "+url)
	return err
}

// withoutRedirects makes sure that the POST request can not be redirected.
// The standard library will, by default, redirect requests (including POSTs) if it gets a 302 or
// 303 response, and also 301s in go1.8. It redirects by making a second request, changing the
// method to GET and removing the body. This produces very confusing error messages, so instead we
// set a redirect policy that always errors. This stops Go from executing the redirect.
//
// We have to be a little careful in case the user-provided http.Client has its own CheckRedirect
// policy - if so, we'll run through that policy first.
//
// Because this requires modifying the http.Client, we make a new copy of the client and return it.
func withoutRedirects(in *http.Client) *http.Client {
	copy := *in
	copy.CheckRedirect = func(req *http.Request, via []*http.Request) error {
		if in.CheckRedirect != nil {
			// Run the input's redirect if it exists, in case it has side effects, but ignore any error it
			// returns, since we want to use ErrUseLastResponse.
			err := in.CheckRedirect(req, via)
			_ = err // Silly, but this makes sure generated code passes errcheck -blank, which some people use.
		}
		return http.ErrUseLastResponse
	}
	return &copy
}

// doProtobufRequest makes a Protobuf request to the remote Twirp service.
func doProtobufRequest(ctx context.Context, client HTTPClient, hooks *twirp.ClientHooks, url string, in, out proto.Message) (_ context.Context, err error) {
	reqBodyBytes, err := proto.Marshal(in)
	if err != nil {
		return ctx, wrapInternal(err, "failed to marshal proto request")
	}
	reqBody := bytes.NewBuffer(reqBodyBytes)
	if err = ctx.Err(); err != nil {
		return ctx, wrapInternal(err, "aborted because context was done")
	}

	req, err := newRequest(ctx, url, reqBody, "application/protobuf")
	if err != nil {
		return ctx, wrapInternal(err, "could not build request")
	}
	ctx, err = callClientRequestPrepared(ctx, hooks, req)
	if err != nil {
		return ctx, err
	}

	req = req.WithContext(ctx)
	resp, err := client.Do(req)
	if err != nil {
		return ctx, wrapInternal(err, "failed to do request")
	}

	defer func() {
		cerr := resp.Body.Close()
		if err == nil && cerr != nil {
			err = wrapInternal(cerr, "failed to close response body")
		}
	}()

	if err = ctx.Err(); err != nil {
		return ctx, wrapInternal(err, "aborted because context was done")
	}

	if resp.StatusCode != 200 {
		return ctx, errorFromResponse(resp)
	}

	respBodyBytes, err := ioutil.ReadAll(resp.Body)
	if err != nil {
		return ctx, wrapInternal(err, "failed to read response body")
	}
	if err = ctx.Err(); err != nil {
		return ctx, wrapInternal(err, "aborted because context was done")
	}

	if err = proto.Unmarshal(respBodyBytes, out); err != nil {
		return ctx, wrapInternal(err, "failed to unmarshal proto response")
	}
	return ctx, nil
}

// doJSONRequest makes a JSON request to the remote Twirp service.
func doJSONRequest(ctx context.Context, client HTTPClient, hooks *twirp.ClientHooks, url string, in, out proto.Message) (_ context.Context, err error) {
	reqBody := bytes.NewBuffer(nil)
	marshaler := &jsonpb.Marshaler{OrigName: true}
	if err = marshaler.Marshal(reqBody, in); err != nil {
		return ctx, wrapInternal(err, "failed to marshal json request")
	}
	if err = ctx.Err(); err != nil {
		return ctx, wrapInternal(err, "aborted because context was done")
	}

	req, err := newRequest(ctx, url, reqBody, "application/json")
	if err != nil {
		return ctx, wrapInternal(err, "could not build request")
	}
	ctx, err = callClientRequestPrepared(ctx, hooks, req)
	if err != nil {
		return ctx, err
	}

	req = req.WithContext(ctx)
	resp, err := client.Do(req)
	if err != nil {
		return ctx, wrapInternal(err, "failed to do request")
	}

	defer func() {
		cerr := resp.Body.Close()
		if err == nil && cerr != nil {
			err = wrapInternal(cerr, "failed to close response body")
		}
	}()

	if err = ctx.Err(); err != nil {
		return ctx, wrapInternal(err, "aborted because context was done")
	}

	if resp.StatusCode != 200 {
		return ctx, errorFromResponse(resp)
	}

	unmarshaler := jsonpb.Unmarshaler{AllowUnknownFields: true}
	if err = unmarshaler.Unmarshal(resp.Body, out); err != nil {
		return ctx, wrapInternal(err, "failed to unmarshal json response")
	}
	if err = ctx.Err(); err != nil {
		return ctx, wrapInternal(err, "aborted because context was done")
	}
	return ctx, nil
}

// Call twirp.ServerHooks.RequestReceived if the hook is available
func callRequestReceived(ctx context.Context, h *twirp.ServerHooks) (context.Context, error) {
	if h == nil || h.RequestReceived == nil {
		return ctx, nil
	}
	return h.RequestReceived(ctx)
}

// Call twirp.ServerHooks.RequestRouted if the hook is available
func callRequestRouted(ctx context.Context, h *twirp.ServerHooks) (context.Context, error) {
	if h == nil || h.RequestRouted == nil {
		return ctx, nil
	}
	return h.RequestRouted(ctx)
}

// Call twirp.ServerHooks.ResponsePrepared if the hook is available
func callResponsePrepared(ctx context.Context, h *twirp.ServerHooks) context.Context {
	if h == nil || h.ResponsePrepared == nil {
		return ctx
	}
	return h.ResponsePrepared(ctx)
}

// Call twirp.ServerHooks.ResponseSent if the hook is available
func callResponseSent(ctx context.Context, h *twirp.ServerHooks) {
	if h == nil || h.ResponseSent == nil {
		return
	}
	h.ResponseSent(ctx)
}

// Call twirp.ServerHooks.Error if the hook is available
func callError(ctx context.Context, h *twirp.ServerHooks, err twirp.Error) context.Context {
	if h == nil || h.Error == nil {
		return ctx
	}
	return h.Error(ctx, err)
}

func callClientResponseReceived(ctx context.Context, h *twirp.ClientHooks) {
	if h == nil || h.ResponseReceived == nil {
		return
	}
	h.ResponseReceived(ctx)
}

func callClientRequestPrepared(ctx context.Context, h *twirp.ClientHooks, req *http.Request) (context.Context, error) {
	if h == nil || h.RequestPrepared == nil {
		return ctx, nil
	}
	return h.RequestPrepared(ctx, req)
}

func callClientError(ctx context.Context, h *twirp.ClientHooks, err twirp.Error) {
	if h == nil || h.Error == nil {
		return
	}
	h.Error(ctx, err)
}

var twirpFileDescriptor0 = []byte{
	// 898 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x55, 0xdd, 0x6e, 0x1b, 0x45,
	0x14, 0xee, 0xac, 0x1d, 0xc7, 0x7b, 0xe2, 0x98, 0x74, 0xd4, 0x36, 0x53, 0xb7, 0x51, 0xc3, 0xaa,
	0x95, 0x2c, 0x40, 0x36, 0x0d, 0x5c, 0x70, 0x4b, 0x82, 0x20, 0x95, 0x4a, 0x41, 0x93, 0x72, 0xc3,
	0x8d, 0x35, 0xf6, 0x8e, 0xd7, 0x4b, 0xbc, 0x3b, 0xcb, 0xcc, 0xd8, 0x28, 0x17, 0xdc, 0xf7, 0x39,
	0x78, 0x04, 0x6e, 0x90, 0xb8, 0x45, 0xbc, 0x04, 0x4f, 0x83, 0xe6, 0x6f, 0x6d, 0xe7, 0xa7, 0x6d,
	0x7a, 0x37, 0xe7, 0x9c, 0x6f, 0xcf, 0xcf, 0xf7, 0x9d, 0x99, 0x85, 0x8e, 0xd2, 0x4c, 0x2f, 0xd4,
	0xa0, 0x92, 0x42, 0x0b, 0xdc, 0x72, 0x56, 0xef, 0x49, 0x26, 0x44, 0x36, 0xe7, 0x43, 0xeb, 0x1d,
	0x2f, 0xa6, 0x43, 0x9d, 0x17, 0x5c, 0x69, 0x56, 0x54, 0x0e, 0x98, 0xfc, 0x85, 0xe0, 0xf1, 0x77,
	0x5c, 0xbf, 0x28, 0x27, 0x92, 0x17, 0xbc, 0xd4, 0x6c, 0x7e, 0x22, 0x8a, 0x22, 0xd7, 0x8a, 0xf2,
	0x5f, 0x17, 0x5c, 0x69, 0x3c, 0x80, 0xe6, 0x54, 0x8a, 0x82, 0xa0, 0x43, 0xd4, 0xdf, 0x39, 0xea,
	0x0d, 0x5c, 0xc2, 0x41, 0x48, 0x38, 0x78, 0x1d, 0x12, 0x52, 0x8b, 0xc3, 0x9f, 0x40, 0xa4, 0x05,
	0x89, 0xde, 0x89, 0x8e, 0xb4, 0xc0, 0x1d, 0x40, 0x25, 0x69, 0x1c, 0xa2, 0x7e, 0x83, 0xa2, 0x12,
	0xef, 0x41, 0xa3, 0x12, 0x29, 0x69, 0x1e, 0xa2, 0x7e, 0x4c, 0xcd, 0x11, 0x3f, 0x82, 0x58, 0xf2,
	0x4a, 0x8c, 0x2a, 0xa6, 0x67, 0x64, 0xcb, 0xfa, 0xdb, 0xc6, 0xf1, 0x23, 0xd3, 0xb3, 0xe4, 0x0d,
	0x82, 0x83, 0x1b, 0x3a, 0x57, 0x95, 0x28, 0x15, 0xc7, 0x5f, 0x42, 0xbb, 0xe0, 0x9a, 0xa5, 0x4c,
	0x33, 0xdf, 0x3e, 0x19, 0x78, 0x96, 0x02, 0xe6, 0x7b, 0x1f, 0xa7, 0x35, 0x12, 0x3f, 0x87, 0xd6,
	0xa2, 0x4a, 0x99, 0xe6, 0x7e, 0x88, 0x87, 0xe1, 0x9b, 0xb5, 0x4a, 0x3f, 0x59, 0x00, 0xf5, 0xc0,
	0xe4, 0x5f, 0x04, 0x77, 0xaf, 0x44, 0xf1, 0x67, 0xb0, 0x3d, 0x71, 0x1d, 0x11, 0x74, 0xd8, 0xe8,
	0xef, 0x1c, 0xe1, 0x90, 0xe9, 0xa5, 0x28, 0x33, 0xd7, 0x2c, 0x0d, 0x10, 0xfc, 0x1c, 0x3a, 0x63,
	0xc9, 0xca, 0xc9, 0x6c, 0x34, 0xe3, 0x2c, 0x55, 0x24, 0xb2, 0x9f, 0x74, 0xc3, 0x27, 0xc7, 0x36,
	0x46, 0x77, 0x1c, 0xe6, 0xd4, 0x40, 0x70, 0x02, 0x5b, 0x9a, 0xa9, 0x73, 0x45, 0x1a, 0x16, 0xdb,
	0x09, 0xd8, 0xd7, 0x4c, 0x9d, 0x53, 0x17, 0xc2, 0x9f, 0x42, 0xdb, 0x54, 0xe0, 0xa5, 0x56, 0xa4,
	0x69, 0x61, 0x1f, 0x05, 0xd8, 0x89, 0xf3, 0xd3, 0x1a, 0x90, 0x7c, 0x0e, 0x2d, 0x57, 0x07, 0x63,
	0x68, 0x96, 0xac, 0xe0, 0x96, 0xb6, 0x98, 0xda, 0xb3, 0xf1, 0x99, 0xd6, 0x2c, 0x2d, 0x31, 0xb5,
	0xe7, 0xe4, 0x0f, 0x04, 0x4d, 0x53, 0x0e, 0x93, 0xcd, 0x61, 0xe3, 0xd5, 0x60, 0x21, 0x55, 0xb4,
	0x96, 0xaa, 0x0b, 0x51, 0x9e, 0x5a, 0xe5, 0x63, 0x1a, 0xe5, 0x29, 0xee, 0x41, 0x5b, 0xf2, 0x65,
	0xae, 0x72, 0x51, 0x7a, 0xfd, 0x6b, 0x1b, 0x3f, 0x00, 0xbf, 0xcc, 0x7e, 0x03, 0xbc, 0x85, 0xfb,
	0xb0, 0xa7, 0x7e, 0x63, 0xb2, 0xc8, 0xcb, 0x6c, 0x64, 0x66, 0x1d, 0xe5, 0x29, 0x69, 0x59, 0x44,
	0x37, 0xf8, 0x4d, 0x67, 0x2f, 0xd2, 0xe4, 0x6f, 0x04, 0xb0, 0xa2, 0xdc, 0xce, 0xc1, 0xd4, 0x2c,
	0xcc, 0x66, 0xce, 0xa6, 0x08, 0x5b, 0xe8, 0x99, 0x90, 0xbe, 0x4d, 0x6f, 0x99, 0xb1, 0xd4, 0x62,
	0xfc, 0x0b, 0x9f, 0x68, 0xdf, 0x6d, 0x30, 0x4d, 0xa4, 0x62, 0xb2, 0xe6, 0x35, 0xa6, 0xc1, 0x34,
	0xf9, 0xc7, 0x22, 0xbd, 0xf0, 0xed, 0xda, 0x33, 0xfe, 0x0a, 0xe2, 0xfa, 0xe6, 0xd9, 0x2e, 0xdf,
	0x7e, 0x39, 0x56, 0xe0, 0xe4, 0x9f, 0x08, 0xb6, 0xbd, 0x52, 0x9e, 0x36, 0x54, 0xd3, 0x86, 0xa1,
	0x69, 0xae, 0x43, 0xa0, 0xd6, 0x9c, 0x37, 0x2b, 0x35, 0x6e, 0x51, 0xc9, 0x64, 0x5b, 0x28, 0x2e,
	0xbd, 0x00, 0xf6, 0x6c, 0xa6, 0x2c, 0xb8, 0x52, 0x2c, 0xe3, 0x7e, 0x9c, 0x60, 0x9a, 0x48, 0xca,
	0xe7, 0x5c, 0x73, 0xc7, 0x7a, 0x9b, 0x06, 0x13, 0x3f, 0x83, 0x6e, 0x9e, 0x95, 0x42, 0xf2, 0xd1,
	0x94, 0xe5, 0xf3, 0x85, 0xe4, 0x64, 0xdb, 0x02, 0x76, 0x9d, 0xf7, 0x5b, 0xe7, 0xc4, 0xf7, 0x60,
	0x6b, 0x3a, 0x67, 0xe7, 0x17, 0xa4, 0x6d, 0xa3, 0xce, 0xc0, 0x4f, 0xa1, 0x6b, 0xc5, 0x54, 0x15,
	0x9f, 0x8c, 0xec, 0xde, 0xc4, 0xb6, 0x6e, 0xc7, 0x78, 0xcf, 0x2a, 0x3e, 0x79, 0x65, 0xf6, 0x67,
	0x1f, 0xb6, 0x83, 0xe4, 0xe0, 0xf4, 0xd2, 0x56, 0x6a, 0xa3, 0xa3, 0xdb, 0x3b, 0xb2, 0xe3, 0xfc,
	0xce, 0x4a, 0x7e, 0x87, 0xbd, 0xcb, 0x57, 0x1e, 0x1f, 0x00, 0x28, 0xcd, 0xa4, 0x1e, 0x89, 0x25,
	0x97, 0x96, 0xd5, 0x36, 0x8d, 0xad, 0xe7, 0x87, 0x25, 0x97, 0xe1, 0x39, 0x8a, 0x56, 0xcf, 0xd1,
	0x07, 0x53, 0x9b, 0xfc, 0x87, 0xe0, 0xee, 0xd7, 0x69, 0x1a, 0x6e, 0x9c, 0x7f, 0x5a, 0x83, 0x7c,
	0x68, 0x4d, 0x3e, 0x52, 0x0f, 0x60, 0x0b, 0x9f, 0xde, 0x09, 0x23, 0xe0, 0x03, 0x88, 0x6b, 0x66,
	0xdc, 0x32, 0x9e, 0xde, 0xa1, 0xed, 0x40, 0x0b, 0x7e, 0xb8, 0xa2, 0xa4, 0x19, 0xbe, 0xf4, 0xa4,
	0xdc, 0x2c, 0x62, 0xad, 0x41, 0x6b, 0x5d, 0x83, 0xf7, 0x13, 0xf0, 0xb8, 0x05, 0x4d, 0x7d, 0x51,
	0xf1, 0xe4, 0x15, 0xe0, 0xf5, 0xd9, 0xfc, 0xe3, 0xbb, 0x41, 0x16, 0xba, 0x0d, 0x59, 0x7f, 0x22,
	0xb8, 0xf7, 0x8d, 0xdd, 0xa5, 0xf7, 0xe0, 0xeb, 0xc1, 0x26, 0x5f, 0x35, 0x5b, 0x8f, 0xae, 0xb0,
	0xb5, 0xc6, 0xd5, 0xfe, 0x25, 0xae, 0x6a, 0xa6, 0x36, 0x9a, 0xde, 0xba, 0x4d, 0xd3, 0xfb, 0x70,
	0xff, 0x52, 0xcf, 0x8e, 0x87, 0xa3, 0x37, 0x11, 0xec, 0x9e, 0xd9, 0x17, 0xeb, 0x8c, 0xcb, 0x65,
	0x3e, 0xe1, 0x38, 0x85, 0xfb, 0xd7, 0xfe, 0xb7, 0xf0, 0xd3, 0xf0, 0x32, 0xbf, 0xed, 0x87, 0xdc,
	0x7b, 0xf6, 0x0e, 0x94, 0xe7, 0xff, 0x04, 0x60, 0xa5, 0x0a, 0xae, 0x7f, 0x62, 0x57, 0xb6, 0xb0,
	0xd7, 0xbb, 0x2e, 0xe4, 0x93, 0xbc, 0x84, 0xdd, 0x8d, 0xa9, 0xf0, 0xe3, 0x00, 0xbe, 0x4e, 0xa0,
	0xde, 0xc1, 0x0d, 0x51, 0x97, 0xed, 0xf8, 0xe3, 0x9f, 0x9f, 0x64, 0x62, 0xa0, 0xce, 0x73, 0x36,
	0x10, 0x32, 0x1b, 0xe6, 0xe5, 0x54, 0xb2, 0xa1, 0xfb, 0x62, 0x98, 0x89, 0xa1, 0xac, 0x26, 0xe3,
	0x96, 0x65, 0xf9, 0x8b, 0xff, 0x03, 0x00, 0x00, 0xff, 0xff, 0x6b, 0x95, 0xd0, 0xb8, 0xce, 0x08,
	0x00, 0x00,
}
