// This is taken from a production /json/trstatus request (specifically the corpStatus section).
export const exampleCorpora = [{
  name: 'canvaskit',
  ok: false,
  minCommitHash: '',
  untriagedCount: 2,
  negativeCount: 2,
}, {
  name: 'colorImage',
  ok: true,
  minCommitHash: '',
  untriagedCount: 0,
  negativeCount: 1,
}, {
  name: 'gm',
  ok: false,
  minCommitHash: '',
  untriagedCount: 61,
  negativeCount: 1494,
}, {
  name: 'image',
  ok: false,
  minCommitHash: '',
  untriagedCount: 22,
  negativeCount: 35,
}, {
  name: 'pathkit',
  ok: true,
  minCommitHash: '',
  untriagedCount: 0,
  negativeCount: 0,
}, {
  name: 'skp',
  ok: true,
  minCommitHash: '',
  untriagedCount: 0,
  negativeCount: 1,
}, {
  name: 'svg',
  ok: false,
  minCommitHash: '',
  untriagedCount: 19,
  negativeCount: 21,
}];
