- name: Install Python 3
  win_package:
    # Reference: https://docs.python.org/3.9/using/windows.html#installing-without-ui
    path: https://www.python.org/ftp/python/3.9.7/python-3.9.7-amd64.exe
    arguments:
      - /quiet
      - 'TargetDir={{ win_python3_path }}'
      - PrependPath=1
      - Include_launcher=0
    state: present

- name: Install pywin32
  win_command: "{{ win_python3_path }}\\Scripts\\pip.exe install pywin32"

# The below tasks were copied from
# https://skia.googlesource.com/buildbot/+/ddcf7644bee4286f4030978c61d977858d9e80de/skolo/win/ansible/skolo-credentials.yml.

- name: Create empty C:\.boto file
  win_file:
    path: C:\.boto
    state: touch

- name: Create empty C:\Users\chrome-bot\.boto file
  win_file:
    path: C:\Users\chrome-bot\.boto
    state: touch

- name: Create C:\swarming_config directory
  win_file:
    path: C:\swarming_config
    state: directory

- name: Copy oauth2 config file
  win_template:
    src: templates/oauth2_access_token_config.json
    dest: C:\swarming_config\oauth2_access_token_config.json

- name: Stop Swarming from running on its own.
  win_environment:
    name: SWARMING_EXTERNAL_BOT_SETUP
    level: machine
    state: present
    value: '1'

# Only necessary for GCE machines. As of 2023-03-23, Skolo machines have the necessary permissions
# by default, but we run this step on all machines for consistency. The difference in permission
# defaults can probably be attributed to the fact that GCE machines run Windows Server, whereas
# Skolo machines run Windows 10.
- name: Give Swarming (via the chrome-bot user) permission to reboot the machine.
  # https://docs.ansible.com/ansible/latest/collections/ansible/windows/win_user_right_module.html
  win_user_right:
    # List of possible values:
    # https://learn.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/user-rights-assignment
    name: SeShutdownPrivilege
    users:
    - Users
    - '{{ ansible_hostname }}\chrome-bot'
    action: add

- name: Give Swarming (via the chrome-bot user) permission to create symlinks (required for Bazel).
  # https://docs.ansible.com/ansible/latest/collections/ansible/windows/win_user_right_module.html
  win_user_right:
    # List of possible values:
    # https://learn.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/user-rights-assignment
    name: SeCreateSymbolicLinkPrivilege
    users:
    - Users
    - '{{ ansible_hostname }}\chrome-bot'
    action: add

- name: Delete old metadata server from hosts file if applicable.
  # Based on
  # https://skia.googlesource.com/buildbot/+/f90b188b889759a0646ac296320a4d73ca32542a/skolo/win/ansible/skolo-credentials.yml#18.
  win_lineinfile:
    path: c:\Windows\System32\Drivers\etc\hosts
    regex: '^\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}.*metadata$'
    state: absent

- name: Add metadata server to hosts file.
  # Based on
  # https://skia.googlesource.com/buildbot/+/f90b188b889759a0646ac296320a4d73ca32542a/skolo/win/ansible/skolo-credentials.yml#18.
  win_lineinfile:
    path: c:\Windows\System32\Drivers\etc\hosts
    line: "{{ metadata_ip }} metadata"
