// Code generated by protoc-gen-go. DO NOT EDIT.
// source: diffservice.proto

package diffstore

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_7be44b2c6ca656f4, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type GetDiffsRequest struct {
	Priority             int64    `protobuf:"varint,1,opt,name=priority,proto3" json:"priority,omitempty"`
	MainDigest           string   `protobuf:"bytes,2,opt,name=mainDigest,proto3" json:"mainDigest,omitempty"`
	RightDigests         []string `protobuf:"bytes,3,rep,name=rightDigests,proto3" json:"rightDigests,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDiffsRequest) Reset()         { *m = GetDiffsRequest{} }
func (m *GetDiffsRequest) String() string { return proto.CompactTextString(m) }
func (*GetDiffsRequest) ProtoMessage()    {}
func (*GetDiffsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7be44b2c6ca656f4, []int{1}
}

func (m *GetDiffsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDiffsRequest.Unmarshal(m, b)
}
func (m *GetDiffsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDiffsRequest.Marshal(b, m, deterministic)
}
func (m *GetDiffsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDiffsRequest.Merge(m, src)
}
func (m *GetDiffsRequest) XXX_Size() int {
	return xxx_messageInfo_GetDiffsRequest.Size(m)
}
func (m *GetDiffsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDiffsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetDiffsRequest proto.InternalMessageInfo

func (m *GetDiffsRequest) GetPriority() int64 {
	if m != nil {
		return m.Priority
	}
	return 0
}

func (m *GetDiffsRequest) GetMainDigest() string {
	if m != nil {
		return m.MainDigest
	}
	return ""
}

func (m *GetDiffsRequest) GetRightDigests() []string {
	if m != nil {
		return m.RightDigests
	}
	return nil
}

type GetDiffsResponse struct {
	Diffs                []byte   `protobuf:"bytes,1,opt,name=diffs,proto3" json:"diffs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDiffsResponse) Reset()         { *m = GetDiffsResponse{} }
func (m *GetDiffsResponse) String() string { return proto.CompactTextString(m) }
func (*GetDiffsResponse) ProtoMessage()    {}
func (*GetDiffsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7be44b2c6ca656f4, []int{2}
}

func (m *GetDiffsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDiffsResponse.Unmarshal(m, b)
}
func (m *GetDiffsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDiffsResponse.Marshal(b, m, deterministic)
}
func (m *GetDiffsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDiffsResponse.Merge(m, src)
}
func (m *GetDiffsResponse) XXX_Size() int {
	return xxx_messageInfo_GetDiffsResponse.Size(m)
}
func (m *GetDiffsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDiffsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetDiffsResponse proto.InternalMessageInfo

func (m *GetDiffsResponse) GetDiffs() []byte {
	if m != nil {
		return m.Diffs
	}
	return nil
}

type PurgeDigestsRequest struct {
	Digests              []string `protobuf:"bytes,1,rep,name=digests,proto3" json:"digests,omitempty"`
	PurgeGCS             bool     `protobuf:"varint,2,opt,name=purgeGCS,proto3" json:"purgeGCS,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PurgeDigestsRequest) Reset()         { *m = PurgeDigestsRequest{} }
func (m *PurgeDigestsRequest) String() string { return proto.CompactTextString(m) }
func (*PurgeDigestsRequest) ProtoMessage()    {}
func (*PurgeDigestsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7be44b2c6ca656f4, []int{3}
}

func (m *PurgeDigestsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PurgeDigestsRequest.Unmarshal(m, b)
}
func (m *PurgeDigestsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PurgeDigestsRequest.Marshal(b, m, deterministic)
}
func (m *PurgeDigestsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PurgeDigestsRequest.Merge(m, src)
}
func (m *PurgeDigestsRequest) XXX_Size() int {
	return xxx_messageInfo_PurgeDigestsRequest.Size(m)
}
func (m *PurgeDigestsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PurgeDigestsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PurgeDigestsRequest proto.InternalMessageInfo

func (m *PurgeDigestsRequest) GetDigests() []string {
	if m != nil {
		return m.Digests
	}
	return nil
}

func (m *PurgeDigestsRequest) GetPurgeGCS() bool {
	if m != nil {
		return m.PurgeGCS
	}
	return false
}

type UnavailableDigestsResponse struct {
	DigestFailures       map[string]*DigestFailureResponse `protobuf:"bytes,1,rep,name=digestFailures,proto3" json:"digestFailures,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *UnavailableDigestsResponse) Reset()         { *m = UnavailableDigestsResponse{} }
func (m *UnavailableDigestsResponse) String() string { return proto.CompactTextString(m) }
func (*UnavailableDigestsResponse) ProtoMessage()    {}
func (*UnavailableDigestsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7be44b2c6ca656f4, []int{4}
}

func (m *UnavailableDigestsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnavailableDigestsResponse.Unmarshal(m, b)
}
func (m *UnavailableDigestsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnavailableDigestsResponse.Marshal(b, m, deterministic)
}
func (m *UnavailableDigestsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnavailableDigestsResponse.Merge(m, src)
}
func (m *UnavailableDigestsResponse) XXX_Size() int {
	return xxx_messageInfo_UnavailableDigestsResponse.Size(m)
}
func (m *UnavailableDigestsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UnavailableDigestsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UnavailableDigestsResponse proto.InternalMessageInfo

func (m *UnavailableDigestsResponse) GetDigestFailures() map[string]*DigestFailureResponse {
	if m != nil {
		return m.DigestFailures
	}
	return nil
}

type WarmDigestsRequest struct {
	Priority             int64    `protobuf:"varint,1,opt,name=priority,proto3" json:"priority,omitempty"`
	Digests              []string `protobuf:"bytes,2,rep,name=digests,proto3" json:"digests,omitempty"`
	Sync                 bool     `protobuf:"varint,3,opt,name=sync,proto3" json:"sync,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WarmDigestsRequest) Reset()         { *m = WarmDigestsRequest{} }
func (m *WarmDigestsRequest) String() string { return proto.CompactTextString(m) }
func (*WarmDigestsRequest) ProtoMessage()    {}
func (*WarmDigestsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7be44b2c6ca656f4, []int{5}
}

func (m *WarmDigestsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WarmDigestsRequest.Unmarshal(m, b)
}
func (m *WarmDigestsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WarmDigestsRequest.Marshal(b, m, deterministic)
}
func (m *WarmDigestsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WarmDigestsRequest.Merge(m, src)
}
func (m *WarmDigestsRequest) XXX_Size() int {
	return xxx_messageInfo_WarmDigestsRequest.Size(m)
}
func (m *WarmDigestsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WarmDigestsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WarmDigestsRequest proto.InternalMessageInfo

func (m *WarmDigestsRequest) GetPriority() int64 {
	if m != nil {
		return m.Priority
	}
	return 0
}

func (m *WarmDigestsRequest) GetDigests() []string {
	if m != nil {
		return m.Digests
	}
	return nil
}

func (m *WarmDigestsRequest) GetSync() bool {
	if m != nil {
		return m.Sync
	}
	return false
}

type DigestFailureResponse struct {
	Digest               string   `protobuf:"bytes,1,opt,name=Digest,proto3" json:"Digest,omitempty"`
	Reason               string   `protobuf:"bytes,2,opt,name=Reason,proto3" json:"Reason,omitempty"`
	TS                   int64    `protobuf:"varint,3,opt,name=TS,proto3" json:"TS,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DigestFailureResponse) Reset()         { *m = DigestFailureResponse{} }
func (m *DigestFailureResponse) String() string { return proto.CompactTextString(m) }
func (*DigestFailureResponse) ProtoMessage()    {}
func (*DigestFailureResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7be44b2c6ca656f4, []int{6}
}

func (m *DigestFailureResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DigestFailureResponse.Unmarshal(m, b)
}
func (m *DigestFailureResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DigestFailureResponse.Marshal(b, m, deterministic)
}
func (m *DigestFailureResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DigestFailureResponse.Merge(m, src)
}
func (m *DigestFailureResponse) XXX_Size() int {
	return xxx_messageInfo_DigestFailureResponse.Size(m)
}
func (m *DigestFailureResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DigestFailureResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DigestFailureResponse proto.InternalMessageInfo

func (m *DigestFailureResponse) GetDigest() string {
	if m != nil {
		return m.Digest
	}
	return ""
}

func (m *DigestFailureResponse) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

func (m *DigestFailureResponse) GetTS() int64 {
	if m != nil {
		return m.TS
	}
	return 0
}

func init() {
	proto.RegisterType((*Empty)(nil), "diffstore.Empty")
	proto.RegisterType((*GetDiffsRequest)(nil), "diffstore.GetDiffsRequest")
	proto.RegisterType((*GetDiffsResponse)(nil), "diffstore.GetDiffsResponse")
	proto.RegisterType((*PurgeDigestsRequest)(nil), "diffstore.PurgeDigestsRequest")
	proto.RegisterType((*UnavailableDigestsResponse)(nil), "diffstore.UnavailableDigestsResponse")
	proto.RegisterMapType((map[string]*DigestFailureResponse)(nil), "diffstore.UnavailableDigestsResponse.DigestFailuresEntry")
	proto.RegisterType((*WarmDigestsRequest)(nil), "diffstore.WarmDigestsRequest")
	proto.RegisterType((*DigestFailureResponse)(nil), "diffstore.DigestFailureResponse")
}

func init() { proto.RegisterFile("diffservice.proto", fileDescriptor_7be44b2c6ca656f4) }

var fileDescriptor_7be44b2c6ca656f4 = []byte{
	// 455 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0x41, 0x6f, 0xd3, 0x30,
	0x14, 0x6e, 0x92, 0x75, 0x6b, 0x5f, 0xab, 0x51, 0xde, 0x00, 0x45, 0x41, 0x4c, 0x95, 0x25, 0xa4,
	0x1e, 0x50, 0x0f, 0x45, 0x42, 0xc0, 0x09, 0x41, 0xcb, 0x0e, 0x1c, 0x98, 0xdc, 0xa1, 0xdd, 0x90,
	0xbc, 0xce, 0x2b, 0x16, 0x69, 0x92, 0xd9, 0x4e, 0xa5, 0xfc, 0x54, 0xee, 0xfc, 0x10, 0x14, 0x3b,
	0xe9, 0x9c, 0x36, 0x20, 0x6e, 0xfe, 0x9e, 0xdf, 0xfb, 0xfc, 0xf9, 0xf3, 0x97, 0xc0, 0xe3, 0x5b,
	0x71, 0x77, 0xa7, 0xb8, 0xdc, 0x8a, 0x15, 0x9f, 0x66, 0x32, 0xd5, 0x29, 0xf6, 0x4d, 0x49, 0xa7,
	0x92, 0x93, 0x13, 0xe8, 0x2e, 0x36, 0x99, 0x2e, 0xc8, 0x3d, 0x3c, 0xba, 0xe0, 0x7a, 0x5e, 0x6e,
	0x50, 0x7e, 0x9f, 0x73, 0xa5, 0x31, 0x82, 0x5e, 0x26, 0x45, 0x2a, 0x85, 0x2e, 0x42, 0x6f, 0xec,
	0x4d, 0x02, 0xba, 0xc3, 0x78, 0x0e, 0xb0, 0x61, 0x22, 0x99, 0x8b, 0x35, 0x57, 0x3a, 0xf4, 0xc7,
	0xde, 0xa4, 0x4f, 0x9d, 0x0a, 0x12, 0x18, 0x4a, 0xb1, 0xfe, 0xa1, 0x2d, 0x54, 0x61, 0x30, 0x0e,
	0x26, 0x7d, 0xda, 0xa8, 0x91, 0x09, 0x8c, 0x1e, 0x8e, 0x54, 0x59, 0x9a, 0x28, 0x8e, 0x4f, 0xa0,
	0x6b, 0xc4, 0x99, 0x03, 0x87, 0xd4, 0x02, 0xf2, 0x05, 0xce, 0x2e, 0x73, 0xb9, 0xe6, 0xd5, 0x64,
	0x2d, 0x30, 0x84, 0x93, 0xdb, 0x8a, 0xdf, 0x33, 0xfc, 0x35, 0x34, 0xd2, 0xcb, 0x81, 0x8b, 0x4f,
	0x4b, 0x23, 0xae, 0x47, 0x77, 0x98, 0xfc, 0xf6, 0x20, 0xfa, 0x96, 0xb0, 0x2d, 0x13, 0x31, 0xbb,
	0x89, 0x1f, 0x38, 0x2b, 0x05, 0x0c, 0x4e, 0x2d, 0xcb, 0x67, 0x26, 0xe2, 0x5c, 0x72, 0xcb, 0x3d,
	0x98, 0xbd, 0x9b, 0xee, 0x5c, 0x9b, 0xfe, 0x7d, 0x7c, 0x3a, 0x6f, 0xcc, 0x2e, 0x12, 0x2d, 0x0b,
	0xba, 0x47, 0x18, 0xad, 0xe0, 0xac, 0xa5, 0x0d, 0x47, 0x10, 0xfc, 0xe4, 0xd6, 0xea, 0x3e, 0x2d,
	0x97, 0xf8, 0x06, 0xba, 0x5b, 0x16, 0xe7, 0xdc, 0xdc, 0x61, 0x30, 0x1b, 0x3b, 0x12, 0x1a, 0x04,
	0xf5, 0xe9, 0xd4, 0xb6, 0xbf, 0xf7, 0xdf, 0x7a, 0xe4, 0x3b, 0xe0, 0x35, 0x93, 0x9b, 0x3d, 0xcb,
	0xfe, 0xf5, 0xa6, 0x8e, 0x9d, 0x7e, 0xd3, 0x4e, 0x84, 0x23, 0x55, 0x24, 0xab, 0x30, 0x30, 0x56,
	0x9a, 0x35, 0xb9, 0x86, 0xa7, 0xad, 0x1a, 0xf0, 0x19, 0x1c, 0x57, 0xb1, 0xb0, 0x37, 0xa9, 0x50,
	0x59, 0xa7, 0x9c, 0xa9, 0x34, 0xa9, 0xe2, 0x52, 0x21, 0x3c, 0x05, 0xff, 0x6a, 0x69, 0xa8, 0x03,
	0xea, 0x5f, 0x2d, 0x67, 0xbf, 0x7c, 0x18, 0x94, 0xa1, 0x58, 0xda, 0xcc, 0xe2, 0x02, 0x7a, 0x75,
	0x4c, 0x30, 0x72, 0x1c, 0xd8, 0x8b, 0x6b, 0xf4, 0xbc, 0x75, 0xcf, 0x8a, 0x22, 0x1d, 0xfc, 0x00,
	0x03, 0xc7, 0x0f, 0x7c, 0xe1, 0x74, 0x1f, 0xfa, 0x14, 0x8d, 0x9c, 0x6d, 0xfb, 0x81, 0x74, 0xf0,
	0x2b, 0xe0, 0xe1, 0xc3, 0xe3, 0x41, 0x67, 0xf4, 0xf2, 0xbf, 0x92, 0x42, 0x3a, 0xf8, 0x11, 0x86,
	0x6e, 0xac, 0xf1, 0xdc, 0x19, 0x6c, 0xc9, 0x7b, 0xab, 0xa8, 0x57, 0x70, 0x74, 0x29, 0x92, 0x75,
	0x8b, 0x8c, 0x96, 0xee, 0x9b, 0x63, 0xf3, 0x03, 0x78, 0xfd, 0x27, 0x00, 0x00, 0xff, 0xff, 0xda,
	0x77, 0x51, 0xac, 0x15, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DiffServiceClient is the client API for DiffService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DiffServiceClient interface {
	// Same functionality as Get in the diff.DiffStore interface.
	GetDiffs(ctx context.Context, in *GetDiffsRequest, opts ...grpc.CallOption) (*GetDiffsResponse, error)
	// Same functionality as WarmDigests in the diff.DiffStore interface.
	WarmDigests(ctx context.Context, in *WarmDigestsRequest, opts ...grpc.CallOption) (*Empty, error)
	// Same functionality asSee UnavailableDigests in the diff.DiffStore interface.
	UnavailableDigests(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*UnavailableDigestsResponse, error)
	//Same functionality asSee PurgeDigestset in the diff.DiffStore interface.
	PurgeDigests(ctx context.Context, in *PurgeDigestsRequest, opts ...grpc.CallOption) (*Empty, error)
	// Ping is used to test connection.
	Ping(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
}

type diffServiceClient struct {
	cc *grpc.ClientConn
}

func NewDiffServiceClient(cc *grpc.ClientConn) DiffServiceClient {
	return &diffServiceClient{cc}
}

func (c *diffServiceClient) GetDiffs(ctx context.Context, in *GetDiffsRequest, opts ...grpc.CallOption) (*GetDiffsResponse, error) {
	out := new(GetDiffsResponse)
	err := c.cc.Invoke(ctx, "/diffstore.DiffService/GetDiffs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diffServiceClient) WarmDigests(ctx context.Context, in *WarmDigestsRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/diffstore.DiffService/WarmDigests", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diffServiceClient) UnavailableDigests(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*UnavailableDigestsResponse, error) {
	out := new(UnavailableDigestsResponse)
	err := c.cc.Invoke(ctx, "/diffstore.DiffService/UnavailableDigests", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diffServiceClient) PurgeDigests(ctx context.Context, in *PurgeDigestsRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/diffstore.DiffService/PurgeDigests", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diffServiceClient) Ping(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/diffstore.DiffService/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DiffServiceServer is the server API for DiffService service.
type DiffServiceServer interface {
	// Same functionality as Get in the diff.DiffStore interface.
	GetDiffs(context.Context, *GetDiffsRequest) (*GetDiffsResponse, error)
	// Same functionality as WarmDigests in the diff.DiffStore interface.
	WarmDigests(context.Context, *WarmDigestsRequest) (*Empty, error)
	// Same functionality asSee UnavailableDigests in the diff.DiffStore interface.
	UnavailableDigests(context.Context, *Empty) (*UnavailableDigestsResponse, error)
	//Same functionality asSee PurgeDigestset in the diff.DiffStore interface.
	PurgeDigests(context.Context, *PurgeDigestsRequest) (*Empty, error)
	// Ping is used to test connection.
	Ping(context.Context, *Empty) (*Empty, error)
}

// UnimplementedDiffServiceServer can be embedded to have forward compatible implementations.
type UnimplementedDiffServiceServer struct {
}

func (*UnimplementedDiffServiceServer) GetDiffs(ctx context.Context, req *GetDiffsRequest) (*GetDiffsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDiffs not implemented")
}
func (*UnimplementedDiffServiceServer) WarmDigests(ctx context.Context, req *WarmDigestsRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WarmDigests not implemented")
}
func (*UnimplementedDiffServiceServer) UnavailableDigests(ctx context.Context, req *Empty) (*UnavailableDigestsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnavailableDigests not implemented")
}
func (*UnimplementedDiffServiceServer) PurgeDigests(ctx context.Context, req *PurgeDigestsRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PurgeDigests not implemented")
}
func (*UnimplementedDiffServiceServer) Ping(ctx context.Context, req *Empty) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}

func RegisterDiffServiceServer(s *grpc.Server, srv DiffServiceServer) {
	s.RegisterService(&_DiffService_serviceDesc, srv)
}

func _DiffService_GetDiffs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDiffsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiffServiceServer).GetDiffs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/diffstore.DiffService/GetDiffs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiffServiceServer).GetDiffs(ctx, req.(*GetDiffsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiffService_WarmDigests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WarmDigestsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiffServiceServer).WarmDigests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/diffstore.DiffService/WarmDigests",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiffServiceServer).WarmDigests(ctx, req.(*WarmDigestsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiffService_UnavailableDigests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiffServiceServer).UnavailableDigests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/diffstore.DiffService/UnavailableDigests",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiffServiceServer).UnavailableDigests(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiffService_PurgeDigests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PurgeDigestsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiffServiceServer).PurgeDigests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/diffstore.DiffService/PurgeDigests",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiffServiceServer).PurgeDigests(ctx, req.(*PurgeDigestsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiffService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiffServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/diffstore.DiffService/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiffServiceServer).Ping(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _DiffService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "diffstore.DiffService",
	HandlerType: (*DiffServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDiffs",
			Handler:    _DiffService_GetDiffs_Handler,
		},
		{
			MethodName: "WarmDigests",
			Handler:    _DiffService_WarmDigests_Handler,
		},
		{
			MethodName: "UnavailableDigests",
			Handler:    _DiffService_UnavailableDigests_Handler,
		},
		{
			MethodName: "PurgeDigests",
			Handler:    _DiffService_PurgeDigests_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _DiffService_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "diffservice.proto",
}
