#!/bin/bash
# Builds and uploads a debian package for graphite-exporter.
APPNAME=graphite-exporter
DESCRIPTION="Takes collectd metrics via graphite and exports them to Prometheus."
SYSTEMD="graphite-exporter.service"

set -x -e

# Copy files into the right locations in ${ROOT}.
copy_release_files()
{
INSTALL="fakeroot install -D --verbose --backup=none --group=root --owner=root"
INSTALL_DIR="fakeroot install -d --verbose --backup=none --group=root --owner=root"

${INSTALL} --mode=755 -T ./tmp/graphite_exporter           ${ROOT}/usr/local/bin/graphite_exporter
${INSTALL} --mode=644 -T ./sys/graphite-exporter.service   ${ROOT}/etc/systemd/system/graphite-exporter.service
${INSTALL} --mode=644 -T ./sys/graphite-exporter.conf      ${ROOT}/etc/graphite-exporter/graphite-exporter.conf
}

source ../bash/release.sh
