// Code generated by mockery v2.4.0. DO NOT EDIT.

package mocks

import (
	context "context"
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// ProjectAudit is an autogenerated mock type for the ProjectAudit type
type ProjectAudit struct {
	mock.Mock
}

// StartAudit provides a mock function with given fields: ctx, pollInterval
func (_m *ProjectAudit) StartAudit(ctx context.Context, pollInterval time.Duration) {
	_m.Called(ctx, pollInterval)
}
