# tasks file for load-secret-vars
- name: Make temp directory for secrets
  delegate_to: 127.0.0.1
  tempfile:
    state: directory
  register: secrets_dir

- name: Extract secrets and trigger `clean_up_tempfile` handler for cleanup.
  delegate_to: 127.0.0.1
  command:
    argv:
      - '{{ all.repo_root }}/kube/secrets/download-gcp-secret.sh'
      - ansible-secret-vars
      - '{{ secrets_dir.path }}/secrets.yml'
    creates: '{{ secrets_dir.path }}/secrets.yml'

- name: Import secrets as vars
  include_vars:
    file: '{{ secrets_dir.path }}/secrets.yml'
