---
# Ensure Swarming can reboot the host.
- hosts: all
  remote_user: chrome-bot
  become: yes

  tasks:
    - name: Create and set permissions on /b
      file:
        path: /b
        state: directory
        owner: chrome-bot
