// Code generated by "go run gen_versions.go"; DO NOT EDIT

package cipd

var PACKAGES = map[string]*Package{
	"infra/git/${platform}": {
		Dest:    "cipd_bin_packages",
		Name:    "infra/git/${platform}",
		Version: "version:2.23.0.chromium16",
	},
	"infra/gsutil": {
		Dest:    "cipd_bin_packages",
		Name:    "infra/gsutil",
		Version: "version:4.28",
	},
	"infra/python/cpython/${platform}": {
		Dest:    "cipd_bin_packages",
		Name:    "infra/python/cpython/${platform}",
		Version: "version:2.7.14.chromium14",
	},
	"infra/tools/cipd/${os}-${arch}": {
		Dest:    ".",
		Name:    "infra/tools/cipd/${os}-${arch}",
		Version: "latest",
	},
	"infra/tools/git/${platform}": {
		Dest:    "cipd_bin_packages",
		Name:    "infra/tools/git/${platform}",
		Version: "git_revision:0275b342af7f4ef18f4513f80d3b0e5c1bb3fb6c",
	},
	"infra/tools/luci-auth/${platform}": {
		Dest:    "cipd_bin_packages",
		Name:    "infra/tools/luci-auth/${platform}",
		Version: "git_revision:2c805f1c716f6c5ad2126b27ec88b8585a09481e",
	},
	"infra/tools/luci/git-credential-luci/${platform}": {
		Dest:    "cipd_bin_packages",
		Name:    "infra/tools/luci/git-credential-luci/${platform}",
		Version: "git_revision:2c805f1c716f6c5ad2126b27ec88b8585a09481e",
	},
	"infra/tools/luci/isolate/${platform}": {
		Dest:    "cipd_bin_packages",
		Name:    "infra/tools/luci/isolate/${platform}",
		Version: "git_revision:6759c8c87f5b20e96215db107ec1b050ade347bd",
	},
	"infra/tools/luci/isolated/${platform}": {
		Dest:    "cipd_bin_packages",
		Name:    "infra/tools/luci/isolated/${platform}",
		Version: "git_revision:6759c8c87f5b20e96215db107ec1b050ade347bd",
	},
	"infra/tools/luci/kitchen/${platform}": {
		Dest:    ".",
		Name:    "infra/tools/luci/kitchen/${platform}",
		Version: "git_revision:d8f38ca9494b5af249942631f9cee45927f6b4bc",
	},
	"infra/tools/luci/swarming/${platform}": {
		Dest:    "cipd_bin_packages",
		Name:    "infra/tools/luci/swarming/${platform}",
		Version: "git_revision:6759c8c87f5b20e96215db107ec1b050ade347bd",
	},
	"infra/tools/luci/vpython/${platform}": {
		Dest:    "cipd_bin_packages",
		Name:    "infra/tools/luci/vpython/${platform}",
		Version: "git_revision:96f81e737868d43124b4661cf1c325296ca04944",
	},
	"skia/bots/gcloud_linux": {
		Dest:    "gcloud_linux",
		Name:    "skia/bots/gcloud_linux",
		Version: "version:14",
	},
	"skia/bots/go": {
		Dest:    "go",
		Name:    "skia/bots/go",
		Version: "version:7",
	},
	"skia/bots/go_win": {
		Dest:    "go_win",
		Name:    "skia/bots/go_win",
		Version: "version:0",
	},
	"skia/bots/node": {
		Dest:    "node",
		Name:    "skia/bots/node",
		Version: "version:0",
	},
	"skia/bots/protoc": {
		Dest:    "protoc",
		Name:    "skia/bots/protoc",
		Version: "version:0",
	},
}
