// Code generated by "go run gen_versions.go"; DO NOT EDIT

package cipd

var PACKAGES = map[string]*Package{
	"infra/3pp/tools/cpython3/${platform}": {
		Path:    ".",
		Name:    "infra/3pp/tools/cpython3/${platform}",
		Version: "version:3@3.14.8.chromium.1",
	},
	"infra/3pp/tools/git/${platform}": {
		Path:    ".",
		Name:    "infra/3pp/tools/git/${platform}",
		Version: "version:3@2.56.0.chromium.11",
	},
	"infra/tools/cipd/${platform}": {
		Path:    ".",
		Name:    "infra/tools/cipd/${platform}",
		Version: "git_revision:9119ead6d70953d1f9a7670979431344c2cc3f10",
	},
	"infra/tools/git/${platform}": {
		Path:    ".",
		Name:    "infra/tools/git/${platform}",
		Version: "git_revision:3d1174859c0a5bb00d87c78506f8c031afad16aa",
	},
	"infra/tools/luci-auth/${platform}": {
		Path:    ".",
		Name:    "infra/tools/luci-auth/${platform}",
		Version: "git_revision:9119ead6d70953d1f9a7670979431344c2cc3f10",
	},
	"infra/tools/luci/docker-credential-luci/${platform}": {
		Path:    ".",
		Name:    "infra/tools/luci/docker-credential-luci/${platform}",
		Version: "git_revision:b2fad5ab18774b86d84aa867287bfb4f2394893b",
	},
	"infra/tools/luci/git-credential-luci/${platform}": {
		Path:    ".",
		Name:    "infra/tools/luci/git-credential-luci/${platform}",
		Version: "git_revision:9119ead6d70953d1f9a7670979431344c2cc3f10",
	},
	"infra/tools/luci/isolate/${platform}": {
		Path:    ".",
		Name:    "infra/tools/luci/isolate/${platform}",
		Version: "git_revision:9119ead6d70953d1f9a7670979431344c2cc3f10",
	},
	"infra/tools/luci/kitchen/${platform}": {
		Path:    ".",
		Name:    "infra/tools/luci/kitchen/${platform}",
		Version: "git_revision:9119ead6d70953d1f9a7670979431344c2cc3f10",
	},
	"infra/tools/luci/lucicfg/${platform}": {
		Path:    ".",
		Name:    "infra/tools/luci/lucicfg/${platform}",
		Version: "git_revision:1b249e92c5aa4afc46cf207293609ce8de14cde4",
	},
	"infra/tools/luci/swarming/${platform}": {
		Path:    ".",
		Name:    "infra/tools/luci/swarming/${platform}",
		Version: "git_revision:9119ead6d70953d1f9a7670979431344c2cc3f10",
	},
	"infra/tools/luci/vpython3/${platform}": {
		Path:    ".",
		Name:    "infra/tools/luci/vpython3/${platform}",
		Version: "git_revision:219778b55493f5026a9802f10a72024ce6896bf3",
	},
	"skia/bots/bazel": {
		Path:    "bazel",
		Name:    "skia/bots/bazel",
		Version: "version:3",
	},
	"skia/bots/bazelisk_linux_amd64": {
		Path:    "bazelisk_linux_amd64",
		Name:    "skia/bots/bazelisk_linux_amd64",
		Version: "version:1",
	},
	"skia/bots/cockroachdb": {
		Path:    "cockroachdb",
		Name:    "skia/bots/cockroachdb",
		Version: "version:4",
	},
	"skia/bots/gcloud_linux": {
		Path:    "gcloud_linux",
		Name:    "skia/bots/gcloud_linux",
		Version: "version:15",
	},
	"skia/bots/go": {
		Path:    "go",
		Name:    "skia/bots/go",
		Version: "version:18",
	},
	"skia/bots/go_win": {
		Path:    "go_win",
		Name:    "skia/bots/go_win",
		Version: "version:5",
	},
	"skia/bots/gsutil": {
		Path:    ".",
		Name:    "skia/bots/gsutil",
		Version: "version:6",
	},
	"skia/bots/node": {
		Path:    "node",
		Name:    "skia/bots/node",
		Version: "version:2",
	},
	"skia/bots/patch_linux_amd64": {
		Path:    ".",
		Name:    "skia/bots/patch_linux_amd64",
		Version: "version:0",
	},
	"skia/bots/protoc": {
		Path:    "protoc",
		Name:    "skia/bots/protoc",
		Version: "version:0",
	},
	"skia/tools/bazel_build_all/${platform}": {
		Path:    ".",
		Name:    "skia/tools/bazel_build_all/${platform}",
		Version: "git_revision:cbdd9976bce93e20b84de153ce1b2838a09018e8",
	},
	"skia/tools/bazel_test_all/${platform}": {
		Path:    ".",
		Name:    "skia/tools/bazel_test_all/${platform}",
		Version: "git_revision:f2fc891dd0fbd4a97cfa21036a95126b5150b834",
	},
	"skia/tools/command_wrapper/${platform}": {
		Path:    ".",
		Name:    "skia/tools/command_wrapper/${platform}",
		Version: "git_revision:1788c591a35921a980672d60be4c47be276aa88c",
	},
	"skia/tools/goldctl/${platform}": {
		Path:    ".",
		Name:    "skia/tools/goldctl/${platform}",
		Version: "git_revision:9119ead6d70953d1f9a7670979431344c2cc3f10",
	},
	"skia/tools/presubmit/${platform}": {
		Path:    ".",
		Name:    "skia/tools/presubmit/${platform}",
		Version: "git_revision:f2fc891dd0fbd4a97cfa21036a95126b5150b834",
	},
}
