apiVersion: v1
kind: Service
metadata:
  labels:
    app: gold-{{.INSTANCE_ID}}-gitilesfollower
  name: gold-{{.INSTANCE_ID}}-gitilesfollower
spec:
  ports:
    - name: metrics
      port: 20000
  selector:
    app: gold-{{.INSTANCE_ID}}-gitilesfollower
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gold-{{.INSTANCE_ID}}-gitilesfollower
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gold-{{.INSTANCE_ID}}-gitilesfollower
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: gold-{{.INSTANCE_ID}}-gitilesfollower
        appgroup: gold
        goldgroup: '{{.INSTANCE_ID}}'
        date: '{{.NOW}}' # Forces a re-deploy even if just the config file changes.
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: 'true'
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsUser: 2000 # aka skia
        fsGroup: 2000 # aka skia
      serviceAccountName: gold-gitilesfollower
      containers:
        - name: gold-{{.INSTANCE_ID}}-gitilesfollower
          image: { { .GITILESFOLLOWER_IMAGE } }
          args:
            - '--common_instance_config=/etc/gold-config/{{.INSTANCE_ID}}.json5'
            - '--config=/etc/gold-config/{{.INSTANCE_ID}}-gitilesfollower.json5'
          ports:
            - containerPort: 20000
              name: prom
          volumeMounts:
            - name: gold-{{.INSTANCE_ID}}-config-volume
              mountPath: /etc/gold-config/
          env:
            - name: K8S_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          resources:
            requests:
              memory: '100Mi'
              cpu: '10m'
              ephemeral-storage: '32M'
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 3
      volumes:
        - name: gold-{{.INSTANCE_ID}}-config-volume
          configMap:
            defaultMode: 400
            name: gold-{{.INSTANCE_ID}}-config
