#!/bin/bash
set -x -e

APPNAME=codereview-watcher
IMAGE=$(dirname "$0")

# Copy files into the right locations in ${ROOT}.
copy_release_files()
{
${INSTALL} --mode=644 -T ${IMAGE}/Dockerfile      ${ROOT}/Dockerfile
${INSTALL} --mode=755 -T ${GOPATH}/bin/${APPNAME} ${ROOT}/usr/local/bin/${APPNAME}
}

source ../bash/docker_build.sh
