---
- hosts: all
  remote_user: chrome-bot
  become_user: root
  become: yes
  become_method: sudo
  tasks:
  - name: hello world!
    command: hostname
  - name: Who are we?
    command: whoami
  - name: sudo apt update
    apt:
      update_cache: yes
  - name: sudo apt upgrade
    apt:
      upgrade: safe
  - name: sudo apt full-upgrade
    apt:
      upgrade: full
  - name: sudo apt autoremove
    apt:
      autoremove: yes
  - name: Enumerate sources.list files.
    find:
      path: /etc/apt/
      recurse: yes
      patterns: '*.list'
    register: sources_list
  - name: with_list
    debug:
      msg: "{{ item.path }}"
    with_list: "{{sources_list.files}}"
  - name: update sources.list to buster
    replace:
      path: "{{ item.path }}"
      regexp: 'stretch'
      replace: 'buster'
    with_list: "{{sources_list.files}}"
  - name: sudo apt update
    apt:
      update_cache: yes
  - name: sudo apt upgrade
    apt:
      upgrade: safe
  - name: sudo apt full-upgrade
    apt:
      upgrade: full
  - name: Reboot the Debian or Ubuntu server
    reboot:
      msg: "Reboot initiated by Ansible script"
      connect_timeout: 5
      reboot_timeout: 300
      pre_reboot_delay: 0
      post_reboot_delay: 30
      test_command: uptime
