include ../../../res/imp/http-server.mk

deps: install_extras

install_extras:
	# We download these here because the default target is called by unittests
	wget --no-clobber https://storage.googleapis.com/skia-infra-testdata/status-demo/alert-widget-demo.json
	wget --no-clobber https://storage.googleapis.com/skia-infra-testdata/status-demo/autoroll-widget-demo.json
	wget --no-clobber https://storage.googleapis.com/skia-infra-testdata/status-demo/commits-canvas-demo.json
	wget --no-clobber https://storage.googleapis.com/skia-infra-testdata/status-demo/status-sk-demo-0.json
	wget --no-clobber https://storage.googleapis.com/skia-infra-testdata/status-demo/status-sk-demo-1.json
	wget --no-clobber https://storage.googleapis.com/skia-infra-testdata/status-demo/status-sk-demo-2.json
	wget --no-clobber https://storage.googleapis.com/skia-infra-testdata/status-demo/status-sk-demo-3.json
	wget --no-clobber https://storage.googleapis.com/skia-infra-testdata/status-demo/status-sk-demo-4.json
	wget --no-clobber https://storage.googleapis.com/skia-infra-testdata/status-demo/status-sk-demo-5.json
	wget --no-clobber https://storage.googleapis.com/skia-infra-testdata/status-demo/status-sk-demo-6.json
	wget --no-clobber https://storage.googleapis.com/skia-infra-testdata/status-demo/status-sk-demo-7.json
	wget --no-clobber https://storage.googleapis.com/skia-infra-testdata/status-demo/status-sk-demo-8.json
	wget --no-clobber https://storage.googleapis.com/skia-infra-testdata/status-demo/status-sk-demo-9.json
	wget --no-clobber https://storage.googleapis.com/skia-infra-testdata/status-demo/status-sk-demo-10.json
