apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: rpi-swarming-client
spec:
  selector:
    matchLabels:
      name: rpi-swarming-client
  template:
    metadata:
      labels:
        name: rpi-swarming-client
    spec:
      #securityContext:
      #  fsGroup: 2000
      imagePullSecrets:
        - name: gcr-io-skia-public
      containers:
        - name: rpi-swarming-client
          image: gcr.io/skia-public/rpi-swarming-client:2019-11-06T17_07_03Z-jcgregorio-fb43a38-dirty
          securityContext:
            privileged: true
            capabilities:
              add:
                - ALL
          env:
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
          - mountPath: /b
            name: local-swarming-workingset
          - name: dev
            mountPath: /dev
          - name: sys
            mountPath: /sys
          - mountPath: /root/.android
            name: skolo-rpi-adb-key
      volumes:
      - name: local-swarming-workingset
        hostPath:
          # directory location on host
          path: /var/swarming
          # this field is optional
          type: Directory
      - name: dev
        hostPath:
          path: /dev
      - name: sys
        hostPath:
          path: /sys
      - name: skolo-rpi-adb-key
        secret:
          secretName: skolo-rpi-adb-key