apiVersion: v1
kind: Service
metadata:
  labels:
    app: docserverk
  name: docserverk
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8000
    - name: metrics
      protocol: TCP
      port: 20000
  selector:
    app: docserverk
  type: NodePort
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: docserverk
spec:
  selector:
    matchLabels:
      app: docserverk # Label selector that determines which Pods belong to the StatefulSet
                 # Must match spec: template: metadata: labels
  serviceName: "docserverk"
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: docserverk # Pod template's label selector
    spec:
      volumes:
      - name: skia-docs-sa
        secret:
          secretName: skia-docs
      terminationGracePeriodSeconds: 10
      containers:
      - name: docserverk
        image: gcr.io/skia-public/docserver:2018-04-20T21_21_48Z-jcgregorio-f40851bf4611a844bb63b289e91cddc6eba886ae-dirty
        args:
          - "--logtostderr"
          - "--resources_dir=/usr/local/share/docserver/"
          - "--work_dir=/mnt/pd0"
        ports:
          - name: http
            containerPort: 8000
          - name: metrics
            containerPort: 20000
        resources:
          requests:
            cpu: "500m"
            memory: "100Mi"
        volumeMounts:
        - name: skia-docs-sa
          mountPath: /var/secrets/google
        - name: docserverk-storage
          mountPath: /mnt/pd0
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/key.json
  volumeClaimTemplates:
  - metadata:
      name: docserverk-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 500Mi
