#!/bin/bash
# Builds and uploads a debian package for status.
APPNAME=status-staging
DESCRIPTION="Server which provides status information about Skia."
SYSTEMD=${APPNAME}.service

# Copy files into the right locations in ${ROOT}.
copy_release_files()
{
INSTALL="fakeroot install -D --verbose --backup=none --group=root --owner=root"
INSTALL_DIR="fakeroot install -d --verbose --backup=none --group=root --owner=root"
${INSTALL} --mode=644 -T ./sys/${APPNAME}.service          ${ROOT}/etc/systemd/system/${APPNAME}.service
${INSTALL} --mode=755 -T ${GOPATH}/bin/status              ${ROOT}/usr/local/bin/status
${INSTALL} --mode=644 -T ./res/img/favicon-open.ico        ${ROOT}/usr/local/share/status/res/img/favicon-open.ico
${INSTALL} --mode=644 -T ./res/img/favicon-closed.ico      ${ROOT}/usr/local/share/status/res/img/favicon-closed.ico
${INSTALL} --mode=644 -T ./res/js/core.js                  ${ROOT}/usr/local/share/status/res/js/core.js
${INSTALL} --mode=644 -T ./res/vul/elements.html           ${ROOT}/usr/local/share/status/res/vul/elements.html
${INSTALL} --mode=644 -T ./templates/header.html           ${ROOT}/usr/local/share/status/templates/header.html
${INSTALL} --mode=644 -T ./templates/commits.html          ${ROOT}/usr/local/share/status/templates/commits.html
${INSTALL} --mode=644 -T ./templates/capacity.html    ${ROOT}/usr/local/share/status/templates/capacity.html
${INSTALL_DIR} --mode=777                                  ${ROOT}/mnt/pd0/status_workdir
}

source ../bash/release.sh
