- name: get rpi k3s version
  hosts: rack4_trial_run
  tasks:
    - name: Copy authorized_keys with owner and permissions
      become: yes
      ansible.builtin.copy:
        src: ../../authorized_keys
        dest: /home/chrome-bot/.ssh/authorized_keys
        owner: chrome-bot
        group: chrome-bot
        mode: '0644'
