/** A list of Android device names and their aliases. */
export const DEVICE_ALIASES: Record<string, string> = {
  '4560MMX_b_sprout': 'Android One',
  '4560MMX_sprout': 'Android One',
  ELE: 'P30',
  'TECNO-KB8': 'Tecno Spark 3 Pro',
  angler: 'Nexus 6p',
  athene: 'Moto G4',
  blueline: 'Pixel 3',
  bullhead: 'Nexus 5X',
  chorizo: 'Chromecast',
  coral: 'Pixel 4 XL',
  crosshatch: 'Pixel 3 XL',
  darcy: 'NVIDIA Shield [2017]',
  dragon: 'Pixel C',
  exynos990: 'Galaxy S20',
  flame: 'Pixel 4',
  flo: 'Nexus 7 [2013]',
  flounder: 'Nexus 9',
  foster: 'NVIDIA Shield [2015]',
  fugu: 'Nexus Player',
  gce_x86: 'Android on GCE',
  goyawifi: 'Galaxy Tab 3',
  grouper: 'Nexus 7 [2012]',
  hammerhead: 'Nexus 5',
  herolte: 'Galaxy S7 [Global]',
  heroqlteatt: 'Galaxy S7 [AT&T]',
  'iPad4,1': 'iPad Air',
  'iPad5,1': 'iPad mini 4',
  'iPad6,3': 'iPad Pro [9.7 in]',
  'iPhone7,2': 'iPhone 6',
  'iPhone9,1': 'iPhone 7',
  'iPhone10,1': 'iPhone 8',
  'iPhone12,1': 'iPhone 11',
  j5xnlte: 'Galaxy J5',
  m0: 'Galaxy S3',
  mako: 'Nexus 4',
  manta: 'Nexus 10',
  marlin: 'Pixel XL',
  redfin: 'Pixel 5',
  sailfish: 'Pixel',
  sargo: 'Pixel 3a',
  shamu: 'Nexus 6',
  sprout: 'Android One',
  starlte: 'Galaxy S9',
  sunfish: 'Pixel 4a',
  taimen: 'Pixel2 XL',
  universal7420: 'Galaxy S6',
  walleye: 'Pixel 2',
  zerofltetmo: 'Galaxy S6',
};
