// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	gotypes "go.skia.org/infra/task_scheduler/go/types"

	mock "github.com/stretchr/testify/mock"

	types "go.skia.org/infra/autogardener/go/types"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// ClassifyFailure provides a mock function with given fields: ctx, res, failureClasses, repoURL
func (_m *Client) ClassifyFailure(ctx context.Context, res *types.TaskSummary, failureClasses []*types.FailureClass, repoURL string) (string, error) {
	ret := _m.Called(ctx, res, failureClasses, repoURL)

	if len(ret) == 0 {
		panic("no return value specified for ClassifyFailure")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *types.TaskSummary, []*types.FailureClass, string) (string, error)); ok {
		return rf(ctx, res, failureClasses, repoURL)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *types.TaskSummary, []*types.FailureClass, string) string); ok {
		r0 = rf(ctx, res, failureClasses, repoURL)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *types.TaskSummary, []*types.FailureClass, string) error); ok {
		r1 = rf(ctx, res, failureClasses, repoURL)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GenerateReport provides a mock function with given fields: ctx, repo, branch, numCommits
func (_m *Client) GenerateReport(ctx context.Context, repo string, branch string, numCommits int) (*types.Report, error) {
	ret := _m.Called(ctx, repo, branch, numCommits)

	if len(ret) == 0 {
		panic("no return value specified for GenerateReport")
	}

	var r0 *types.Report
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int) (*types.Report, error)); ok {
		return rf(ctx, repo, branch, numCommits)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int) *types.Report); ok {
		r0 = rf(ctx, repo, branch, numCommits)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Report)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, int) error); ok {
		r1 = rf(ctx, repo, branch, numCommits)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTaskSummary provides a mock function with given fields: ctx, task
func (_m *Client) GetTaskSummary(ctx context.Context, task *gotypes.Task) (*types.TaskSummary, error) {
	ret := _m.Called(ctx, task)

	if len(ret) == 0 {
		panic("no return value specified for GetTaskSummary")
	}

	var r0 *types.TaskSummary
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gotypes.Task) (*types.TaskSummary, error)); ok {
		return rf(ctx, task)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gotypes.Task) *types.TaskSummary); ok {
		r0 = rf(ctx, task)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.TaskSummary)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gotypes.Task) error); ok {
		r1 = rf(ctx, task)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
