# This is the file which defines the DAG of tasks.

# Pinned version of the infra-side code, eg. canned steps, API version, etc.
version: 0.1.0/abc123

# GCP project ID.
project: skia-swarming-bots

# Static, pinned images generated elsewhere and used here. We'd want to roll
# them periodically, which I think is orthogonal to this configuration.
images:
  build-task-drivers:
    name: golang:1.13
    sha256: f19be6b8095d6ea46f5345e2651eec4e5ee9e84fc83f3bc3b73587197853dc9e
  linux-build:
    name: debian:buster
    sha256: f19be6b8095d6ea46f5345e2651eec4e5ee9e84fc83f3bc3b73587197853dc9e
  linux-run:
    name: debian:buster
    sha256: f19be6b8095d6ea46f5345e2651eec4e5ee9e84fc83f3bc3b73587197853dc9e
  skps:
    name: gcr.io/skia-resources/skps
    sha256: f19be6b8095d6ea46f5345e2651eec4e5ee9e84fc83f3bc3b73587197853dc9e
  skimage:
    name: gcr.io/skia-resources/skimage
    sha256: f19be6b8095d6ea46f5345e2651eec4e5ee9e84fc83f3bc3b73587197853dc9e

# Definitions of all tasks. You'll notice that the dependencies between tasks
# are implicit, based on the images and resources specified as inputs and
# outputs to each task. I think we'd offer a command-line tool which could
# validate the DAG implied by this file as well as roll versions of dependent
# images, etc.
tasks:
  Build-Debian9-Clang-x86_64-Debug:
    # Descriptors indicating which machines can run this task. We might rename
    # in a non-Swarming world.
    dimensions:
      cpu: x86-64-Haswell_GCE
      gpu: none
      machine_type: n1-highcpu-64
      os: Debian-9.8
      # Note that for security reasons we may want to move the "pool" dimension
      # outside of the individual task definition and into a repo-wide config.
      pool: Skia
    # This task runs "docker build", which is a canned task definition which
    # implicitly runs a task driver (whose build is regenerated on the infra
    # side, pinned, and rolled periodically).
    docker-build:
      # The Dockerfile used to perform the build. Path is relative to the repo
      # root.
      file: docker/Dockerfile.Build-Debian9-Clang-x86_64-Debug
      # Base image used for this build. It's specified by name here, but we will
      # always use the sha256 sum (either specified in the "images" section
      # above or obtained from the task which generated it) when running the
      # task.
      base: linux-build
      # Docker images generated by this build. Note that images generated by
      # tasks are not named in the "images" section. I think we'd have these
      # pushed to a different image registry than we currently use for our
      # "production" images, eg. "build intermediates", with the option to push
      # to skia-public (we'd need to think through the security implications of
      # that).
      outputs:
        dm.Build-Debian9-Clang-x86_64-Debug:
          image: dm.Build-Debian9-Clang-x86_64-Debug
          target: dm
        nanobench.Build-Debian9-Clang-x86_64-Debug:
          image: nanobench.Build-Debian9-Clang-x86_64-Debug
          target: nanobench
      # Any extra --build-arg may be defined here. "--build-arg base=<sha256>"
      # is implied by the "base" parameter. Note that in this formulation the
      # compile flags are part of the Dockerfile, which implies that each build
      # task has its own Dockerfile. In Skia, with so many different build
      # configurations, we'd probably want to have a script to generate all of
      # the Dockerfiles. An alternative would be to group all builds which use
      # the same build environment into a single Dockerfile and pass the compile
      # flags as build-args. The downside would be that a developer needs to
      # type the build-args in order to reproduce a given build.
      build-args:
        REPO: <(REPO)
        REVISION: <(REVISION)
        PATCH_REF: <(PATCH_REF)

  Test-Debian9-Clang-GCE-CPU-AVX2-x86_64-Debug-All:
    # Descriptors indicating which machines can run this task. We might rename
    # in a non-Swarming world.
    dimensions:
      cpu: x86-64-Haswell_GCE
      gpu: none
      machine_type: n1-standard-16
      os: Debian-9.8
      # Note that for security reasons we may want to move the "pool" dimension
      # outside of the individual task definition and into a repo-wide config.
      pool: Skia
    # This task runs "docker run", which is a canned task definition which
    # implicitly runs a task driver (whose build is regenerated on the infra
    # side, pinned, and rolled periodically).
    docker-run:
      # Docker image used to create the container in which the command runs.
      image: linux-run
      # Artifacts are Docker images which are used to deliver files needed by
      # this task. They replace isolates and CIPD packages. Best practice is to
      # base them on the empty "scratch" image to avoid transferring unnecessary
      # OS files. The docker-run task driver takes these as inputs, extracts the
      # specified files into a temporary directory, and mounts it to the
      # specified location for "docker run".
      artifacts:
        # The "exec" resource contains the compiled binary which is run in the
        # container. It is transferred as a resource rather than the image used
        # for "docker run" because we may want to run the same binary within
        # different contexts.
        dm.Build-Debian9-Clang-x86_64-Debug:
          image: dm.Build-Debian9-Clang-x86_64-Debug
          source: /out
          mount: /exec
        # The "task-driver" resource contains the compiled task driver which is
        # run in the container.
        task-driver:
          image: image_Build-Task-Drivers-Linux_amd64
          source: /out
          mount: /task-drivers
        # The following are other artifacts needed by the task, pinned in the
        # "images" section of this file.
        skps:
          image: skps
          source: /skps
          mount: /skps
        skimage:
          image: skimage
          source: /skimage
          mount: /skimage
      # This is the command which is run inside the container. Note that we're
      # moving all of the logic about what the task should do (eg. dm flags,
      # platform, etc) outside of the task itself. We want a task driver for
      # this task so that we can pipe the results of multiple steps (eg.
      # transferring files to/from devices, uploading generated images, etc) to
      # the UI.
      command: [
        "/task-drivers/dm", "--dm=/exec/dm", "--",
        "--skps", "/skps",
        "--skimage", "/skimage",
        "--properties", "gitHash", "$revision", "builder", "$task_name", "task_id", "$task_id",
        "--key", "arch", "x86_64", "compiler", "Clang",
        "--nogpu",
        "--config", "8888",
        "--src", "tests", "gm", "image", "colorImage",
        "--blacklist", "_", "image", "gen_platf", "error",
      ]

  Build-Task-Drivers-Linux_amd64:
    # Descriptors indicating which machines can run this task. We might rename
    # in a non-Swarming world.
    dimensions:
      cpu: x86-64-Haswell_GCE
      gpu: none
      machine_type: n1-highmem-2
      os: Debian-9.8
      # Note that for security reasons we may want to move the "pool" dimension
      # outside of the individual task definition and into a repo-wide config.
      pool: Skia
    docker-build:
      file: docker/Dockerfile.Build-Task-Drivers
      base: build-task-drivers
      outputs:
        task-driver:
          image: image_Build-Task-Drivers-Linux_amd64
      build-args:
        arch: amd64
        os: linux

# Definitions of all jobs. The roles of tasks and jobs haven't changed; a job is
# just a pointer to a sub-section of the task DAG.
jobs:
  Test-Debian9-Clang-GCE-CPU-AVX2-x86_64-Debug-All:
    tasks:
      - Test-Debian9-Clang-GCE-CPU-AVX2-x86_64-Debug-All
    trigger: "commit"
