import { MostRecentBinariesRPCResponse } from '../rpc_types';

export const fakeNow = new Date('2022-02-16T00:18:32Z').getTime();

export const fakeMostRecentBinariesRPCResponse: MostRecentBinariesRPCResponse = {
  binaries: [{
    commit: '34e3b35eb460e8668bb063adeefdc1fed857d075',
    patch_issue: '',
    patch_set: '',
    binaries: [{
      metadata: {
        version: 1,
        timestamp: '2022-02-15T23:57:57Z',
        swarming_task_id: '59189d06df0e9611',
        swarming_server: 'https://chromium-swarm.appspot.com',
        task_id: 'rG2vO5FkQOODEHgHf7W8',
        task_name: 'CodeSize-dm-Debian10-Clang-x86_64-Debug',
        compile_task_name: 'Build-Debian10-Clang-x86_64-Debug',
        binary_name: 'dm',
        bloaty_cipd_version: 'version:1',
        bloaty_args: ['build/dm', '-d', 'compileunits,symbols', '-n', '0', '--tsv'],
        patch_issue: '',
        patch_server: '',
        patch_set: '',
        repo: 'https://skia.googlesource.com/skia.git',
        revision: '34e3b35eb460e8668bb063adeefdc1fed857d075',
        commit_timestamp: '2022-02-15T23:42:43Z',
        author: 'Alice (alice@google.com)',
        subject: '[codesize] Define more CodeSize tasks for testing purposes (both for CQ and waterfall).',
      },
    }, {
      metadata: {
        version: 1,
        timestamp: '2022-02-15T23:58:06Z',
        swarming_task_id: '59189d06e2af3411',
        swarming_server: 'https://chromium-swarm.appspot.com',
        task_id: 'Y4gukiEf8Mmq9QBCGWG7',
        task_name: 'CodeSize-fm-Debian10-Clang-x86_64-Debug',
        compile_task_name: 'Build-Debian10-Clang-x86_64-Debug',
        binary_name: 'fm',
        bloaty_cipd_version: 'version:1',
        bloaty_args: ['build/fm', '-d', 'compileunits,symbols', '-n', '0', '--tsv'],
        patch_issue: '',
        patch_server: '',
        patch_set: '',
        repo: 'https://skia.googlesource.com/skia.git',
        revision: '34e3b35eb460e8668bb063adeefdc1fed857d075',
        commit_timestamp: '2022-02-15T23:42:43Z',
        author: 'Alice (alice@google.com)',
        subject: '[codesize] Define more CodeSize tasks for testing purposes (both for CQ and waterfall).',
      },
    }, {
      metadata: {
        version: 1,
        timestamp: '2022-02-15T23:53:20Z',
        swarming_task_id: '59189cb76ad2ae11',
        swarming_server: 'https://chromium-swarm.appspot.com',
        task_id: 'HLLSmfrsVgTTopCIJsvr',
        task_name: 'CodeSize-dm-Debian10-Clang-x86_64-Release',
        compile_task_name: 'Build-Debian10-Clang-x86_64-Release',
        binary_name: 'dm',
        bloaty_cipd_version: 'version:1',
        bloaty_args: ['build/dm', '-d', 'compileunits,symbols', '-n', '0', '--tsv'],
        patch_issue: '',
        patch_server: '',
        patch_set: '',
        repo: 'https://skia.googlesource.com/skia.git',
        revision: '34e3b35eb460e8668bb063adeefdc1fed857d075',
        commit_timestamp: '2022-02-15T23:42:43Z',
        author: 'Alice (alice@google.com)',
        subject: '[codesize] Define more CodeSize tasks for testing purposes (both for CQ and waterfall).',
      },
    }, {
      metadata: {
        version: 1,
        timestamp: '2022-02-15T23:53:14Z',
        swarming_task_id: '59189cb75f381a11',
        swarming_server: 'https://chromium-swarm.appspot.com',
        task_id: 'iO6VEoDAQkmCub4d9otW',
        task_name: 'CodeSize-fm-Debian10-Clang-x86_64-Release',
        compile_task_name: 'Build-Debian10-Clang-x86_64-Release',
        binary_name: 'fm',
        bloaty_cipd_version: 'version:1',
        bloaty_args: ['build/fm', '-d', 'compileunits,symbols', '-n', '0', '--tsv'],
        patch_issue: '',
        patch_server: '',
        patch_set: '',
        repo: 'https://skia.googlesource.com/skia.git',
        revision: '34e3b35eb460e8668bb063adeefdc1fed857d075',
        commit_timestamp: '2022-02-15T23:42:43Z',
        author: 'Alice (alice@google.com)',
        subject: '[codesize] Define more CodeSize tasks for testing purposes (both for CQ and waterfall).',
      },
    }],
  }, {
    commit: '',
    patch_issue: '509502',
    patch_set: '4',
    binaries: [{
      metadata: {
        version: 1,
        timestamp: '2022-02-15T23:52:24Z',
        swarming_task_id: '59189b98fa88f511',
        swarming_server: 'https://chromium-swarm.appspot.com',
        task_id: 'vibAeTb0bEEoh75iKymJ',
        task_name: 'CodeSize-dm-Debian10-Clang-x86_64-Release',
        compile_task_name: 'Build-Debian10-Clang-x86_64-Release',
        compile_task_name_no_patch: 'Build-Debian10-Clang-x86_64-Release-NoPatch',
        binary_name: 'dm',
        bloaty_cipd_version: 'version:1',
        bloaty_args: ['build/dm', '-d', 'compileunits,symbols', '-n', '0', '--tsv'],
        bloaty_diff_args: ['build/dm', '--', 'build_nopatch/dm'],
        patch_issue: '509502',
        patch_server: 'https://skia-review.googlesource.com',
        patch_set: '4',
        repo: 'https://skia.googlesource.com/skia.git',
        revision: '149938e8e34f042e67719daef4a4ece91478fd55',
        commit_timestamp: '2022-02-15 23:17:39.000000000',
        author: 'Bob (bob@google.com)',
        subject: 'serialization framework down to the Slug level, but not runs',
      },
    }],
  }, {
    commit: '',
    patch_issue: '509557',
    patch_set: '1',
    binaries: [{
      metadata: {
        version: 1,
        timestamp: '2022-02-15T23:52:17Z',
        swarming_task_id: '59189b98ec009111',
        swarming_server: 'https://chromium-swarm.appspot.com',
        task_id: 'YEB1xW1ZQIuxeklV5NOy',
        task_name: 'CodeSize-dm-Debian10-Clang-x86_64-Release',
        compile_task_name: 'Build-Debian10-Clang-x86_64-Release',
        compile_task_name_no_patch: 'Build-Debian10-Clang-x86_64-Release-NoPatch',
        binary_name: 'dm',
        bloaty_cipd_version: 'version:1',
        bloaty_args: ['build/dm', '-d', 'compileunits,symbols', '-n', '0', '--tsv'],
        bloaty_diff_args: ['build/dm', '--', 'build_nopatch/dm'],
        patch_issue: '509557',
        patch_server: 'https://skia-review.googlesource.com',
        patch_set: '1',
        repo: 'https://skia.googlesource.com/skia.git',
        revision: '149938e8e34f042e67719daef4a4ece91478fd55',
        commit_timestamp: '2022-02-15 23:23:56.000000000',
        author: 'Bob (bob@google.com)',
        subject: 'add facilities for flattening different subrun types',
      },
    }],
  }, {
    commit: 'eec8edb6604774dcbf33dedc9d7b6dcf7f032a3f',
    patch_issue: '',
    patch_set: '',
    binaries: [{
      metadata: {
        version: 1,
        timestamp: '2022-02-15T23:29:51Z',
        swarming_task_id: '59188764360c3611',
        swarming_server: 'https://chromium-swarm.appspot.com',
        task_id: 'JRRLh7MFZgwWh4VObRcU',
        task_name: 'CodeSize-dm-Debian10-Clang-x86_64-Release',
        compile_task_name: 'Build-Debian10-Clang-x86_64-Release',
        binary_name: 'dm',
        bloaty_cipd_version: 'version:1',
        bloaty_args: ['build/dm', '-d', 'compileunits,symbols', '-n', '0', '--tsv'],
        patch_issue: '',
        patch_server: '',
        patch_set: '',
        repo: 'https://skia.googlesource.com/skia.git',
        revision: 'eec8edb6604774dcbf33dedc9d7b6dcf7f032a3f',
        commit_timestamp: '2022-02-15T22:40:08Z',
        author: 'Charlie (charlie@google.com)',
        subject: 'Remove skottiekit experiment',
      },
    }],
  }, {
    commit: '149938e8e34f042e67719daef4a4ece91478fd55',
    patch_issue: '',
    patch_set: '',
    binaries: [{
      metadata: {
        version: 1,
        timestamp: '2022-02-15T23:11:17Z',
        swarming_task_id: '591875dac333e811',
        swarming_server: 'https://chromium-swarm.appspot.com',
        task_id: 'bqASxWOnISRhCHZ3p5cd',
        task_name: 'CodeSize-dm-Debian10-Clang-x86_64-Release',
        compile_task_name: 'Build-Debian10-Clang-x86_64-Release',
        binary_name: 'dm',
        bloaty_cipd_version: 'version:1',
        bloaty_args: ['build/dm', '-d', 'compileunits,symbols', '-n', '0', '--tsv'],
        patch_issue: '',
        patch_server: '',
        patch_set: '',
        repo: 'https://skia.googlesource.com/skia.git',
        revision: '149938e8e34f042e67719daef4a4ece91478fd55',
        commit_timestamp: '2022-02-15T22:42:17Z',
        author: 'Charlie (charlie@google.com)',
        subject: '[canvaskit] Rename some CK-specific defines',
      },
    }],
  }],
};
