ARG BASE=golang:1.13

FROM $BASE
COPY . /work
WORKDIR /work
ENV TASK_DRIVERS_DIR="/work/infra/bots/task_drivers"
RUN mkdir ~/out && for td in $(cd ${TASK_DRIVERS_DIR} && ls); do \
  go build -o ~/out/${td} ${TASK_DRIVERS_DIR}/${td}/${td}.go; \
done
