#!/bin/bash
# Builds and uploads a debian package for datastore_backup.
APPNAME=datastore_backup_k
DESCRIPTION="Application to backup Cloud Datastore to Cloud Storage."

set -x -e

# Copy files into the right locations in ${ROOT}.
copy_release_files()
{
INSTALL="install -D --verbose"
${INSTALL} --mode=644 -T ${APPNAME}/Dockerfile    ${ROOT}/Dockerfile
${INSTALL} --mode=755 -T ${GOPATH}/bin/${APPNAME} ${ROOT}/usr/local/bin/${APPNAME}
}

source ../bash/docker_build.sh
