#!/bin/bash
# Builds and uploads a debian package for InfluxDB.
APPNAME=influxdbd
DESCRIPTION="A local cache of the influxdb debian package."

# Don't run the step where we generate an .deb file, we are actually
# copying in the .deb file to be managed.
BYPASS_GENERATION=true

# Copy files into the right locations in ${ROOT}.
copy_release_files()
{
wget https://dl.influxdata.com/influxdb/releases/influxdb_1.1.1_amd64.deb -O ${ROOT}/${APPNAME}.deb
}

source ../bash/release.sh
