#!/bin/bash
APPNAME=task-scheduler-fe

set -x -e

# Copy files into the right locations in ${ROOT}.
copy_release_files()
{
INSTALL="install -D --verbose --backup=none"
INSTALL_DIR="install -d --verbose --backup=none"
${INSTALL} --mode=644 -T ./go/task-scheduler-fe/Dockerfile ${ROOT}/Dockerfile
${INSTALL} --mode=755 -T ${GOPATH}/bin/${APPNAME}          ${ROOT}/usr/local/bin/${APPNAME}
${INSTALL} --mode=644 -T ./res/img/fav.ico                 ${ROOT}/usr/local/share/task-scheduler/res/img/fav.ico
${INSTALL_DIR}                                             ${ROOT}/usr/local/share/${APPNAME}
cp -r                    ./dist                            ${ROOT}/usr/local/share/${APPNAME}/dist
chmod -R                 777                               ${ROOT}/usr/local/share/${APPNAME}/dist
}

source ../bash/docker_build.sh
