import { GetGroupReportResponse, GraphConfig } from '../json';

export const anomaly_table = [
  {
    id: '1',
    test_path:
      'ChromiumPerf/mac-m1_mini_2020-perf/jetstream2/stanford-crypto-aes.Average/JetStream2',
    bug_id: 12345,
    start_revision: 1729647389,
    end_revision: 1739647389,
    is_improvement: false,
    recovered: true,
    state: '',
    statistic: '',
    units: 'ms',
    degrees_of_freedom: 0,
    median_before_anomaly: 75.209091,
    median_after_anomaly: 100.5023,
    p_value: 0,
    segment_size_after: 0,
    segment_size_before: 0,
    std_dev_before_anomaly: 0,
    t_statistic: 0,
    subscription_name: '',
    bug_component: 'Component C',
    bug_labels: [],
    bug_cc_emails: [],
    bisect_ids: [],
  },
  {
    id: '2',
    test_path: 'ChromiumPerf/win-10-perf/jetstream2/stanford-crypto-aes.Average/JetStream2',
    bug_id: 23456,
    start_revision: 1749788389,
    end_revision: 1759747389,
    is_improvement: false,
    recovered: true,
    state: '',
    statistic: '',
    units: 'delta',
    degrees_of_freedom: 0,
    median_before_anomaly: 75.209091,
    median_after_anomaly: 100.5023,
    p_value: 0,
    segment_size_after: 0,
    segment_size_before: 0,
    std_dev_before_anomaly: 0,
    t_statistic: 0,
    subscription_name: '',
    bug_component: 'Component A',
    bug_labels: [],
    bug_cc_emails: [],
    bisect_ids: [],
  },
  {
    id: '3',
    test_path: 'ChromiumPerf/mac-m1-pro-perf/jetstream2/stanford-crypto-aes.Average/JetStream2',
    bug_id: 34567,
    start_revision: 1749787389,
    end_revision: 1759777389,
    is_improvement: false,
    recovered: true,
    state: '',
    statistic: '',
    units: 'ms',
    degrees_of_freedom: 0,
    median_before_anomaly: 1.345,
    median_after_anomaly: 2.403,
    p_value: 0,
    segment_size_after: 0,
    segment_size_before: 0,
    std_dev_before_anomaly: 0,
    t_statistic: 0,
    subscription_name: '',
    bug_component: 'Component B',
    bug_labels: [],
    bug_cc_emails: [],
    bisect_ids: [],
  },
  {
    id: '4',
    test_path: 'ChromiumPerf/win-11-perf/jetstream2/stanford-crypto-aes.Average/JetStream2',
    bug_id: 12345,
    start_revision: 1749747389,
    end_revision: 1759747389,
    is_improvement: true,
    recovered: true,
    state: '',
    statistic: '',
    units: 'ns',
    degrees_of_freedom: 0,
    median_before_anomaly: 72.209091,
    median_after_anomaly: 73.5023,
    p_value: 0,
    segment_size_after: 0,
    segment_size_before: 0,
    std_dev_before_anomaly: 0,
    t_statistic: 0,
    subscription_name: '',
    bug_component: 'Component B',
    bug_labels: [],
    bug_cc_emails: [],
    bisect_ids: [],
  },
  {
    id: '5',
    test_path: 'ChromiumPerf/linux-perf-pgo/jetstream2/stanford-crypto-aes.Average/JetStream2',
    bug_id: -1,
    start_revision: 1849647389,
    end_revision: 1850947244,
    is_improvement: false,
    recovered: true,
    state: '',
    statistic: '',
    units: 'ms',
    degrees_of_freedom: 0,
    median_before_anomaly: 75.209091,
    median_after_anomaly: 100.5023,
    p_value: 0,
    segment_size_after: 0,
    segment_size_before: 0,
    std_dev_before_anomaly: 0,
    t_statistic: 0,
    subscription_name: '',
    bug_component: 'Component C',
    bug_labels: [],
    bug_cc_emails: [],
    bisect_ids: [],
  },
];

export const GROUP_REPORT_RESPONSE_WITH_SID: GetGroupReportResponse = {
  sid: 'test-sid',
  anomaly_list: anomaly_table,
  timerange_map: {
    1: { begin: 1719220000, end: 1719223600 },
    2: { begin: 1719227200, end: 1719230800 },
  },
  selected_keys: null,
  error: '',
  is_commit_number_based: true,
};

export const GROUP_REPORT_RESPONSE: GetGroupReportResponse = {
  sid: '',
  anomaly_list: anomaly_table,
  timerange_map: {
    1: { begin: 1719220000, end: 1719223600 },
    2: { begin: 1719227200, end: 1719230800 },
  },
  selected_keys: null,
  error: '',
  is_commit_number_based: true,
};

export const graphConfig: GraphConfig[] = [
  {
    keys: '',
    formulas: [],
    queries: ['config=8888&arch=x86'],
  },
];

export const groupRowsCount = 2;
