import '../node_modules/@webcomponents/custom-elements/custom-elements.min.js'
import 'infra-sk/modules/login-sk'
import 'elements-sk/collapse-sk'
import '../modules/triage2-sk'
import '../modules/word-cloud-sk'
import '../modules/commit-detail-sk'
