name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the code
      uses: actions/checkout@v4

    - name: Start emulators
      run: ./scripts/run_emulators/run_emulators start

    - name: Build
      run: $HOME/bazelisk test //perf/...
